# -*- coding: utf-8 -*-
"""ADHD_Dec.23rd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110s3rp8OHzjUioTFyYrzUfVk8ESR3eek

医学影像不是图片，是结构化科研数据

BIDS 是“医学影像的语言”

sub / ses / anat 的含义

MRI ≠ CNN

3D → 2D（slice）

形状（shape）比数值更重要

CNN 不是黑箱

参数是怎么算出来的

为什么 Dense 层会爆参数

科研第一步不是 accuracy

而是 pipeline 能不能跑通

上节课我们：MRI → slice → CNN

但现在它少了 3 个东西：

没有 label

没有 subject-level 对齐

没有 train / test split

这节课我们：

participants.tsv
        ↓
subject_id ↔ diagnosis
        ↓
MRI → slice → X
label → y
        ↓
CNN training

今天我们要做的不是“训练一个很准的 ADHD 模型”，而是做一件更重要的事：
把真实医学数据（BIDS + participants.tsv）变成一个不犯科研错误的 baseline 模型。

你们会学到三件事：

标签不在 MRI 里，在 participants.tsv 里

一个被试只能算一个样本（否则会 data leakage）

医学模型的核心不是 accuracy，而是 AUC / Recall / 阈值选择

---
我们现在的数据长什么样？

我们最终的数据表（合并后）每一行代表一个 subject，包含：

sub_id：被试编号（匿名）

t1_path：T1 结构像路径

y：二分类标签（0=Control, 1=ADHD）

age / gender：协变量（可能是 confound）

我们这一节课只用 T1 的中央切片（2D） 做 baseline。
"""

# ===============================
# Cell 1 - Setup & Paths (Drive)
# ===============================

import os
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

# 🔧 按你的真实路径改这里（Peking_1 的位置）
BASE_DIR = "/content/drive/MyDrive/ADHD200/Peking_1"

# ✅ participants.tsv 就在 Peking_1 文件夹内
PARTICIPANTS_TSV = os.path.join(BASE_DIR, "participants.tsv")

print("BASE_DIR =", BASE_DIR)
print("PARTICIPANTS_TSV =", PARTICIPANTS_TSV)
print("BASE_DIR exists:", os.path.exists(BASE_DIR))
print("TSV exists:", os.path.exists(PARTICIPANTS_TSV))

# 小检查：列一下 Peking_1 顶层文件，确认 participants.tsv 在
print("\nTop-level files in BASE_DIR:")
print(sorted(os.listdir(BASE_DIR))[:30])

"""这一节我们要把 pipeline 升级为真正科研版：

上节课：
MRI → slice → CNN（假标签）

这节课：
participants.tsv → (sub_id ↔ diagnosis) → MRI → slice → CNN（真标签）

关键点：

标签来自 TSV，不在 MRI 里

拆分 train/test 必须按 subject（防 data leakage）
"""

# ===============================
# Cell 3A - Inspect participants.tsv (robust encoding)
# ===============================

import pandas as pd

# 常见编码顺序尝试
encodings_to_try = ["utf-8", "latin1", "ISO-8859-1", "cp1252"]

df_p = None
for enc in encodings_to_try:
    try:
        df_p = pd.read_csv(PARTICIPANTS_TSV, sep="\t", encoding=enc)
        print(f"✅ Successfully read with encoding: {enc}")
        break
    except UnicodeDecodeError as e:
        print(f"❌ Failed with encoding: {enc}")

assert df_p is not None, "所有常见编码都失败了（极少见），请告诉我"

print("participants.tsv shape:", df_p.shape)
print("\nColumns:", list(df_p.columns))
display(df_p.head())

"""真实世界数据第一坑——编码（encoding）

你们刚刚遇到的 UnicodeDecodeError 很典型：
真实科研数据经常不是 UTF-8。

这不是你们错，也不是 pandas 错，是数据的历史遗留问题。

正确做法不是“硬改文件”，而是：
在读取时明确指定 encoding（例如 latin1）。
"""

# ===============================
# Cell 3B - Build label table (sub_id, y) from participants.tsv
# ===============================

import pandas as pd
import numpy as np

df_p = pd.read_csv(PARTICIPANTS_TSV, sep="\t", encoding="latin1")
print("participants.tsv shape:", df_p.shape)

# 1) 标准化 sub_id
df_p["sub_id"] = df_p["participant_id"].astype(str).apply(lambda x: f"sub-{x}")

# 2) 把 dx 文本映射到二分类标签 y
#    Control: Typically Developing Children
#    ADHD: any label containing "ADHD"
dx = df_p["dx"].astype(str)

y = np.full(len(df_p), np.nan, dtype=float)
y[dx.str.contains("Typically Developing", case=False, na=False)] = 0
y[dx.str.contains("ADHD", case=False, na=False)] = 1

df_lab = df_p[["sub_id", "dx", "gender", "age", "qc_anatomical_1"]].copy()
df_lab["y"] = y

print("\nRaw dx value counts (top):")
print(df_lab["dx"].value_counts().head(10))

print("\nLabel y value counts:")
print(df_lab["y"].value_counts(dropna=False))

display(df_lab.head())

# ===============================
# Cell 3C - Optional: QC filter (anatomical Pass only)
# ===============================

df_lab_qc = df_lab.copy()

# 只保留 qc_anatomical_1 == Pass
df_lab_qc = df_lab_qc[df_lab_qc["qc_anatomical_1"].astype(str).str.lower() == "pass"]

# 只保留有 y 的
df_lab_qc = df_lab_qc.dropna(subset=["y"]).copy()
df_lab_qc["y"] = df_lab_qc["y"].astype(int)

print("After QC+label filter:", df_lab_qc.shape)
print(df_lab_qc["y"].value_counts())
display(df_lab_qc.head())

# ===============================
# Cell 4 - Collect T1 files (BIDS)
# ===============================

import os
import pandas as pd

def collect_t1_files(base_dir, ses_id="ses-1"):
    t1_list = []
    for sub in sorted(os.listdir(base_dir)):
        if not sub.startswith("sub-"):
            continue
        anat_dir = os.path.join(base_dir, sub, ses_id, "anat")
        if not os.path.exists(anat_dir):
            continue
        for fname in os.listdir(anat_dir):
            if fname.endswith("_T1w.nii.gz"):
                t1_list.append({
                    "sub_id": sub,
                    "ses_id": ses_id,
                    "t1_path": os.path.join(anat_dir, fname)
                })
    return pd.DataFrame(t1_list)

df_t1 = collect_t1_files(BASE_DIR, ses_id="ses-1")
print("T1 files found:", df_t1.shape[0])
display(df_t1.head())

# ===============================
# Cell 5 - Merge MRI paths with labels
# ===============================

# ✅ 用 QC 版本（推荐）
use_qc = True

label_table = df_lab_qc if use_qc else df_lab.dropna(subset=["y"]).copy()
label_table["y"] = label_table["y"].astype(int)

df = df_t1.merge(label_table[["sub_id", "y", "gender", "age"]], on="sub_id", how="inner")

print("Merged dataset shape:", df.shape)
print("Class distribution (y):")
print(df["y"].value_counts())

display(df.head())

"""最重要的科研规范——Subject-level（防 data leakage）

今天我们必须强调一句话：

一个 subject 只能出现一次。

因为同一个人可能有：

run-1 / run-2 两份结构像
如果我们不去重，训练集可能看到 run-1，测试集又看到 run-2，结果会虚高。

你们的去重结果：

合并后 180 条记录

去重后变成 130 个 subject（更接近真实）

这一步决定了你模型是否“可信”。
"""

# ===============================
# Cell 5.5 - De-duplicate by subject (one T1 per sub_id)
# ===============================

import pandas as pd

# 检查哪些 sub 重复
dup_counts = df["sub_id"].value_counts()
dups = dup_counts[dup_counts > 1]
print("Subjects with duplicate T1 entries:", len(dups))
display(dups.head(10))

# 去重策略：同一个 sub_id 保留第一条（最简单、最稳的 baseline）
df = df.sort_values(["sub_id", "t1_path"]).drop_duplicates(subset=["sub_id"], keep="first").reset_index(drop=True)

print("After dedup, dataset shape:", df.shape)
print("Class distribution (y):")
print(df["y"].value_counts())
display(df.head())

"""我们怎么把 MRI 变成 CNN 输入？

MRI 是 3D 体积数据（X, Y, Z）
我们先取 z 轴中间切片当作 2D 图片

这不是最强方法，但它是最清晰、最适合教学的 baseline。
"""

# ===============================
# Cell 6 - Load middle slice
# ===============================

import nibabel as nib
import numpy as np

def load_middle_slice(t1_path):
    vol = nib.load(t1_path).get_fdata()
    z_mid = vol.shape[2] // 2
    sl = vol[:, :, z_mid].astype(np.float32)

    vmin, vmax = sl.min(), sl.max()
    if vmax > vmin:
        sl = (sl - vmin) / (vmax - vmin)
    else:
        sl = np.zeros_like(sl, dtype=np.float32)
    return sl

# sanity check
sl0 = load_middle_slice(df.loc[0, "t1_path"])
print("One slice shape:", sl0.shape, "min/max:", float(sl0.min()), float(sl0.max()))

"""为什么要 resize？

CNN 要求每张输入图像尺寸一致。
MRI 在不同被试之间尺寸可能不同，所以必须 resize。
我们选择一个课堂友好尺寸：128×128。
"""

# ===============================
# Cell 7 - Resize & build X / y
# ===============================

import tensorflow as tf
import numpy as np
import nibabel as nib

TARGET_H, TARGET_W = 128, 128

def load_middle_slice(t1_path):
    vol = nib.load(t1_path).get_fdata()
    z_mid = vol.shape[2] // 2
    sl = vol[:, :, z_mid].astype(np.float32)
    vmin, vmax = sl.min(), sl.max()
    if vmax > vmin:
        sl = (sl - vmin) / (vmax - vmin)
    else:
        sl = np.zeros_like(sl, dtype=np.float32)
    return sl

def resize_slice(sl, h=TARGET_H, w=TARGET_W):
    sl = sl[..., np.newaxis]  # (H, W, 1)
    sl = tf.image.resize(sl, [h, w], method="bilinear").numpy().astype(np.float32)
    return sl

X_list, y_list, sub_list = [], [], []

for _, row in df.iterrows():
    sl = load_middle_slice(row["t1_path"])
    sl = resize_slice(sl)
    X_list.append(sl)
    y_list.append(int(row["y"]))
    sub_list.append(row["sub_id"])

X = np.stack(X_list, axis=0)  # (N, 128, 128, 1)
y = np.array(y_list, dtype=np.int32)
sub_ids = np.array(sub_list)

print("X shape:", X.shape, "y shape:", y.shape)
print("y distribution:", {0: int((y==0).sum()), 1: int((y==1).sum())})

"""最重要的科研规范——按 subject 拆分 train/test

我们的每一条样本就是一个 subject
所以 train/test split 是安全的

如果未来你用 “多张 slice/每人多条记录”，就必须更小心避免leakage。
"""

# ===============================
# Cell 8 - Train/Test split
# ===============================

from sklearn.model_selection import train_test_split
import numpy as np

idx = np.arange(len(y))
train_idx, test_idx = train_test_split(
    idx, test_size=0.2, random_state=42, stratify=y
)

X_train, y_train = X[train_idx], y[train_idx]
X_test,  y_test  = X[test_idx],  y[test_idx]

print("Train:", X_train.shape, "Test:", X_test.shape)
print("Train y:", {0: int((y_train==0).sum()), 1: int((y_train==1).sum())})
print("Test y:",  {0: int((y_test==0).sum()),  1: int((y_test==1).sum())})

"""为什么不用 Flatten？（回扣上节课）

Flatten 会把特征图“拉直”成超长向量，参数会暴涨，容易过拟合。
所以我们用 GlobalAveragePooling2D：
让模型“看整体特征”，而不是靠巨大 Dense 记住训练集。
"""

# ===============================
# Cell 9 - Small CNN baseline (better for N=130)
# ===============================

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

l2 = 1e-4

inp = layers.Input(shape=(TARGET_H, TARGET_W, 1))

x = layers.Conv2D(8, 3, padding="same", activation="relu",
                  kernel_regularizer=regularizers.l2(l2))(inp)
x = layers.MaxPooling2D(2)(x)

x = layers.Conv2D(16, 3, padding="same", activation="relu",
                  kernel_regularizer=regularizers.l2(l2))(x)
x = layers.MaxPooling2D(2)(x)

x = layers.Conv2D(32, 3, padding="same", activation="relu",
                  kernel_regularizer=regularizers.l2(l2))(x)
x = layers.MaxPooling2D(2)(x)

x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(16, activation="relu", kernel_regularizer=regularizers.l2(l2))(x)
x = layers.Dropout(0.4)(x)

out = layers.Dense(1, activation="sigmoid")(x)

model = models.Model(inp, out)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[tf.keras.metrics.AUC(name="AUC"), "accuracy"]
)

model.summary()

# ===============================
# Cell 10 - Train
# ===============================

from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import tensorflow as tf

classes = np.unique(y_train)
cw = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight = {int(c): float(w) for c, w in zip(classes, cw)}
print("class_weight:", class_weight)

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_AUC", mode="max",
                                     patience=10, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_AUC", mode="max",
                                         factor=0.5, patience=4, min_lr=1e-5, verbose=1)
]

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=80,
    batch_size=8,
    class_weight=class_weight,
    callbacks=callbacks,
    verbose=1
)

"""我们现在看到一个很有意思、也很真实的现象：

在训练集上，AUC 会在 0.45–0.60 之间波动；
但在验证集上，AUC 几乎固定在 0.5。

1. val_AUC 一直是 0.5000

这是最重要、也是最容易被误解的地方。

它意味着什么？

模型在验证集上，没有学到“可泛化的 ADHD 区分信号”

但注意：

❌ 这不是 bug

❌ 这不是代码错

❌ 这不是你参数没调好

这是因为：

T1 结构像 + 单 slice
对 ADHD 来说，本来就是极弱信号

这是 ADHD 领域的“真相”。

2. val_accuracy 有时 0.71、有时 0.33，看起来很乱？

这其实是一个非常好的教学点：

Accuracy 在 类别不平衡 + 小样本 情况下
是一个非常不稳定、而且容易骗人的指标

你现在的验证集大概只有：

~20 多个人

ADHD 可能只有 6–8 个

如果模型“全猜 Control”：

accuracy 也能到 0.7

但 AUC = 0.5

 这正是为什么医学里一定要看 AUC / Recall，而不是 accuracy

3. learning rate 一直在降，是不是“学不动了”？

你看到：

ReduceLROnPlateau reducing learning rate


这说明：

模型在验证集上没有任何持续改善的趋势

这正是 ReduceLROnPlateau 该做的事：

不盲目训练

不让模型在噪声上过拟合

这说明你的训练策略是“成熟的”

这正是为什么 ADHD 的研究通常依赖：

功能像（fMRI）

多模态信息

或更大样本

我们今天做的不是一个“强模型”，
而是一个诚实地反映数据上限的 baseline。

一个你现在「已经可以下的科研结论」

你现在完全可以合理地下结论：

Using single-slice T1-weighted MRI,
a subject-level CNN baseline fails to generalize for ADHD classification,
yielding chance-level validation AUC.

翻成中文就是：

仅使用单张 T1 结构像切片，
CNN 在 ADHD 分类任务上无法泛化，
验证性能接近随机水平。
"""

# ===============================
# Cell 10.5 - Plot training curves
# ===============================

import matplotlib.pyplot as plt

plt.figure()
plt.plot(history.history["AUC"])
plt.plot(history.history["val_AUC"])
plt.xlabel("Epoch")
plt.ylabel("AUC")
plt.legend(["train_AUC", "val_AUC"])
plt.title("Training Curve (AUC)")
plt.show()

"""训练曲线（Cell 10.5）

train_AUC 在 0.45–0.55 之间随机波动

val_AUC 是一条直线 0.5

解读

训练集：模型在“试图”学一些弱模式

验证集：完全没有稳定的泛化信号

这说明不是过拟合，而是**信息不足**。
（如果是过拟合，train 会一路升、val 会一路掉。）
"""

# ===============================
# Cell 11 - Evaluate: AUC + CM + R90 threshold
# ===============================

from sklearn.metrics import roc_auc_score, confusion_matrix
import numpy as np

y_prob = model.predict(X_test).ravel()
test_auc = roc_auc_score(y_test, y_prob)
print("Test AUC:", test_auc)

def eval_at_threshold(y_true, y_prob, thr):
    y_pred = (y_prob >= thr).astype(int)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    recall = tp / (tp + fn + 1e-9)
    precision = tp / (tp + fp + 1e-9)
    acc = (tp + tn) / (tp + tn + fp + fn + 1e-9)
    return {"thr": float(thr), "TN": int(tn), "FP": int(fp), "FN": int(fn), "TP": int(tp),
            "Recall": float(recall), "Precision": float(precision), "ACC": float(acc)}

print("\n== Threshold 0.5 ==")
print(eval_at_threshold(y_test, y_prob, 0.5))

# R90：找最小阈值使 Recall >= 0.90
thr_list = np.linspace(0, 1, 1001)
best = None
for thr in thr_list:
    r = eval_at_threshold(y_test, y_prob, thr)
    if r["Recall"] >= 0.90:
        best = r
        break

print("\n== R90 (Recall >= 0.90) ==")
print(best if best else "No threshold achieves Recall >= 0.90 on this test set.")

"""这个 baseline 模型在测试集上能“排序”（AUC≈0.63），
但在默认阈值下完全不能“判别”（Recall=0）——
这是 ADHD T1 单 slice 的典型结果。

Test AUC = 0.634

这是一个容易被误解、但其实很重要的点。

AUC 在回答什么问题？

随机抽一个 ADHD 和一个 Control，
模型把 ADHD 排在前面的概率是多少？

AUC≈0.63 的含义

比随机好（0.5）

但离“可用判别”还很远

👉 这在 ADHD 文献里非常常见，尤其是：

单模态

T1

小样本

阈值 = 0.5（默认）
TN=17, FP=0, FN=9, TP=0
Recall = 0
ACC ≈ 0.65


解读

模型 一个 ADHD 都不敢报

全部预测为 Control

Accuracy 看起来“还行”，但完全没临床意义

👉 这是医学 AI 里 accuracy 最会骗人的典型例子。

R90（Recall ≥ 0.90）
thr = 0.0
Recall ≈ 1.0
Precision ≈ 0.35
ACC ≈ 0.35


解读

想要“几乎不漏诊 ADHD”

唯一办法：全部判成 ADHD

结果：FP 爆炸

👉 这是“弱信号模型”的必然代价。

我们这个模型其实做了两件事：

第一，它在测试集上给出了 AUC≈0.63，
说明它在排序层面捕捉到了一些弱的 ADHD 相关模式。

但第二，当我们尝试把这个排序结果变成“是否 ADHD”的判断时，
就会发现：

用默认阈值，它一个 ADHD 都不敢报

想要高召回率，就必须接受大量误报

这说明：
T1 结构像的单 slice，对 ADHD 来说，
只包含非常有限、而且不稳定的信息。

这组结果其实“很成功”的三个理由

1.没有数据泄露

去重后 subject-level

train/val/test 分离清晰

2.AUC 与阈值行为一致

AUC>0.5 但阈值下崩 → 弱信号模型

这是“正确失败”

3. R90 分析非常有教学价值

“医学里你想少漏诊，就一定要付出误报的代价”
"""