# -*- coding: utf-8 -*-
"""ADHD_sliceCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110s3rp8OHzjUioTFyYrzUfVk8ESR3eek

医学影像不是图片，是结构化科研数据

BIDS 是“医学影像的语言”

sub / ses / anat 的含义

MRI ≠ CNN

3D → 2D（slice）

形状（shape）比数值更重要

CNN 不是黑箱

参数是怎么算出来的

为什么 Dense 层会爆参数

科研第一步不是 accuracy

而是 pipeline 能不能跑通

上节课我们：MRI → slice → CNN

但现在它少了 3 个东西：

没有 label

没有 subject-level 对齐

没有 train / test split

这节课我们：

participants.tsv
        ↓
subject_id ↔ diagnosis
        ↓
MRI → slice → X
label → y
        ↓
CNN training

今天我们要做的不是“训练一个很准的 ADHD 模型”，而是做一件更重要的事：
把真实医学数据（BIDS + participants.tsv）变成一个不犯科研错误的 baseline 模型。

你们会学到三件事：

标签不在 MRI 里，在 participants.tsv 里

一个被试只能算一个样本（否则会 data leakage）

医学模型的核心不是 accuracy，而是 AUC / Recall / 阈值选择

---
我们现在的数据长什么样？

我们最终的数据表（合并后）每一行代表一个 subject，包含：

sub_id：被试编号（匿名）

t1_path：T1 结构像路径

y：二分类标签（0=Control, 1=ADHD）

age / gender：协变量（可能是 confound）

我们这一节课只用 T1 的中央切片（2D） 做 baseline。
"""

# ===============================
# Cell 1 - Setup & Paths (Drive)
# ===============================

import os
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

# 🔧 按你的真实路径改这里（Peking_1 的位置）
BASE_DIR = "/content/drive/MyDrive/ADHD200/Peking_1"

# ✅ participants.tsv 就在 Peking_1 文件夹内
PARTICIPANTS_TSV = os.path.join(BASE_DIR, "participants.tsv")

print("BASE_DIR =", BASE_DIR)
print("PARTICIPANTS_TSV =", PARTICIPANTS_TSV)
print("BASE_DIR exists:", os.path.exists(BASE_DIR))
print("TSV exists:", os.path.exists(PARTICIPANTS_TSV))

# 小检查：列一下 Peking_1 顶层文件，确认 participants.tsv 在
print("\nTop-level files in BASE_DIR:")
print(sorted(os.listdir(BASE_DIR))[:30])

"""这一节我们要把 pipeline 升级为真正科研版：

上节课：
MRI → slice → CNN（假标签）

这节课：
participants.tsv → (sub_id ↔ diagnosis) → MRI → slice → CNN（真标签）

关键点：

标签来自 TSV，不在 MRI 里

拆分 train/test 必须按 subject（防 data leakage）
"""

# ===============================
# Cell 3A - Inspect participants.tsv (robust encoding)
# ===============================

import pandas as pd

# 常见编码顺序尝试
encodings_to_try = ["utf-8", "latin1", "ISO-8859-1", "cp1252"]

df_p = None
for enc in encodings_to_try:
    try:
        df_p = pd.read_csv(PARTICIPANTS_TSV, sep="\t", encoding=enc)
        print(f"✅ Successfully read with encoding: {enc}")
        break
    except UnicodeDecodeError as e:
        print(f"❌ Failed with encoding: {enc}")

assert df_p is not None, "所有常见编码都失败了（极少见），请告诉我"

print("participants.tsv shape:", df_p.shape)
print("\nColumns:", list(df_p.columns))
display(df_p.head())

"""真实世界数据第一坑——编码（encoding）

你们刚刚遇到的 UnicodeDecodeError 很典型：
真实科研数据经常不是 UTF-8。

这不是你们错，也不是 pandas 错，是数据的历史遗留问题。

正确做法不是“硬改文件”，而是：
在读取时明确指定 encoding（例如 latin1）。
"""

# ===============================
# Cell 3B - Build label table (sub_id, y) from participants.tsv
# ===============================

import pandas as pd
import numpy as np

df_p = pd.read_csv(PARTICIPANTS_TSV, sep="\t", encoding="latin1")
print("participants.tsv shape:", df_p.shape)

# 1) 标准化 sub_id
df_p["sub_id"] = df_p["participant_id"].astype(str).apply(lambda x: f"sub-{x}")

# 2) 把 dx 文本映射到二分类标签 y
#    Control: Typically Developing Children
#    ADHD: any label containing "ADHD"
dx = df_p["dx"].astype(str)

y = np.full(len(df_p), np.nan, dtype=float)
y[dx.str.contains("Typically Developing", case=False, na=False)] = 0
y[dx.str.contains("ADHD", case=False, na=False)] = 1

df_lab = df_p[["sub_id", "dx", "gender", "age", "qc_anatomical_1"]].copy()
df_lab["y"] = y

print("\nRaw dx value counts (top):")
print(df_lab["dx"].value_counts().head(10))

print("\nLabel y value counts:")
print(df_lab["y"].value_counts(dropna=False))

display(df_lab.head())

"""Cell 3B 在做什么？（标签 y 的来源）

目标：从 participants.tsv 生成模型的标签 y。

注意：

MRI 文件里没有标签

标签在 dx 这一列（文本）

我们把它变成二分类：

Typically Developing Children → y=0（Control）

任何包含 ADHD 的 → y=1（ADHD）

你应该看到：

y 的分布（0 有多少，1 有多少）

每一行有：sub_id + dx + y
"""

# ===============================
# Cell 3C - Optional: QC filter (anatomical Pass only)
# ===============================

df_lab_qc = df_lab.copy()

# 只保留 qc_anatomical_1 == Pass
df_lab_qc = df_lab_qc[df_lab_qc["qc_anatomical_1"].astype(str).str.lower() == "pass"]

# 只保留有 y 的
df_lab_qc = df_lab_qc.dropna(subset=["y"]).copy()
df_lab_qc["y"] = df_lab_qc["y"].astype(int)

print("After QC+label filter:", df_lab_qc.shape)
print(df_lab_qc["y"].value_counts())
display(df_lab_qc.head())

"""Cell 3C 在做什么？（QC 过滤，为什么很重要）

目标：只保留结构像 QC=Pass 的被试。

为什么？

如果不做 QC，模型可能学到“扫描质量差”而不是 ADHD

QC 是医学影像的基本规范之一

你应该看到：

过滤后样本数减少（正常）

y 的分布还在（0/1 都还存在）

相当于先把明显模糊的照片删掉再训练
"""

# ===============================
# Cell 4 - Collect T1 files (BIDS)
# ===============================

import os
import pandas as pd

def collect_t1_files(base_dir, ses_id="ses-1"):
    t1_list = []
    for sub in sorted(os.listdir(base_dir)):
        if not sub.startswith("sub-"):
            continue
        anat_dir = os.path.join(base_dir, sub, ses_id, "anat")
        if not os.path.exists(anat_dir):
            continue
        for fname in os.listdir(anat_dir):
            if fname.endswith("_T1w.nii.gz"):
                t1_list.append({
                    "sub_id": sub,
                    "ses_id": ses_id,
                    "t1_path": os.path.join(anat_dir, fname)
                })
    return pd.DataFrame(t1_list)

df_t1 = collect_t1_files(BASE_DIR, ses_id="ses-1")
print("T1 files found:", df_t1.shape[0])
display(df_t1.head())

"""Cell 4 在做什么？（从 BIDS 找到 T1 文件）

目标：遍历 BIDS 目录，把每个 subject 的 T1w 路径收集出来。

BIDS 结构回顾（给学生背诵用）：

sub-xxxx/ses-1/anat/*_T1w.nii.gz

你应该看到：

T1 files found: ...

表格里有 sub_id, t1_path
"""

# ===============================
# Cell 5 - Merge MRI paths with labels
# ===============================

# ✅ 用 QC 版本（推荐）
use_qc = True

label_table = df_lab_qc if use_qc else df_lab.dropna(subset=["y"]).copy()
label_table["y"] = label_table["y"].astype(int)

df = df_t1.merge(label_table[["sub_id", "y", "gender", "age"]], on="sub_id", how="inner")

print("Merged dataset shape:", df.shape)
print("Class distribution (y):")
print(df["y"].value_counts())

display(df.head())

"""Cell 5 在做什么？（合并：影像 + 标签）

目标：把两张表合并：

表 A：df_t1（谁有 MRI）

表 B：df_lab_qc（谁有标签且 QC 合格）

合并后每一行就是一个“可训练样本”（subject-level）。

你看到：

Merged dataset shape: ...

Class distribution (y): ...

最重要的科研规范——Subject-level（防 data leakage）

今天我们必须强调一句话：

一个 subject 只能出现一次。

因为同一个人可能有：

run-1 / run-2 两份结构像
如果我们不去重，训练集可能看到 run-1，测试集又看到 run-2，结果会虚高。

你们的去重结果：

合并后 180 条记录

去重后变成 130 个 subject（更接近真实）

这一步决定了你模型是否“可信”。
"""

# ===============================
# Cell 5.5 - De-duplicate by subject (one T1 per sub_id)
# ===============================

import pandas as pd

# 检查哪些 sub 重复
dup_counts = df["sub_id"].value_counts()
dups = dup_counts[dup_counts > 1]
print("Subjects with duplicate T1 entries:", len(dups))
display(dups.head(10))

# 去重策略：同一个 sub_id 保留第一条（最简单、最稳的 baseline）
df = df.sort_values(["sub_id", "t1_path"]).drop_duplicates(subset=["sub_id"], keep="first").reset_index(drop=True)

print("After dedup, dataset shape:", df.shape)
print("Class distribution (y):")
print(df["y"].value_counts())
display(df.head())

"""Cell 5.5 在做什么？（最关键：去重、防data leakage）

目标：一个 subject 只能出现一次。

为什么会重复？

同一个人可能有 run-1 / run-2

如果不去重：

训练集可能看过这个人

测试集又出现这个人

结果会虚高（data leakage）

我们怎么把 MRI 变成 CNN 输入？

MRI 是 3D 体积数据（X, Y, Z）
我们先取 z 轴中间切片当作 2D 图片

这不是最强方法，但它是最清晰的baseline。
"""

# ===============================
# Cell 6 - Load middle slice
# ===============================

import nibabel as nib
import numpy as np

def load_middle_slice(t1_path):
    vol = nib.load(t1_path).get_fdata()
    z_mid = vol.shape[2] // 2
    sl = vol[:, :, z_mid].astype(np.float32)

    vmin, vmax = sl.min(), sl.max()
    if vmax > vmin:
        sl = (sl - vmin) / (vmax - vmin)
    else:
        sl = np.zeros_like(sl, dtype=np.float32)
    return sl

# sanity check
sl0 = load_middle_slice(df.loc[0, "t1_path"])
print("One slice shape:", sl0.shape, "min/max:", float(sl0.min()), float(sl0.max()))

"""Cell 6 在做什么？（3D → 2D 中央切片）

目标：把 3D MRI 变成 2D 图片，让 CNN 能训练。

我们暂时做最简单的 baseline：

取 z 轴中间 slice

可以看到：

One slice shape: (H, W)

min/max 在 0–1

为什么要 resize？

CNN 要求每张输入图像尺寸一致。
MRI 在不同被试之间尺寸可能不同，所以必须 resize。
我们选择一个课堂友好尺寸：128×128。
"""

# ===============================
# Cell 7 - Resize & build X / y
# ===============================

import tensorflow as tf
import numpy as np
import nibabel as nib

TARGET_H, TARGET_W = 128, 128

def load_middle_slice(t1_path):
    vol = nib.load(t1_path).get_fdata()
    z_mid = vol.shape[2] // 2
    sl = vol[:, :, z_mid].astype(np.float32)
    vmin, vmax = sl.min(), sl.max()
    if vmax > vmin:
        sl = (sl - vmin) / (vmax - vmin)
    else:
        sl = np.zeros_like(sl, dtype=np.float32)
    return sl

def resize_slice(sl, h=TARGET_H, w=TARGET_W):
    sl = sl[..., np.newaxis]  # (H, W, 1)
    sl = tf.image.resize(sl, [h, w], method="bilinear").numpy().astype(np.float32)
    return sl

X_list, y_list, sub_list = [], [], []

for _, row in df.iterrows():
    sl = load_middle_slice(row["t1_path"])
    sl = resize_slice(sl)
    X_list.append(sl)
    y_list.append(int(row["y"]))
    sub_list.append(row["sub_id"])

X = np.stack(X_list, axis=0)  # (N, 128, 128, 1)
y = np.array(y_list, dtype=np.int32)
sub_ids = np.array(sub_list)

print("X shape:", X.shape, "y shape:", y.shape)
print("y distribution:", {0: int((y==0).sum()), 1: int((y==1).sum())})

"""最重要的科研规范——按 subject 拆分 train/test

我们的每一条样本就是一个 subject
所以 train/test split 是安全的

如果未来你用 “多张 slice/每人多条记录”，就必须更小心避免leakage。
"""

# ===============================
# Cell 8 - Train/Test split
# ===============================

from sklearn.model_selection import train_test_split
import numpy as np

idx = np.arange(len(y))
train_idx, test_idx = train_test_split(
    idx, test_size=0.2, random_state=42, stratify=y
)

X_train, y_train = X[train_idx], y[train_idx]
X_test,  y_test  = X[test_idx],  y[test_idx]

print("Train:", X_train.shape, "Test:", X_test.shape)
print("Train y:", {0: int((y_train==0).sum()), 1: int((y_train==1).sum())})
print("Test y:",  {0: int((y_test==0).sum()),  1: int((y_test==1).sum())})

"""为什么不用 Flatten？（回扣上节课）

Flatten 会把特征图“拉直”成超长向量，参数会暴涨，容易过拟合。
所以我们用 GlobalAveragePooling2D：
让模型“看整体特征”，而不是靠巨大 Dense 记住训练集。
"""

# ===============================
# Cell 9 - Small CNN baseline (better for N=130)
# ===============================

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

l2 = 1e-4

inp = layers.Input(shape=(TARGET_H, TARGET_W, 1))

x = layers.Conv2D(8, 3, padding="same", activation="relu",
                  kernel_regularizer=regularizers.l2(l2))(inp)
x = layers.MaxPooling2D(2)(x)

x = layers.Conv2D(16, 3, padding="same", activation="relu",
                  kernel_regularizer=regularizers.l2(l2))(x)
x = layers.MaxPooling2D(2)(x)

x = layers.Conv2D(32, 3, padding="same", activation="relu",
                  kernel_regularizer=regularizers.l2(l2))(x)
x = layers.MaxPooling2D(2)(x)

x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(16, activation="relu", kernel_regularizer=regularizers.l2(l2))(x)
x = layers.Dropout(0.4)(x)

out = layers.Dense(1, activation="sigmoid")(x)

model = models.Model(inp, out)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[tf.keras.metrics.AUC(name="AUC"), "accuracy"]
)

model.summary()

"""Cell 9 在做什么？（定义一个“小 CNN baseline”）

目标：定义一个适合小样本（N≈130）的 CNN。

为什么要“小”？

样本少，模型太大容易过拟合/随机波动

为什么用 GlobalAveragePooling2D？

避免 Flatten 导致参数暴涨（上节课讲过）

"""

# ===============================
# Cell 10 - Train
# ===============================

from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import tensorflow as tf

classes = np.unique(y_train)
cw = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight = {int(c): float(w) for c, w in zip(classes, cw)}
print("class_weight:", class_weight)

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_AUC", mode="max",
                                     patience=10, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_AUC", mode="max",
                                         factor=0.5, patience=4, min_lr=1e-5, verbose=1)
]

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=80,
    batch_size=8,
    class_weight=class_weight,
    callbacks=callbacks,
    verbose=1
)

"""我们现在看到一个很有意思、也很真实的现象：

在训练集上，AUC 会在 0.45–0.60 之间波动；
但在验证集上，AUC 几乎固定在 0.5。

1. val_AUC 一直是 0.5000

这是最重要、也是最容易被误解的地方。

它意味着什么？

模型在验证集上，没有学到“可泛化的 ADHD 区分信号”

但注意：

❌ 这不是 bug

❌ 这不是代码错

❌ 这不是你参数没调好

这是因为：

T1 结构像 + 单 slice
对 ADHD 来说，本来就是极弱信号

这是 ADHD 领域的“真相”。

2. val_accuracy 有时 0.71、有时 0.33，看起来很乱？

这其实是一个非常好的教学点：

Accuracy 在 类别不平衡 + 小样本 情况下
是一个非常不稳定、而且容易骗人的指标

你现在的验证集大概只有：

~20 多个人

ADHD 可能只有 6–8 个

如果模型“全猜 Control”：

accuracy 也能到 0.7

但 AUC = 0.5

 这正是为什么医学里一定要看 AUC / Recall，而不是 accuracy

3. learning rate 一直在降，是不是“学不动了”？

你看到：

ReduceLROnPlateau reducing learning rate


这说明：

模型在验证集上没有任何持续改善的趋势

这正是 ReduceLROnPlateau 该做的事：

不盲目训练

不让模型在噪声上过拟合

这说明你的训练策略是“成熟的”

这正是为什么 ADHD 的研究通常依赖：

功能像（fMRI）

多模态信息

或更大样本

我们今天做的不是一个“强模型”，
而是一个诚实地反映数据上限的 baseline。

一个你现在「已经可以下的科研结论」

你现在完全可以合理地下结论：

Using single-slice T1-weighted MRI,
a subject-level CNN baseline fails to generalize for ADHD classification,
yielding chance-level validation AUC.

翻成中文就是：

仅使用单张 T1 结构像切片，
CNN 在 ADHD 分类任务上无法泛化，
验证性能接近随机水平。
"""

# ===============================
# Cell 10.5 - Plot training curves
# ===============================

import matplotlib.pyplot as plt

plt.figure()
plt.plot(history.history["AUC"])
plt.plot(history.history["val_AUC"])
plt.xlabel("Epoch")
plt.ylabel("AUC")
plt.legend(["train_AUC", "val_AUC"])
plt.title("Training Curve (AUC)")
plt.show()

"""训练曲线（Cell 10.5）

train_AUC 在 0.45–0.55 之间随机波动

val_AUC 是一条直线 0.5

解读

训练集：模型在“试图”学一些弱模式

验证集：完全没有稳定的泛化信号

这说明不是过拟合，而是**信息不足**。
（如果是过拟合，train 会一路升、val 会一路掉。）
"""

# ===============================
# Cell 11 - Evaluate: AUC + CM + R90 threshold
# ===============================

from sklearn.metrics import roc_auc_score, confusion_matrix
import numpy as np

y_prob = model.predict(X_test).ravel()
test_auc = roc_auc_score(y_test, y_prob)
print("Test AUC:", test_auc)

def eval_at_threshold(y_true, y_prob, thr):
    y_pred = (y_prob >= thr).astype(int)
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    recall = tp / (tp + fn + 1e-9)
    precision = tp / (tp + fp + 1e-9)
    acc = (tp + tn) / (tp + tn + fp + fn + 1e-9)
    return {"thr": float(thr), "TN": int(tn), "FP": int(fp), "FN": int(fn), "TP": int(tp),
            "Recall": float(recall), "Precision": float(precision), "ACC": float(acc)}

print("\n== Threshold 0.5 ==")
print(eval_at_threshold(y_test, y_prob, 0.5))

# R90：找最小阈值使 Recall >= 0.90
thr_list = np.linspace(0, 1, 1001)
best = None
for thr in thr_list:
    r = eval_at_threshold(y_test, y_prob, thr)
    if r["Recall"] >= 0.90:
        best = r
        break

print("\n== R90 (Recall >= 0.90) ==")
print(best if best else "No threshold achieves Recall >= 0.90 on this test set.")

"""这个 baseline 模型在测试集上能“排序”（AUC≈0.63），
但在默认阈值下完全不能“判别”（Recall=0）——
这是 ADHD T1 单 slice 的典型结果。

Test AUC = 0.634

这是一个容易被误解、但其实很重要的点。

AUC 在回答什么问题？

随机抽一个 ADHD 和一个 Control，
模型把 ADHD 排在前面的概率是多少？

AUC≈0.63 的含义

比随机好（0.5）

但离“可用判别”还很远

👉 这在 ADHD 文献里非常常见，尤其是：

单模态

T1

小样本

阈值 = 0.5（默认）
TN=17, FP=0, FN=9, TP=0
Recall = 0
ACC ≈ 0.65


解读

模型 一个 ADHD 都不敢报

全部预测为 Control

Accuracy 看起来“还行”，但完全没临床意义

👉 这是医学 AI 里 accuracy 最会骗人的典型例子。

R90（Recall ≥ 0.90）
thr = 0.0
Recall ≈ 1.0
Precision ≈ 0.35
ACC ≈ 0.35


解读

想要“几乎不漏诊 ADHD”

唯一办法：全部判成 ADHD

结果：FP 爆炸

👉 这是“弱信号模型”的必然代价。

我们这个模型其实做了两件事：

第一，它在测试集上给出了 AUC≈0.63，
说明它在排序层面捕捉到了一些弱的 ADHD 相关模式。

但第二，当我们尝试把这个排序结果变成“是否 ADHD”的判断时，
就会发现：

用默认阈值，它一个 ADHD 都不敢报

想要高召回率，就必须接受大量误报

这说明：
T1 结构像的单 slice，对 ADHD 来说，
只包含非常有限、而且不稳定的信息。

这组结果其实“很成功”的三个理由

1.没有数据泄露

去重后 subject-level

train/val/test 分离清晰

2.AUC 与阈值行为一致

AUC>0.5 但阈值下崩 → 弱信号模型

这是“正确失败”

3. R90 分析非常有教学价值

“医学里你想少漏诊，就一定要付出误报的代价”
"""

# ===============================
# Cell 12 -  What if we leak data?
# ===============================

#

# 假设：我们从每个 subject 取 5 个 slice
def load_multi_slices(t1_path, num_slices=5):
    vol = nib.load(t1_path).get_fdata()
    z = vol.shape[2]
    idxs = np.linspace(z*0.3, z*0.7, num_slices).astype(int)
    slices = []
    for zi in idxs:
        sl = vol[:, :, zi].astype(np.float32)
        vmin, vmax = sl.min(), sl.max()
        sl = (sl - vmin) / (vmax - vmin + 1e-9)
        sl = resize_slice(sl)
        slices.append(sl)
    return slices

X_leak, y_leak = [], []

for _, row in df.iterrows():
    slices = load_multi_slices(row["t1_path"], num_slices=5)
    for sl in slices:
        X_leak.append(sl)
        y_leak.append(row["y"])

X_leak = np.stack(X_leak)
y_leak = np.array(y_leak)

print("Leaky dataset shape:", X_leak.shape)

# ===============================
# Helper - define the SAME CNN as Cell 9
# ===============================

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers

def build_small_cnn(target_h=128, target_w=128, l2=1e-4, lr=1e-3):
    inp = layers.Input(shape=(target_h, target_w, 1))

    x = layers.Conv2D(8, 3, padding="same", activation="relu",
                      kernel_regularizer=regularizers.l2(l2))(inp)
    x = layers.MaxPooling2D(2)(x)

    x = layers.Conv2D(16, 3, padding="same", activation="relu",
                      kernel_regularizer=regularizers.l2(l2))(x)
    x = layers.MaxPooling2D(2)(x)

    x = layers.Conv2D(32, 3, padding="same", activation="relu",
                      kernel_regularizer=regularizers.l2(l2))(x)
    x = layers.MaxPooling2D(2)(x)

    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(16, activation="relu",
                     kernel_regularizer=regularizers.l2(l2))(x)
    x = layers.Dropout(0.4)(x)

    out = layers.Dense(1, activation="sigmoid")(x)

    model = models.Model(inp, out)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=lr),
        loss="binary_crossentropy",
        metrics=[tf.keras.metrics.AUC(name="AUC"), "accuracy"]
    )
    return model

# ===============================
# Cell 12.1 - Train & evaluate on leaky slices (WRONG on purpose)
# ===============================

import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import roc_auc_score, confusion_matrix

# 1) slice-level random split（这就是泄露发生的地方）
idx = np.arange(len(y_leak))
train_idx, test_idx = train_test_split(
    idx, test_size=0.2, random_state=42, stratify=y_leak
)

X_train_l, y_train_l = X_leak[train_idx], y_leak[train_idx]
X_test_l,  y_test_l  = X_leak[test_idx],  y_leak[test_idx]

print("Leaky Train:", X_train_l.shape, "Leaky Test:", X_test_l.shape)
print("Leaky Train y:", {0: int((y_train_l==0).sum()), 1: int((y_train_l==1).sum())})
print("Leaky Test y :", {0: int((y_test_l==0).sum()),  1: int((y_test_l==1).sum())})

# 2) 上一个 CNN
model_leak = build_small_cnn(target_h=TARGET_H, target_w=TARGET_W, l2=1e-4, lr=1e-3)

# 3) class_weight
classes = np.unique(y_train_l)
cw = compute_class_weight(class_weight="balanced", classes=classes, y=y_train_l)
class_weight = {int(c): float(w) for c, w in zip(classes, cw)}
print("class_weight:", class_weight)

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_AUC", mode="max",
                                     patience=10, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_AUC", mode="max",
                                         factor=0.5, patience=4, min_lr=1e-5, verbose=1)
]

history_leak = model_leak.fit(
    X_train_l, y_train_l,
    validation_split=0.2,          # ⚠️ 依然是 slice-level 的 val（同样泄露）
    epochs=80,
    batch_size=8,
    class_weight=class_weight,
    callbacks=callbacks,
    verbose=1
)

# 4) Evaluate (AUC + threshold metrics + R90)
y_prob_l = model_leak.predict(X_test_l).ravel()
auc_l = roc_auc_score(y_test_l, y_prob_l)
print("\nLeaky Test AUC:", auc_l)

def eval_at_threshold(y_true, y_prob, thr):
    y_pred = (y_prob >= thr).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    recall = tp / (tp + fn + 1e-9)
    precision = tp / (tp + fp + 1e-9)
    acc = (tp + tn) / (tp + tn + fp + fn + 1e-9)
    return {"thr": float(thr), "TN": int(tn), "FP": int(fp), "FN": int(fn), "TP": int(tp),
            "Recall": float(recall), "Precision": float(precision), "ACC": float(acc)}

print("\n== Leaky Threshold 0.5 ==")
res05_l = eval_at_threshold(y_test_l, y_prob_l, 0.5)
print(res05_l)

# R90
thr_list = np.linspace(0, 1, 1001)
best_l = None
for thr in thr_list:
    r = eval_at_threshold(y_test_l, y_prob_l, thr)
    if r["Recall"] >= 0.90:
        best_l = r
        break

print("\n== Leaky R90 (Recall >= 0.90) ==")
print(best_l if best_l else "No threshold achieves Recall >= 0.90.")

# ===============================
# Cell 12.2 - Compare: No-leak vs Leaky (make a table)
# ===============================

import pandas as pd

# --- ① 把之前 no-leak 的结果粘贴到这里（从 Cell 11 输出复制） ---
no_leak_auc = None          # e.g. 0.6340
no_leak_05  = None          # e.g. {'thr':0.5,'TN':17,'FP':0,'FN':9,'TP':0,'Recall':0.0,'Precision':0.0,'ACC':0.6538}
no_leak_r90 = None          # e.g. {'thr':0.0,'TN':0,'FP':17,'FN':0,'TP':9,'Recall':1.0,'Precision':0.346,'ACC':0.346}

# --- ② leaky 的结果 ---
leak_auc = float(auc_l)
leak_05  = res05_l
leak_r90 = best_l

def pack_row(tag, auc, res05, r90):
    return {
        "Setting": tag,
        "Test AUC": auc,
        "ACC@0.5": res05["ACC"],
        "Recall@0.5": res05["Recall"],
        "Precision@0.5": res05["Precision"],
        "TP@0.5": res05["TP"],
        "FP@0.5": res05["FP"],
        "FN@0.5": res05["FN"],
        "R90_thr": None if r90 is None else r90["thr"],
        "R90_Recall": None if r90 is None else r90["Recall"],
        "R90_Precision": None if r90 is None else r90["Precision"],
        "R90_FP": None if r90 is None else r90["FP"],
        "R90_FN": None if r90 is None else r90["FN"],
    }

rows = []
if (no_leak_auc is not None) and (no_leak_05 is not None):
    rows.append(pack_row("NO leakage (subject-level)", float(no_leak_auc), no_leak_05, no_leak_r90))

rows.append(pack_row("LEAKY (slice-level random split)", float(leak_auc), leak_05, leak_r90))

df_cmp = pd.DataFrame(rows)
display(df_cmp)

# ===============================
# Cell 13 - Correct multi-slice loader (K slices per subject)
# ===============================

import nibabel as nib
import numpy as np

K_SLICES = 5          # 课堂推荐 5（快、稳定、好解释）
ZMIN, ZMAX = 0.30, 0.70

def load_k_slices(t1_path, k=K_SLICES, zmin=ZMIN, zmax=ZMAX):
    """
    从 3D T1 里取 k 张切片（默认取中间 30%~70%），每张做 min-max normalize + resize
    返回 list[(H,W,1)]，float32
    """
    vol = nib.load(t1_path).get_fdata()
    z = vol.shape[2]

    zs = np.linspace(z * zmin, z * zmax, k).astype(int)
    zs = np.clip(zs, 0, z - 1)

    out = []
    for zi in zs:
        sl = vol[:, :, zi].astype(np.float32)
        vmin, vmax = sl.min(), sl.max()
        if vmax > vmin:
            sl = (sl - vmin) / (vmax - vmin)
        else:
            sl = np.zeros_like(sl, dtype=np.float32)

        sl = resize_slice(sl)  # (TARGET_H, TARGET_W, 1)
        out.append(sl)

    return out

# ===============================
# Cell 14 - Subject-level Train/Test split (NO leakage)
# ===============================

from sklearn.model_selection import train_test_split
import numpy as np

y_sub = df["y"].astype(int).values
idx = np.arange(len(df))

train_sub_idx, test_sub_idx = train_test_split(
    idx, test_size=0.2, random_state=42, stratify=y_sub
)

df_train = df.iloc[train_sub_idx].reset_index(drop=True)
df_test  = df.iloc[test_sub_idx].reset_index(drop=True)

print("Subjects - Train:", len(df_train), "Test:", len(df_test))
print("Train y:", df_train["y"].value_counts().to_dict())
print("Test y :", df_test["y"].value_counts().to_dict())

# ===============================
# Cell 15 - Expand subjects -> slices (train/test separately)
# ===============================

import numpy as np

def build_slice_dataset(df_sub, k=K_SLICES):
    X_list, y_list, sub_list = [], [], []

    for _, row in df_sub.iterrows():
        slices = load_k_slices(row["t1_path"], k=k)
        for sl in slices:
            X_list.append(sl)
            y_list.append(int(row["y"]))
            sub_list.append(row["sub_id"])

    X = np.stack(X_list, axis=0)
    y = np.array(y_list, dtype=np.int32)
    sub = np.array(sub_list)
    return X, y, sub

X_train_all, y_train_all, sub_train_all = build_slice_dataset(df_train, k=K_SLICES)
X_test,      y_test,      sub_test      = build_slice_dataset(df_test,  k=K_SLICES)

print("X_train_all:", X_train_all.shape, "X_test:", X_test.shape)
print("Train y:", {0: int((y_train_all==0).sum()), 1: int((y_train_all==1).sum())})
print("Test y :", {0: int((y_test==0).sum()),      1: int((y_test==1).sum())})

# sanity: train/test subject 不重叠
overlap = set(sub_train_all.tolist()) & set(sub_test.tolist())
print("Subject overlap (should be 0):", len(overlap))

# ===============================
# Cell 16 - Subject-level Train/Val split (recommended)
# ===============================

from sklearn.model_selection import train_test_split
import numpy as np

y_train_sub = df_train["y"].astype(int).values
idx2 = np.arange(len(df_train))

train2_idx, val_idx = train_test_split(
    idx2, test_size=0.2, random_state=42, stratify=y_train_sub
)

df_train2 = df_train.iloc[train2_idx].reset_index(drop=True)
df_val    = df_train.iloc[val_idx].reset_index(drop=True)

X_train, y_train, _ = build_slice_dataset(df_train2, k=K_SLICES)
X_val,   y_val,   _ = build_slice_dataset(df_val,    k=K_SLICES)

print("Subjects - Train2:", len(df_train2), "Val:", len(df_val))
print("X_train:", X_train.shape, "X_val:", X_val.shape)

# ===============================
# Cell 17 - Train (same CNN) & slice-level evaluation
# ===============================

import numpy as np
import tensorflow as tf
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import roc_auc_score

model = build_small_cnn(target_h=TARGET_H, target_w=TARGET_W, l2=1e-4, lr=1e-3)
model.summary()

classes = np.unique(y_train)
cw = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight = {int(c): float(w) for c, w in zip(classes, cw)}
print("class_weight:", class_weight)

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_AUC", mode="max",
                                     patience=10, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_AUC", mode="max",
                                         factor=0.5, patience=4, min_lr=1e-5, verbose=1)
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=80,
    batch_size=8,
    class_weight=class_weight,
    callbacks=callbacks,
    verbose=1
)

y_prob = model.predict(X_test).ravel()
auc_slice = roc_auc_score(y_test, y_prob)
print("\nSlice-level Test AUC:", float(auc_slice))

# ===============================
# Cell 18 - Subject-level aggregation AUC (mean over slices)
# ===============================

import numpy as np
from sklearn.metrics import roc_auc_score

sub_unique = np.unique(sub_test)

y_true_sub = []
y_prob_sub = []

for sid in sub_unique:
    m = (sub_test == sid)
    # 同一 subject 的 y 都相同，这里用 mean/round 更鲁棒
    y_true_sub.append(int(np.round(y_test[m].mean())))
    y_prob_sub.append(float(y_prob[m].mean()))

y_true_sub = np.array(y_true_sub, dtype=int)
y_prob_sub = np.array(y_prob_sub, dtype=float)

auc_sub = roc_auc_score(y_true_sub, y_prob_sub)
print("Subject-level Test AUC (mean over slices):", float(auc_sub))
print("N test subjects:", len(sub_unique))

"""结论

使用 T1 加权磁共振成像和二维卷积神经网络 (2D CNN)，

单层和多层 (K=5) 方法

均无法在 ADHD 分类中实现有意义的泛化，

尤其是在严格执行受试者层面数据分割的情况下。

虽然聚合多个切片的预测结果略微提高了

受试者层面的 AUC 值（≈0.53），

但性能仍然接近随机水平，

表明二维结构切片在该任务中的判别信号极其微弱。

这些结果凸显了

适当的受试者层面评估的重要性，以及

基于准确率的指标在小样本医学影像研究中的局限性。

先把每个 T1 配准到标准空间（MNI），再用 atlas 选 ROI，再选 slice。

配准：ANTs / FSL FLIRT/FNIRT（2D/3D 都可，关键是统一到同一个空间）

ROI：用 atlas（Harvard-Oxford, AAL, Desikan-Killiany 等）取：

ACC（anterior cingulate）

IFG / DLPFC（额下回 / 背外侧前额叶）

Striatum：caudate / putamen / accumbens

# ADHD MRI Project — From Baseline to ROI-Guided Modeling

在前面的课程中，我们已经完整地走完了一条**医学影像 AI 的 baseline pipeline**。

## 我们之前做了什么？

我们从真实的 ADHD 数据出发，而不是从“模型”出发：

- 使用 **BIDS 结构** 读取 T1 结构像  
- 从 `participants.tsv` 中构建 **真实标签（ADHD vs Control）**  
- 严格按照 **subject-level** 进行去重和 train / validation / test 拆分，避免 data leakage  
- 将 3D MRI 简化为 **2D slice**，构建了一个小型 CNN baseline  
- 使用 **AUC、Recall、阈值分析（R90）** 进行医学意义上的评估，而不是只看 accuracy  

我们先做了最简单、也是最容易犯错的一步：  
**单张 slice + CNN**。

## 我们遇到了什么问题？

结果非常“真实”，但并不好看：

- 单 slice 的 **AUC 接近 0.5**  
- 即使使用 multi-slice（每人 5 张），subject-level AUC 也只略微提高  
- accuracy 有时看起来还可以，但 Recall 为 0 —— 模型一个 ADHD 都不敢报  

这不是代码错误，也不是模型没调好，而是一个**关键信号**：

> **T1 结构像的单张或少量 slice，本身包含的 ADHD 判别信息极其有限。**

我们还专门演示了一个**错误示范**：

- 如果我们在 slice-level 随机拆分数据  
- 同一个人的不同 slice 同时出现在 train 和 test 中  
- accuracy 和 AUC 会“看起来变好”  

但这是 **data leakage**，是医学 AI 中最常见、也最危险的错误之一。

## 那我们为什么不能直接上 3D CNN？

在这里直接跳到 3D CNN，会掩盖一个非常重要的问题：

> **是模型不够强，还是输入的信息本身就不够？**

如果我们在 2D 情况下：
- 没有确认 input 是否包含有意义的信号  
- 没有理解哪些脑区可能与 ADHD 相关  

那么直接上 3D CNN，很容易变成：
- 模型更复杂  
- 计算更慢  
- 但科研结论更不清楚  

## 所以，我们今天要做什么？

今天这节课，我们做的是**一个“承上启下”的关键步骤**：

> **在进入 3D CNN 之前，先回答一个更基础、也更科研的问题：  
> 如果我们只看“与 ADHD 更相关的脑区”，情况会不会变好？**

为此，我们做三件事：

1. **把每个被试的 T1 结构像配准到标准空间（MNI）**  
   - 让不同人的脑在同一个坐标系下可比较  

2. **使用标准脑图谱（atlas）定义 ADHD 相关 ROI**  
   - 前额叶（PFC）  
   - 前扣带 / 旁扣带（ACC / Paracingulate）  
   - 纹状体 / 丘脑（fronto-striatal circuit）  

3. **只从这些 ROI 覆盖最多的层面中选取多张 slice（例如 20 张）**  
   - 保持 subject-level split  
   - 仍然使用同一个 2D CNN  
   - 最终在 subject-level 上进行预测聚合和评估  

## 今天这一步的意义是什么？

今天我们做的，并不是“让模型立刻变准”，而是：

- 验证：**是否存在 ROI 层面的结构信号**  
- 区分：**信息不足 vs 模型不足**  
- 为下一步（3D CNN / 多模态）提供清晰的科研依据  

如果在 **ROI-guided multi-slice** 的情况下，模型表现仍然接近随机，  
那么我们就可以非常有底气地说：

> **问题不在于 slice 选得不够多，  
> 而在于 T1 结构像本身并不是 ADHD 的主要判别来源。**

这一步，是整个 ADHD 项目中  
**从“工程尝试”走向“科研判断”的分水岭。**
"""

!pip -q install nilearn antspyx

import numpy as np
import nibabel as nib
from nilearn import datasets

mni_t1 = datasets.load_mni152_template()

ho_cort = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-1mm')
ho_sub  = datasets.fetch_atlas_harvard_oxford('sub-maxprob-thr25-1mm')

def ensure_nii(x):
    # nilearn 新版本：x 可能已经是 Nifti1Image
    if isinstance(x, nib.spatialimages.SpatialImage):
        return x
    # 老版本：x 是 path
    return nib.load(x)

cort_img = ensure_nii(ho_cort.maps)
sub_img  = ensure_nii(ho_sub.maps)

cort_labels = list(ho_cort.labels)
sub_labels  = list(ho_sub.labels)

print("cort_img type:", type(cort_img), "shape:", cort_img.shape)
print("sub_img  type:", type(sub_img),  "shape:", sub_img.shape)

print("Cortical labels:", len(cort_labels))
print("Subcortical labels:", len(sub_labels))
print("Example cortical labels:", cort_labels[:8])
print("Example subcortical labels:", sub_labels[:8])

# ROI keywords
roi_keywords_cort = ["cingulate", "frontal", "orbital", "orbitofrontal"]
roi_keywords_sub  = ["caudate", "putamen", "accumbens", "pallidum", "thalamus", "amygdala", "hippocampus"]

def find_label_indices(labels, keywords):
    idx = []
    for i, name in enumerate(labels):
        s = str(name).lower()
        if any(k in s for k in keywords):
            idx.append(i)
    return sorted(set(idx))

roi_idx_cort = find_label_indices(cort_labels, roi_keywords_cort)
roi_idx_sub  = find_label_indices(sub_labels,  roi_keywords_sub)

print("\nSelected cortical ROI labels:")
for i in roi_idx_cort:
    print(i, cort_labels[i])

print("\nSelected subcortical ROI labels:")
for i in roi_idx_sub:
    print(i, sub_labels[i])

"""## ROI 区域定义与选择逻辑（为什么选这些脑区）

在本节课中，我们没有采用“全脑随机取 slice”的方式，而是**基于神经科学与 ADHD 研究背景，明确选择了一组与 ADHD 高度相关的脑区（ROI）**，并只在这些区域中提取切片进行建模。

---

### 一、我们选择了哪些 ROI 区域？

#### 1️⃣ 前额叶皮层（Prefrontal Cortex, PFC）

包含以下区域：
- 额极（Frontal Pole）
- 额上回（Superior Frontal Gyrus）
- 额中回（Middle Frontal Gyrus）
- 额下回·三角部（Inferior Frontal Gyrus, pars triangularis）
- 额下回·盖部（Inferior Frontal Gyrus, pars opercularis）
- 内侧额叶皮层（Frontal Medial Cortex）
- 眶额皮层（Frontal Orbital Cortex）
- 额盖皮层（Frontal Opercular Cortex）

#### 2️⃣ 扣带皮层（Cingulate Cortex）

包含：
- 旁扣带回（Paracingulate Gyrus）
- 前扣带回（Anterior Cingulate Gyrus）
- 后扣带回（Posterior Cingulate Gyrus）

#### 3️⃣ 皮层下结构（Subcortical ROIs，核心回路）

包含左右双侧：
- 丘脑（Thalamus）
- 尾状核（Caudate）
- 壳核（Putamen）
- 苍白球（Pallidum）
- 伏隔核（Accumbens）

---

### 二、为什么 ADHD 项目要选这些区域？

#### （1）前额叶皮层：执行控制与抑制控制的核心

前额叶皮层是人类高级认知功能的中枢，主要负责：
- 注意力维持
- 行为抑制（抑制不合适的反应）
- 工作记忆与任务管理
- 决策与目标导向行为

ADHD 的核心症状（注意力不集中、冲动、执行功能障碍）  
在神经认知层面，正对应**前额叶功能异常**。

我们选择多个前额叶亚区，是为了覆盖完整的执行控制网络，而不是假设 ADHD 只与某一个单独脑区相关。

---

#### （2）扣带皮层：注意调度与冲突监控

前扣带皮层（ACC）在注意网络中扮演“调度中心”的角色，参与：
- 冲突监控
- 错误检测
- 注意资源的动态分配

ADHD 患者在需要持续注意或抑制反应的任务中，  
常表现出 ACC 功能或结构上的异常。

旁扣带回和后扣带回则与自我监控和默认模式网络（DMN）相关，  
而 ADHD 的一个重要特征正是**任务态下默认模式网络抑制不足**。

---

#### （3）丘脑–纹状体系统：ADHD 的经典核心神经回路

ADHD 最经典、也是被反复验证的神经通路是：

**前额叶 → 纹状体 → 丘脑 → 前额叶（Fronto-striatal–thalamic loop）**

这一回路负责：
- 行为启动与抑制
- 冲动控制
- 奖赏与动机调节

具体来说：
- 尾状核、壳核：行为选择与控制
- 伏隔核：奖赏敏感性（ADHD 常表现为偏好即时奖励）
- 丘脑：信息中继与注意调节

这也是为什么 ADHD 的常用药物主要作用于多巴胺系统，  
而多巴胺系统正是该回路中的关键神经递质通路。

---

### 三、选择这些 ROI 的科研意义

我们选择这组 ROI，并不是为了“让模型更容易学”，  
而是为了回答一个更基础、更科研的问题：

> **如果我们只关注神经科学上最可能与 ADHD 相关的脑区，  
> T1 结构像中是否仍然存在可被模型捕捉的判别信号？**

这一步的意义在于：
- 减少全脑建模带来的噪音
- 提高模型输入的神经生物学可解释性
- 为后续是否进入 3D CNN 或更换模态（如 fMRI）提供依据

---

### 四、与后续步骤的关系

如果在严格 subject-level split 的前提下，  
即使在这些 ADHD 核心 ROI 中、使用更多 slice（例如 20 张），  
模型的表现仍然接近随机，

那么我们就有充分理由认为：
- 问题不在 slice 数量
- 也不完全在模型复杂度
- 而更可能在于 **T1 结构像并不是 ADHD 的主要判别模态**

这将为我们下一步进入 3D CNN 或功能影像分析提供清晰的科研动机。

用这些 ROI 生成 mask → 选 ROI 覆盖最多的 slice（K=20）→ subject-level split + 训练。
"""

# ===============================
# Cell 2 - ROI groups (core vs extended)
# ===============================

# 刚刚 Cell 1 得到的 roi_idx_cort / roi_idx_sub 已经在内存里

# ---- 细分 cortical：PFC vs Cingulate ----
# 我们用 label 名字筛一遍更稳（避免硬编码 index）
def idx_by_name(labels, contains_any):
    out = []
    for i, name in enumerate(labels):
        s = str(name).lower()
        if any(k in s for k in contains_any):
            out.append(i)
    return sorted(set(out))

# cortical groups
idx_pfc = idx_by_name(cort_labels, [
    "frontal", "inferior frontal", "middle frontal", "superior frontal",
    "frontal pole", "frontal medial", "frontal orbital", "frontal opercular"
])
idx_cing = idx_by_name(cort_labels, ["cingulate", "paracingulate"])

# subcortical "core" ADHD (fronto-striatal / thalamus)
idx_sub_core = idx_by_name(sub_labels, ["thalamus", "caudate", "putamen", "accumbens", "pallidum"])

# optional extended (limbic)
idx_sub_limbic = idx_by_name(sub_labels, ["amygdala", "hippocampus"])

# 去掉 background=0
idx_pfc = [i for i in idx_pfc if i != 0]
idx_cing = [i for i in idx_cing if i != 0]
idx_sub_core = [i for i in idx_sub_core if i != 0]
idx_sub_limbic = [i for i in idx_sub_limbic if i != 0]

print("PFC idx:", idx_pfc)
print("Cing idx:", idx_cing)
print("Sub-core idx:", idx_sub_core)
print("Sub-limbic idx:", idx_sub_limbic)

USE_EXTENDED = False  # ✅ 推荐先 False：更“ADHD核心回路”

roi_idx_cort_final = sorted(set(idx_pfc + idx_cing))
roi_idx_sub_final  = sorted(set(idx_sub_core + (idx_sub_limbic if USE_EXTENDED else [])))

print("\nFinal cortical ROIs:")
for i in roi_idx_cort_final:
    print(i, cort_labels[i])

print("\nFinal subcortical ROIs:")
for i in roi_idx_sub_final:
    print(i, sub_labels[i])

# ===============================
# Cell 3 - Make ROI mask in MNI & select top-K axial slices
# ===============================

import numpy as np
import nibabel as nib

TARGET_K = 20
MIN_ROI_PIX = 200  # 这个阈值你可以调：越大 -> 越“真ROI”，但可选层会变少

def make_roi_mask_mni(cort_img, sub_img, roi_idx_cort, roi_idx_sub):
    cort_data = cort_img.get_fdata().astype(np.int32)
    sub_data  = sub_img.get_fdata().astype(np.int32)

    mask = np.zeros_like(cort_data, dtype=np.uint8)

    for v in roi_idx_cort:
        mask |= (cort_data == v)
    for v in roi_idx_sub:
        mask |= (sub_data == v)

    return nib.Nifti1Image(mask.astype(np.uint8), affine=cort_img.affine)

roi_mask_mni = make_roi_mask_mni(cort_img, sub_img, roi_idx_cort_final, roi_idx_sub_final)

def select_topk_z(mask_nii, k=TARGET_K, min_pix=MIN_ROI_PIX, fallback=(0.25, 0.75)):
    m = mask_nii.get_fdata().astype(np.uint8)
    z = m.shape[2]
    counts = m.sum(axis=(0, 1))

    valid = np.where(counts >= min_pix)[0]
    if len(valid) < k:
        # 如果有效层太少：用中间区域补齐
        zmin, zmax = fallback
        extra = np.linspace(z*zmin, z*zmax, k).astype(int)
        extra = np.clip(extra, 0, z-1)
        # 合并去重，再按 counts 排序取前 k
        cand = np.unique(np.concatenate([valid, extra]))
        cand = cand[np.argsort(counts[cand])[::-1]]
        pick = np.sort(cand[:k])
        return pick, counts
    else:
        valid_sorted = valid[np.argsort(counts[valid])[::-1]]
        pick = np.sort(valid_sorted[:k])
        return pick, counts

roi_z_list, z_counts = select_topk_z(roi_mask_mni, k=TARGET_K, min_pix=MIN_ROI_PIX)

print("Selected ROI z indices (K={}):".format(len(roi_z_list)))
print(roi_z_list)
print("ROI pixel counts (min/median/max):",
      int(z_counts[roi_z_list].min()),
      int(np.median(z_counts[roi_z_list])),
      int(z_counts[roi_z_list].max()))

# ===============================
# Cell 3.5 - Visual sanity check: ROI mask slices in MNI
# ===============================

import matplotlib.pyplot as plt

mask = roi_mask_mni.get_fdata().astype(np.uint8)

# 选 6 张代表性的 z
zs_show = np.linspace(0, len(roi_z_list)-1, 6).astype(int)
zs_show = roi_z_list[zs_show]

plt.figure(figsize=(12, 6))
for i, zi in enumerate(zs_show, 1):
    plt.subplot(2, 3, i)
    plt.imshow(mask[:, :, int(zi)].T, origin="lower")
    plt.title(f"ROI mask z={int(zi)}")
    plt.axis("off")
plt.tight_layout()
plt.show()

# ===============================
# REQUIRED - Define register_to_mni (ANTs Affine registration)
# ===============================

import ants
import nibabel as nib
import numpy as np
from nilearn import datasets

# 1) 准备 MNI fixed image（只需一次）
mni_t1 = datasets.load_mni152_template()

def nib_to_ants(img_nii):
    """
    Convert nibabel NIfTI image -> ants image
    """
    data = img_nii.get_fdata().astype(np.float32)
    spacing = img_nii.header.get_zooms()[:3]
    return ants.from_numpy(data, spacing=spacing)

fixed_ants = nib_to_ants(mni_t1)

# 2) 定义 register_to_mni（Affine，课堂版）
def register_to_mni(moving_path, fixed_ants=fixed_ants):
    """
    moving_path: subject T1 NIfTI path
    return:
        warped_ants : subject T1 warped to MNI space (ants image)
        reg         : transform dictionary (for debug / extension)
    """
    moving_nii = nib.load(moving_path)
    moving_ants = nib_to_ants(moving_nii)

    reg = ants.registration(
        fixed=fixed_ants,
        moving=moving_ants,
        type_of_transform="Affine"   # Rigid + Affine，速度可接受
    )

    warped = reg["warpedmovout"]
    return warped, reg

# ===============================
# Speed-up: cache warped MNI volumes
# ===============================

import os
import numpy as np

CACHE_DIR = "/content/mni_cache"
os.makedirs(CACHE_DIR, exist_ok=True)

def cache_path_for_sub(sub_id):
    # 保存 warped volume 的 numpy（float16 节省空间）
    return os.path.join(CACHE_DIR, f"{sub_id}_warped_mni_float16.npy")

def get_warped_mni_cached(sub_id, t1_path):
    p = cache_path_for_sub(sub_id)
    if os.path.exists(p):
        vol = np.load(p)  # (182,218,182) in MNI space
        return vol.astype(np.float32)

    warped_ants, _ = register_to_mni(t1_path)
    vol = warped_ants.numpy().astype(np.float32)
    np.save(p, vol.astype(np.float16))
    return vol

# ===============================
# Cell 4 - Build ROI-guided multi-slice dataset (subject-safe)
# ===============================

from sklearn.model_selection import train_test_split
import numpy as np

# subject-level split
y_sub = df["y"].astype(int).values
idx = np.arange(len(df))
train_sub_idx, test_sub_idx = train_test_split(idx, test_size=0.2, random_state=42, stratify=y_sub)

df_train = df.iloc[train_sub_idx].reset_index(drop=True)
df_test  = df.iloc[test_sub_idx].reset_index(drop=True)

print("Train subjects:", len(df_train), "Test subjects:", len(df_test))

def extract_slices_from_warped(warped_ants, z_indices):
    vol = warped_ants.numpy().astype(np.float32)
    out = []
    for zi in z_indices:
        sl = vol[:, :, int(zi)]
        vmin, vmax = sl.min(), sl.max()
        if vmax > vmin:
            sl = (sl - vmin) / (vmax - vmin)
        else:
            sl = np.zeros_like(sl, dtype=np.float32)
        out.append(sl)
    return out

def build_roi_slice_dataset(df_sub, roi_z_list):
    X_list, y_list, sub_list = [], [], []

    for _, row in df_sub.iterrows():
        vol = get_warped_mni_cached(row["sub_id"], row["t1_path"])  # cached!

        for zi in roi_z_list:
            sl = vol[:, :, int(zi)].astype(np.float32)
            vmin, vmax = sl.min(), sl.max()
            if vmax > vmin:
                sl = (sl - vmin) / (vmax - vmin)
            else:
                sl = np.zeros_like(sl, dtype=np.float32)

            X_list.append(resize_slice(sl))
            y_list.append(int(row["y"]))
            sub_list.append(row["sub_id"])

    X = np.stack(X_list, axis=0)
    y = np.array(y_list, dtype=np.int32)
    sub = np.array(sub_list)
    return X, y, sub


X_train_all, y_train_all, sub_train_all = build_roi_slice_dataset(df_train, roi_z_list)
X_test,      y_test,      sub_test      = build_roi_slice_dataset(df_test,  roi_z_list)

print("X_train_all:", X_train_all.shape, "X_test:", X_test.shape)
print("Train y:", {0: int((y_train_all==0).sum()), 1: int((y_train_all==1).sum())})
print("Test y :", {0: int((y_test==0).sum()),      1: int((y_test==1).sum())})
print("Subject overlap:", len(set(sub_train_all.tolist()) & set(sub_test.tolist())))

"""真正的 ROI 需要把每个人的脑放到同一个标准空间（MNI），
配准是医学影像里最耗时但也最关键的步骤之一。
我们用缓存让它“第一次慢、以后快”，这是科研工程常见做法。
"""

# ===============================
# Cell 5 - Train & evaluate (ROI-guided, subject-safe)
# ===============================

from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import roc_auc_score
import tensorflow as tf
import numpy as np

# subject-level val split
idx2 = np.arange(len(df_train))
train2_idx, val_idx = train_test_split(
    idx2, test_size=0.2, random_state=42, stratify=df_train["y"].astype(int).values
)

df_train2 = df_train.iloc[train2_idx].reset_index(drop=True)
df_val    = df_train.iloc[val_idx].reset_index(drop=True)

X_train, y_train, _ = build_roi_slice_dataset(df_train2, roi_z_list)
X_val,   y_val,   _ = build_roi_slice_dataset(df_val,    roi_z_list)

model = build_small_cnn(target_h=TARGET_H, target_w=TARGET_W, l2=1e-4, lr=1e-3)

classes = np.unique(y_train)
cw = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight = {int(c): float(w) for c, w in zip(classes, cw)}
print("class_weight:", class_weight)

callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_AUC", mode="max", patience=10, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_AUC", mode="max", factor=0.5, patience=4, min_lr=1e-5, verbose=1)
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=80,
    batch_size=8,
    class_weight=class_weight,
    callbacks=callbacks,
    verbose=1
)

# slice-level AUC
y_prob = model.predict(X_test).ravel()
auc_slice = roc_auc_score(y_test, y_prob)
print("\nROI Slice-level Test AUC:", float(auc_slice))

# subject-level aggregation AUC
sub_unique = np.unique(sub_test)
y_true_sub, y_prob_sub = [], []
for sid in sub_unique:
    m = (sub_test == sid)
    y_true_sub.append(int(np.round(y_test[m].mean())))
    y_prob_sub.append(float(y_prob[m].mean()))
auc_sub = roc_auc_score(np.array(y_true_sub), np.array(y_prob_sub))
print("ROI Subject-level Test AUC:", float(auc_sub))
print("N test subjects:", len(sub_unique))

"""# ROI-guided Multi-slice（Subject-level split）——逐 Cell 讲义

---

## Cell 0 — 安装依赖（nilearn + antspyx）

**科研上在做什么？**  
我们为“标准空间对齐 + atlas ROI 定义”准备工具链。  
- `nilearn`：获取 MNI 模板与 Harvard-Oxford atlas（标准脑区图谱）  
- `antspyx`：把每个被试的 T1 配准到 MNI（registration）

**为什么要这样做？**  
如果我们要说“只看 ADHD 相关脑区”，首先必须让不同被试的脑处在**同一个坐标系**，否则“ROI”在每个人身上不一定是同一块解剖区域。

---

## Cell 1 — 载入 MNI 模板 + Harvard-Oxford atlas，并列出 ROI labels

**科研上在做什么？**  
我们把“脑区”从主观猜测变成可复现的定义：  
- MNI152 模板：标准空间的参考脑  
- Harvard-Oxford atlas：标准脑区分割（cortical / subcortical）  
- 通过 label 名称筛选出和 ADHD 更相关的候选区域（PFC、Cingulate、Striatum/Thalamus 等）

**为什么要这样做？**  
这一 cell 的作用是：把“ADHD 相关脑区”变成**可复现的 ROI 集合**。  
后续的 slice 选择将严格基于这些 ROI，而不是基于经验挑某个 z 百分位。

---

## Cell 2 — ROI 细分（PFC vs Cingulate vs Subcortical）并决定核心/扩展 ROI

**科研上在做什么？**  
我们把 ROI 进一步结构化成“可解释的神经回路模块”：  
- PFC（执行控制/抑制控制）  
- ACC / Paracingulate（注意与冲突监控）  
- Striatum/Thalamus（fronto-striatal circuit，奖赏/动机/冲动控制）  
可选：Amygdala/Hippocampus（情绪/记忆相关，但是否纳入要看研究叙事）

**为什么要这样做？**  
ROI 细分可以支持我们做对照实验：  
- “核心 ADHD 回路”是否比“更宽泛的 ROI”更有效？  
这比直接堆更多 slice 或更大模型更像科研。

---

## Cell 3 — 生成 MNI 空间 ROI mask，并选 ROI 覆盖最多的 K=20 个 slices

**科研上在做什么？**  
我们从 atlas 得到一个“ROI 的三维掩膜（mask）”，然后让 slice 选择变成一个可解释的规则：  
- 统计每个 axial z 层中 ROI 的像素数量  
- 选出 ROI 出现最多、最稳定的 K 个层面（例如 20 张）

**为什么要这样做？**  
这一步把“我们看哪些切片”从人为选择变成“ROI 驱动的采样策略”。  
相比均匀采样 z 轴，这种做法更接近“只看 ADHD 相关区域”的科学含义。

---

## Cell 3.5 — 可视化 ROI mask（sanity check）

**科研上在做什么？**  
我们做质量控制（QC）：确认 ROI mask 在我们选的 z 层上确实存在且位置合理。

**为什么要这样做？**  
医学影像 pipeline 最常见的问题不是模型，而是前处理：  
- ROI 是否选错？  
- mask 是否全 0 或全 1？  
- 选到的层是否根本没有 ROI？  
可视化是最便宜也最可靠的 QC。

---

## Cell 4 — Subject-level split 后：对每个被试做配准 → 提取 ROI slices → 构建数据集

**科研上在做什么？**  
这是整个 ROI pipeline 的核心工程步骤：

1) **Subject-level split（train/test）**  
   - 我们先把被试分组，确保 test subjects 完全没见过（防泄露）

2) **Registration（T1 → MNI）**  
   - 每个被试的脑被变换到标准空间，保证 ROI 的解剖意义一致

3) **ROI-guided slice extraction（K=20）**  
   - 在 MNI 空间中只提取我们选定的 ROI 相关层面

4) **形成 CNN 训练数据：X（slice）与 y（label）**  
   - 训练时把每张 slice 当作样本，但仍保留 subject id 以便后续聚合评估

**为什么要这样做？**  
因为“真正的 ROI”不是在每个人原始空间里猜，而是在统一空间里依据 atlas 选取。  
这一 cell 让我们的 ROI 选择具备：  
- 可解释性（我们知道看的是哪块脑）  
- 可复现性（任何人运行同样代码会得到同样 ROI 规则）

---

## Cell 5 — Subject-level validation split + 训练（同一个 CNN）+ slice/subject AUC

**科研上在做什么？**  
我们进行严格评估，避免“validation 泄露”和“只看 slice 指标”：

1) **Train/Val 仍然按 subject 切分**  
   - early stopping 不能看到同一个人的其它 slice（否则会乐观偏差）

2) **保持模型结构不变（同一个 CNN）**  
   - 这样我们比较的不是“模型大小”，而是“数据是否更有信息”

3) **同时报告两种指标：**
   - Slice-level AUC：每张 slice 的排序能力（图像层面）
   - Subject-level AUC：把同一 subject 的 K 张 slice 概率做平均后再算 AUC（临床更真实）

**为什么要这样做？**  
医学任务最终是一人一个结论。  
如果 slice-level AUC 变化不大，但 subject-level AUC 更稳定上升，  
这说明“多 slice + ROI 的信息聚合”确实在帮助模型提取更一致的信号。

---

## 我们通过这一节课想得到什么“科研结论”？

不是“把 AUC 调到很高”，而是回答一个更根本的问题：

- 在严格 subject-level split 下  
- 仅通过 T1 结构像的 2D slices  
- 如果我们聚焦在 ADHD 更相关的 ROI，并使用更多 slices（例如 20 张）  
- 模型的 subject-level AUC 是否出现稳定提升？

如果没有提升，那么我们就有证据支持下一步方向：  
- 进入 3D（保留 3D 结构信息）  
- 或转向更适合 ADHD 的模态（fMRI、DTI、connectivity、多模态）

"""