# -*- coding: utf-8 -*-
"""ADHD_ROI-guided.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVoH0Z3u8h7EMUNtGnbghjNhFXv5O9MM
"""

# ============================================
# ADHD ROI-guided MRI Classification (Colab-ready)
# - Subject-level split (NO leakage)
# - Atlas-guided ROI slice selection (Harvard-Oxford)
# - Rigid registration to MNI152 2mm (ANTsPy) + caching
# - 2D CNN on ROI-selected slices
# - Slice AUC + Subject AUC + Bootstrap CI
# ============================================

# ---------- 0) Mount Drive (if using Drive) ----------
from google.colab import drive
drive.mount('/content/drive')

# ---------- 1) Install deps ----------
!pip -q install nilearn antspyx nibabel scikit-learn tensorflow

# ---------- 2) Imports / seeds ----------
import os, tempfile
import numpy as np
import pandas as pd

import nibabel as nib
import ants
from nilearn import datasets, image

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

import tensorflow as tf
from tensorflow.keras import layers, models

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ---------- 3) Paths (EDIT THIS LINE ONLY) ----------
# Example:
# BASE_DIR = "/content/drive/MyDrive/ADHD200/Peking_1"
BASE_DIR = "/content/drive/MyDrive/ADHD200/Peking_1"

PARTICIPANTS_TSV = os.path.join(BASE_DIR, "participants.tsv")
assert os.path.exists(BASE_DIR), f"BASE_DIR not found: {BASE_DIR}"
assert os.path.exists(PARTICIPANTS_TSV), f"participants.tsv not found: {PARTICIPANTS_TSV}"
print("BASE_DIR OK:", BASE_DIR)

# ---------- 4) Global configs ----------
TARGET_H, TARGET_W = 128, 128
CACHE_DIR = "/content/mni_cache2"
os.makedirs(CACHE_DIR, exist_ok=True)

# You can tune these:
TEST_SIZE = 0.20        # subject-level test split
VAL_SIZE_IN_TRAIN = 0.20  # subject-level val split inside train
K_SLICES = 20           # how many ROI-heavy z-slices to use
MIN_ROI_VOXELS_PER_SLICE = 50  # ignore slices with too few ROI voxels

BATCH_SIZE = 8
EPOCHS = 50
PATIENCE = 8

# ---------- 5) Utils ----------
def resize_slice(sl2d, h=TARGET_H, w=TARGET_W):
    """sl2d: (H,W) float -> (h,w,1) float32"""
    sl = sl2d[..., np.newaxis].astype(np.float32)
    sl = tf.image.resize(sl, [h, w], method="bilinear").numpy().astype(np.float32)
    return sl

def normalize_slice(sl2d, eps=1e-6):
    """simple z-score normalization per slice"""
    m = np.nanmean(sl2d)
    s = np.nanstd(sl2d)
    if not np.isfinite(s) or s < eps:
        return (sl2d - m).astype(np.float32)
    return ((sl2d - m) / (s + eps)).astype(np.float32)

def bootstrap_auc_ci(y_true, y_score, n=2000, seed=0):
    rng = np.random.default_rng(seed)
    y_true = np.asarray(y_true)
    y_score = np.asarray(y_score)
    N = len(y_true)
    aucs = []
    for _ in range(n):
        idx = rng.integers(0, N, N)
        if len(np.unique(y_true[idx])) < 2:
            continue
        aucs.append(roc_auc_score(y_true[idx], y_score[idx]))
    aucs = np.asarray(aucs)
    return float(np.mean(aucs)), float(np.quantile(aucs, 0.025)), float(np.quantile(aucs, 0.975))

# ---------- 6) Load MNI152 2mm template (nilearn) and read as ANTs image ----------
mni_2mm_nii = datasets.load_mni152_template(resolution=2)

with tempfile.NamedTemporaryFile(suffix=".nii.gz", delete=False) as f:
    nib.save(mni_2mm_nii, f.name)
    mni_path = f.name

fixed_ants = ants.image_read(mni_path)
os.remove(mni_path)

print("MNI 2mm shape:", fixed_ants.shape)

# ---------- 7) Fetch Harvard-Oxford atlas (2mm) and build ROI mask in MNI space ----------
ho_cort = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
ho_sub  = datasets.fetch_atlas_harvard_oxford('sub-maxprob-thr25-2mm')

cort_img = ho_cort.maps if isinstance(ho_cort.maps, nib.spatialimages.SpatialImage) else nib.load(ho_cort.maps)
sub_img  = ho_sub.maps  if isinstance(ho_sub.maps,  nib.spatialimages.SpatialImage) else nib.load(ho_sub.maps)

cort_labels = list(ho_cort.labels)
sub_labels  = list(ho_sub.labels)

def idx_by_name(labels, contains_any):
    out = []
    for i, name in enumerate(labels):
        s = str(name).lower()
        if any(k in s for k in contains_any):
            out.append(i)
    return sorted(set(out))

# ADHD-relevant circuits (as in your recap)
idx_pfc  = [i for i in idx_by_name(cort_labels, ["frontal"]) if i != 0]
idx_cing = [i for i in idx_by_name(cort_labels, ["cingulate","paracingulate"]) if i != 0]
idx_sub_core = [i for i in idx_by_name(sub_labels, ["thalamus","caudate","putamen","accumbens","pallidum"]) if i != 0]

roi_idx_cort = sorted(set(idx_pfc + idx_cing))
roi_idx_sub  = sorted(set(idx_sub_core))

cort_data = cort_img.get_fdata().astype(np.int16)
sub_data  = sub_img.get_fdata().astype(np.int16)

mask = np.zeros_like(cort_data, dtype=np.uint8)
for v in roi_idx_cort:
    mask |= (cort_data == v).astype(np.uint8)
for v in roi_idx_sub:
    mask |= (sub_data == v).astype(np.uint8)

# Choose ROI-heavy z-slices (in MNI space)
counts = mask.sum(axis=(0,1))
valid = np.where(counts > MIN_ROI_VOXELS_PER_SLICE)[0]
assert len(valid) > 0, "No valid ROI slices found. Try lowering MIN_ROI_VOXELS_PER_SLICE."

valid_sorted = valid[np.argsort(counts[valid])[::-1]]
roi_z = np.sort(valid_sorted[:K_SLICES])

print("Selected K:", len(roi_z), "z range:", int(roi_z.min()), "-", int(roi_z.max()))

# ---------- 8) Registration with caching: subject T1 -> MNI 2mm (Rigid) ----------
def cache_path(sub_id):
    return os.path.join(CACHE_DIR, f"{sub_id}_mni2mm_float16.npy")

def get_warped_mni2mm(sub_id, t1_path, type_of_transform="Rigid"):
    """
    Returns a numpy volume aligned to MNI 2mm grid (same voxel grid as mni_2mm_nii),
    cached as float16.
    """
    p = cache_path(sub_id)
    if os.path.exists(p):
        return np.load(p).astype(np.float32)

    # load moving
    moving_nii = nib.load(t1_path)

    # speed/stability: resample moving to MNI 2mm grid before ANTs
    moving_2mm = image.resample_to_img(moving_nii, mni_2mm_nii, interpolation="continuous")

    # safest: write temp nifti, read via ants.image_read
    with tempfile.NamedTemporaryFile(suffix=".nii.gz", delete=False) as f:
        nib.save(moving_2mm, f.name)
        moving_ants = ants.image_read(f.name)
    os.remove(f.name)

    reg = ants.registration(
        fixed=fixed_ants,
        moving=moving_ants,
        type_of_transform=type_of_transform
    )

    vol = reg["warpedmovout"].numpy().astype(np.float32)
    np.save(p, vol.astype(np.float16))
    return vol

# ---------- 9) Build subject dataframe df from scratch (QC + labels + T1 paths) ----------
# 9.1 read participants.tsv (robust enc)
df_p = None
for enc in ["utf-8", "latin1", "ISO-8859-1", "cp1252"]:
    try:
        df_p = pd.read_csv(PARTICIPANTS_TSV, sep="\t", encoding=enc)
        print("Read participants.tsv with encoding:", enc)
        break
    except UnicodeDecodeError:
        pass
assert df_p is not None, "Failed to read participants.tsv"

# 9.2 labels
df_p["sub_id"] = df_p["participant_id"].astype(str).apply(lambda x: f"sub-{x}")
dx = df_p["dx"].astype(str)

y = np.full(len(df_p), np.nan, dtype=float)
y[dx.str.contains("Typically Developing", case=False, na=False)] = 0
y[dx.str.contains("ADHD", case=False, na=False)] = 1

df_lab = df_p[["sub_id","dx","gender","age","qc_anatomical_1"]].copy()
df_lab["y"] = y

# 9.3 QC + label exists
df_lab_qc = (
    df_lab[df_lab["qc_anatomical_1"].astype(str).str.lower() == "pass"]
    .dropna(subset=["y"])
    .copy()
)
df_lab_qc["y"] = df_lab_qc["y"].astype(int)

print("After QC+label:", df_lab_qc.shape)
print("Label distribution:", df_lab_qc["y"].value_counts().to_dict())

# 9.4 collect T1 files (BIDS-like)
def collect_t1_files(base_dir, ses_id="ses-1"):
    out = []
    for sub in sorted(os.listdir(base_dir)):
        if not sub.startswith("sub-"):
            continue
        anat_dir = os.path.join(base_dir, sub, ses_id, "anat")
        if not os.path.exists(anat_dir):
            continue
        for fn in os.listdir(anat_dir):
            if fn.endswith("_T1w.nii.gz"):
                out.append({"sub_id": sub, "t1_path": os.path.join(anat_dir, fn)})
    return pd.DataFrame(out)

df_t1 = collect_t1_files(BASE_DIR, ses_id="ses-1")
print("T1 files found:", len(df_t1))

df = (
    df_t1
    .merge(df_lab_qc[["sub_id","y","gender","age"]], on="sub_id", how="inner")
    .sort_values(["sub_id","t1_path"])
    .drop_duplicates("sub_id", keep="first")  # subject-level dedup is CRITICAL
    .reset_index(drop=True)
)

print("Final df shape:", df.shape)
print("Final label distribution:", df["y"].value_counts().to_dict())
assert len(df) > 10, "Too few subjects after merge. Check BASE_DIR site and BIDS structure."

# ---------- 10) Subject-level split (NO leakage) ----------
idx_all = np.arange(len(df))
y_all = df["y"].values

tr_idx, te_idx = train_test_split(
    idx_all,
    test_size=TEST_SIZE,
    random_state=SEED,
    stratify=y_all
)

df_train = df.iloc[tr_idx].reset_index(drop=True)
df_test  = df.iloc[te_idx].reset_index(drop=True)

print("df_train:", df_train.shape, "label:", df_train["y"].value_counts().to_dict())
print("df_test :", df_test.shape,  "label:", df_test["y"].value_counts().to_dict())

# val split inside train (still subject-level)
idx2 = np.arange(len(df_train))
y_tr = df_train["y"].values

tr2, va = train_test_split(
    idx2,
    test_size=VAL_SIZE_IN_TRAIN,
    random_state=SEED,
    stratify=y_tr
)

df_tr2 = df_train.iloc[tr2].reset_index(drop=True)
df_va  = df_train.iloc[va].reset_index(drop=True)

print("df_tr2:", df_tr2.shape, "label:", df_tr2["y"].value_counts().to_dict())
print("df_va :", df_va.shape,  "label:", df_va["y"].value_counts().to_dict())

# ---------- 11) Build ROI-guided slice dataset ----------
def build_roi_dataset(df_sub, roi_z):
    """
    Returns slice-level dataset:
      X: (N_slices, H, W, 1)
      y: (N_slices,)
      sub_ids: (N_slices,)  (for subject aggregation later)
    """
    X_list, y_list, sub_list = [], [], []

    for _, row in df_sub.iterrows():
        sub_id = row["sub_id"]
        t1_path = row["t1_path"]
        label = int(row["y"])

        # registration -> MNI 2mm
        vol = get_warped_mni2mm(sub_id, t1_path, type_of_transform="Rigid")  # (X,Y,Z) in MNI grid

        # extract ROI-selected slices
        for z in roi_z:
            if z < 0 or z >= vol.shape[2]:
                continue
            sl = vol[:, :, z]

            # normalize + resize
            sl = normalize_slice(sl)
            sl = resize_slice(sl, TARGET_H, TARGET_W)

            X_list.append(sl)
            y_list.append(label)
            sub_list.append(sub_id)

    X = np.stack(X_list, axis=0).astype(np.float32)
    y = np.array(y_list, dtype=np.int32)
    sub_ids = np.array(sub_list)
    return X, y, sub_ids

print("Building datasets (this can take time due to registration; cached after first run)...")

X_train, y_train, sub_train = build_roi_dataset(df_tr2, roi_z)
X_val,   y_val,   sub_val   = build_roi_dataset(df_va,  roi_z)
X_test,  y_test,  sub_test  = build_roi_dataset(df_test, roi_z)

print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_val  :", X_val.shape,   "y_val  :", y_val.shape)
print("X_test :", X_test.shape,  "y_test :", y_test.shape)

# ---------- 12) Small 2D CNN baseline ----------
def build_small_cnn():
    inp = layers.Input(shape=(TARGET_H, TARGET_W, 1))
    x = layers.Conv2D(8, 3, activation="relu", padding="same")(inp)
    x = layers.MaxPooling2D(2)(x)
    x = layers.Conv2D(16, 3, activation="relu", padding="same")(x)
    x = layers.MaxPooling2D(2)(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(16, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    out = layers.Dense(1, activation="sigmoid")(x)

    m = models.Model(inp, out)
    m.compile(
        optimizer="adam",
        loss="binary_crossentropy",
        metrics=[tf.keras.metrics.AUC(name="AUC")]
    )
    return m

model = build_small_cnn()
model.summary()

cb = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_AUC",
        mode="max",
        patience=PATIENCE,
        restore_best_weights=True
    )
]

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=cb,
    verbose=1
)

# ---------- 13) Evaluation: slice-level AUC ----------
y_prob = model.predict(X_test, batch_size=BATCH_SIZE).ravel()
auc_slice = roc_auc_score(y_test, y_prob)
print("\nROI-guided slice AUC:", float(auc_slice))

# ---------- 14) Evaluation: subject-level AUC (mean aggregation) ----------
subs = np.unique(sub_test)
y_true_s, y_prob_s = [], []
for sid in subs:
    msk = (sub_test == sid)
    # true label is constant per subject (all slices same y)
    y_true_s.append(int(np.round(y_test[msk].mean())))
    y_prob_s.append(float(y_prob[msk].mean()))

auc_sub = roc_auc_score(y_true_s, y_prob_s)
print("ROI-guided subject AUC:", float(auc_sub), "N subjects:", len(subs))

# ---------- 15) Bootstrap CI on subject AUC ----------
mean_auc, lo, hi = bootstrap_auc_ci(y_true_s, y_prob_s, n=2000, seed=SEED)
print(f"Subject AUC bootstrap: mean={mean_auc:.3f}, 95% CI=({lo:.3f}, {hi:.3f})")

"""'''
【结果解读：为什么 Peking_1 的 AUC 这么低？】

我们这次在 Peking_1 上：
- slice-level AUC ≈ 0.39
- subject-level AUC ≈ 0.35（N=26 个测试被试）

诊断：

(1) AUC < 0.5 可能表示“方向反了”
AUC 的定义是：正类(ADHD=1)的预测分数应该更高。
如果模型把 TD 当成 ADHD 学（或者标签方向反了），AUC 会 < 0.5。
此时把预测概率取反 p -> (1-p)，AUC 会变成 1-AUC。
比如 0.35 的 AUC 取反就是 0.65，这反而提示：模型可能学到了一些信号，但方向相反。

(2) 数据规模太小导致不稳定
Peking_1 最终只有 130 个 subjects，其中测试集 26 个（ADHD=9）。
subject-level AUC 在这种样本量下方差非常大，所以 bootstrap CI 会很宽。

结论：
验证 pipeline 能跑通；
下一步我们需要“更多 subjects + 更强的跨站点统一”，才能评估是否有稳健信号。
'''

'''
【为什么只用 Peking_1 不够？为什么要加别的 site？】

ADHD 的结构 MRI 信号本身是弱效应（weak effect）：
- 单个 site 的样本量通常不够大
- 训练会高度不稳定，结果对 split 很敏感（我们这次 test 只有 26 人）

加入更多 subjects / 多个 sites 的目的有两层：

(1) 统计功效（power）
样本越多，模型越不容易因为随机划分而波动；
bootstrap CI 也会明显变窄。

(2) 泛化能力（generalization）
如果模型只在某一个 site 有效，
很可能学到的是“扫描仪/协议/人群差异”而不是 ADHD 本身。
multi-site 的目标是：
让模型在跨站点条件下仍然可用，才接近真实世界。
'''
"""

print(df.columns)
print(df.head(3))

print("\nOverall label dist:", df["y"].value_counts().to_dict())
print("\nTrain label dist:", df_train["y"].value_counts().to_dict())
print("\nVal label dist:", df_va["y"].value_counts().to_dict())
print("\nTest label dist:", df_test["y"].value_counts().to_dict())

import os

ROOT = "/content/drive/MyDrive/ADHD200-data"
os.makedirs(ROOT, exist_ok=True)

print("Data root:", ROOT)

urls_txt = os.path.join(ROOT, "adhd200_urls.txt")
with open(urls_txt, "w") as f:
    f.write(
"""https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Peking_1/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Peking_2/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Peking_3/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/KKI/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/NYU/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Brown/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Pittsburgh/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/OHSU/
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/WashU/

https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/KKI_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/NYU_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Brown_TestRelease_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Pittsburgh_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/NeuroIMAGE_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/OHSU_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/OHSU_TestRelease_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Peking_1_phenotypic.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ADHD200/RawDataBIDS/Peking_1_TestRelease_phenotypic.csv
"""
    )

print("URL list written to:", urls_txt)

!sudo apt-get update -y
!sudo apt-get install -y aria2

!pip -q install awscli
!aws --version
import os
ROOT="/content/drive/MyDrive/ADHD200-data"
os.makedirs(ROOT, exist_ok=True)
print(ROOT)
!aws s3 sync s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/ \
  /content/drive/MyDrive/ADHD200-data/RawDataBIDS \
  --no-sign-request

!ls -lh /content/drive/MyDrive/ADHD200-data | head

!find /content/drive/MyDrive/ADHD200-data -name "*T1w.nii.gz" | head

# 看看每个 site 里有多少 T1
import glob, os

ROOT = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"

sites = sorted([d for d in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, d))])
print("Sites:", sites)

for s in sites:
    n_t1 = len(glob.glob(os.path.join(ROOT, s, "sub-*", "**", "*T1w.nii.gz"), recursive=True))
    print(f"{s:12s}  T1 count:", n_t1)

import os
DATA_ROOT  = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"
for s in ["Peking_2","Peking_3","WashU"]:
    p = os.path.join(DATA_ROOT, s, "participants.tsv")
    print(s, "participants.tsv exists?" , os.path.exists(p), "path:", p)

import os
import pandas as pd

PHENO_ROOT = "/content/drive/MyDrive/ADHD200-data"

print("=== Phenotypic CSV files in root ===\n")

for fn in sorted(os.listdir(PHENO_ROOT)):
    if "phenotypic" in fn and fn.endswith(".csv"):
        path = os.path.join(PHENO_ROOT, fn)
        try:
            df = pd.read_csv(path)
        except UnicodeDecodeError:
            df = pd.read_csv(path, encoding="latin1")

        print(f"\n--- {fn} ---")
        print(list(df.columns))

import os
import pandas as pd

DATA_ROOT = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"

print("=== participants.tsv columns by site ===\n")

sites = sorted([d for d in os.listdir(DATA_ROOT) if os.path.isdir(os.path.join(DATA_ROOT, d))])

for site in sites:
    p = os.path.join(DATA_ROOT, site, "participants.tsv")
    if not os.path.exists(p):
        print(f"\n--- {site} ---")
        print("NO participants.tsv")
        continue

    try:
        df = pd.read_csv(p, sep="\t")
    except UnicodeDecodeError:
        df = pd.read_csv(p, sep="\t", encoding="latin1")

    print(f"\n--- {site} ---")
    print(list(df.columns))

import pandas as pd

rows = []

# phenotypic csv
for fn in sorted(os.listdir(PHENO_ROOT)):
    if "phenotypic" in fn and fn.endswith(".csv"):
        path = os.path.join(PHENO_ROOT, fn)
        try:
            df = pd.read_csv(path)
        except UnicodeDecodeError:
            df = pd.read_csv(path, encoding="latin1")

        for c in df.columns:
            rows.append({
                "source": fn,
                "type": "phenotypic_csv",
                "column": c
            })

# participants.tsv
for site in sites:
    p = os.path.join(DATA_ROOT, site, "participants.tsv")
    if not os.path.exists(p):
        continue
    try:
        df = pd.read_csv(p, sep="\t")
    except UnicodeDecodeError:
        df = pd.read_csv(p, sep="\t", encoding="latin1")

    for c in df.columns:
        rows.append({
            "source": f"{site}/participants.tsv",
            "type": "participants_tsv",
            "column": c
        })

col_df = pd.DataFrame(rows)
out = "/content/drive/MyDrive/ADHD200-data/column_summary.csv"
col_df.to_csv(out, index=False)

print("Saved column summary to:", out)
col_df.head()

import os, pandas as pd

DATA_ROOT = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"

def read_tsv_safe(path):
    for enc in [None, "utf-8", "utf-8-sig", "latin1", "cp1252"]:
        try:
            return pd.read_csv(path, sep="\t", encoding=enc) if enc else pd.read_csv(path, sep="\t")
        except UnicodeDecodeError:
            continue
    return pd.read_csv(path, sep="\t", encoding="latin1", errors="replace")

for site in ["OHSU", "Pittsburgh", "WashU", "Brown"]:
    p = os.path.join(DATA_ROOT, site, "participants.tsv")
    df = read_tsv_safe(p)
    print("\n===", site, "===")
    # 找所有可能的 anatomical QC 列
    qc_cols = [c for c in df.columns if "qc" in c.lower() and ("anat" in c.lower() or "anatomical" in c.lower())]
    print("QC columns:", qc_cols)
    for c in qc_cols:
        vc = df[c].astype(str).str.lower().value_counts().head(10)
        print(f"\n{c} top values:\n{vc}")

import os, glob, re
import pandas as pd
import numpy as np

DATA_ROOT  = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"
PHENO_ROOT = "/content/drive/MyDrive/ADHD200-data"

def read_csv_safe(path, sep=","):
    for enc in [None, "utf-8", "utf-8-sig", "latin1", "cp1252"]:
        try:
            return pd.read_csv(path, sep=sep, encoding=enc) if enc else pd.read_csv(path, sep=sep)
        except UnicodeDecodeError:
            continue
    return pd.read_csv(path, sep=sep, encoding="latin1", errors="replace")

def read_tsv_safe(path):
    for enc in [None, "utf-8", "utf-8-sig", "latin1", "cp1252"]:
        try:
            return pd.read_csv(path, sep="\t", encoding=enc) if enc else pd.read_csv(path, sep="\t")
        except UnicodeDecodeError:
            continue
    return pd.read_csv(path, sep="\t", encoding="latin1", errors="replace")

def pick_col(df, candidates):
    m = {c.lower(): c for c in df.columns}
    for k in candidates:
        if k.lower() in m:
            return m[k.lower()]
    return None

def norm_sub(x):
    if pd.isna(x): return None
    s = str(x).strip()
    if s.startswith("sub-"): s = s[4:]
    m = re.search(r"(\d+)", s)
    if m:
        d = m.group(1).lstrip("0") or "0"
        return f"sub-{d}"
    return f"sub-{s}"

sites = sorted([d for d in os.listdir(DATA_ROOT) if os.path.isdir(os.path.join(DATA_ROOT, d))])

for site in sites:
    # site participants
    p_tsv = os.path.join(DATA_ROOT, site, "participants.tsv")
    if not os.path.exists(p_tsv):
        print(f"\n{site}: no participants.tsv -> skip")
        continue
    pt = read_tsv_safe(p_tsv)
    pid = pick_col(pt, ["participant_id"])
    pdx = pick_col(pt, ["dx"])
    if pid is None or pdx is None:
        print(f"\n{site}: participants.tsv missing id/dx -> skip")
        continue
    pt2 = pd.DataFrame({
        "sub_id": pt[pid].apply(norm_sub),
        "dx_site": pt[pdx]
    })

    # root phenotypic
    cand = sorted(glob.glob(os.path.join(PHENO_ROOT, f"{site}*phenotypic*.csv")))
    if len(cand) == 0:
        print(f"\n{site}: no root phenotypic -> compare skipped (only site metadata exists)")
        continue
    ph = read_csv_safe(cand[0])
    hid = pick_col(ph, ["ScanDir ID","ID","Subject"])
    hdx = pick_col(ph, ["DX"])
    if hid is None or hdx is None:
        print(f"\n{site}: root phenotypic missing id/DX -> compare skipped")
        continue
    ph2 = pd.DataFrame({
        "sub_id": ph[hid].apply(norm_sub),
        "DX_root": ph[hdx]
    })

    # merge and report
    m = pt2.merge(ph2, on="sub_id", how="inner")
    n_site = pt2["sub_id"].nunique()
    n_root = ph2["sub_id"].nunique()
    n_join = m["sub_id"].nunique()

    # compare values as strings to avoid float/int mismatch
    a = m["dx_site"].astype(str).str.strip()
    b = m["DX_root"].astype(str).str.strip()
    agree = (a == b)
    agree_rate = agree.mean() if len(m) else np.nan

    print(f"\n=== {site} ===")
    print("site subjects:", n_site, "root subjects:", n_root, "overlap:", n_join)
    if len(m):
        print("dx agree rate:", round(float(agree_rate), 4))
        # show some disagreements
        bad = m.loc[~agree, ["sub_id","dx_site","DX_root"]].head(10)
        if len(bad):
            print("examples of disagreement:")
            print(bad.to_string(index=False))
    else:
        print("No overlap matched (ID format mismatch likely).")

import os, glob, re
import pandas as pd
import numpy as np

DATA_ROOT  = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"
OUT_PATH   = "/content/drive/MyDrive/ADHD200-data/manifest_all_sitefirst_strictpass_noBrown.csv"

# ----------------------------
# safe reader
# ----------------------------
def read_tsv_safe(path):
    for enc in [None, "utf-8", "utf-8-sig", "latin1", "cp1252"]:
        try:
            return pd.read_csv(path, sep="\t", encoding=enc) if enc else pd.read_csv(path, sep="\t")
        except UnicodeDecodeError:
            continue
    return pd.read_csv(path, sep="\t", encoding="latin1", errors="replace")

def pick_col(df, candidates):
    m = {c.lower(): c for c in df.columns}
    for k in candidates:
        if k.lower() in m:
            return m[k.lower()]
    return None

def norm_sub(x):
    """
    Normalize subject IDs to match BIDS folder names like sub-12345.
    Keeps only the main digit run; strips leading zeros.
    """
    if pd.isna(x):
        return None
    s = str(x).strip()
    if s.startswith("sub-"):
        s = s[4:]
    m = re.search(r"(\d+)", s)
    if m:
        d = m.group(1).lstrip("0") or "0"
        return f"sub-{d}"
    return f"sub-{s}"

# ----------------------------
# dx -> y (site-first)
# ----------------------------
def dx_text_to_y(dx_series):
    """
    Convert site participants.tsv 'dx' text to binary:
      TD -> 0
      ADHD-* -> 1
    Handles numeric-like too.
    """
    if dx_series is None:
        return None

    s = dx_series

    # numeric-like
    if pd.api.types.is_numeric_dtype(s):
        y = np.full(len(s), np.nan, dtype=float)
        y[pd.Series(s).isin([0])] = 0
        y[pd.Series(s).isin([1,2,3])] = 1
        return y

    ss = s.astype(str).str.strip().str.lower()

    y = np.full(len(ss), np.nan, dtype=float)

    # common ADHD200 participants.tsv wording
    y[ss.str.contains("typically developing")] = 0
    y[ss.str.contains("control")] = 0
    y[ss.str.fullmatch("td")] = 0

    y[ss.str.contains("adhd")] = 1

    # handle explicit numeric strings if present
    y[ss.isin(["0"])] = 0
    y[ss.isin(["1","2","3"])] = 1

    return y

# ----------------------------
# STRICT QC: keep only pass / 1
# ----------------------------
def qc_strict_pass(x):
    if pd.isna(x):
        return False
    s = str(x).strip().lower()
    if s == "pass":
        return True
    if s in ["1", "1.0", "true", "t", "yes", "y"]:
        return True
    return False

# ----------------------------
# T1 index
# ----------------------------
def build_t1_index():
    sites = sorted([d for d in os.listdir(DATA_ROOT) if os.path.isdir(os.path.join(DATA_ROOT, d))])
    sites = [s for s in sites if s != "Brown"]  # exclude Brown

    rows = []
    for site in sites:
        t1s = glob.glob(os.path.join(DATA_ROOT, site, "sub-*", "**", "*T1w.nii.gz"), recursive=True)
        for t1 in t1s:
            sub = [p for p in t1.split("/") if p.startswith("sub-")][0]
            rows.append({"site": site, "sub_id": norm_sub(sub), "t1_path": t1})
    return pd.DataFrame(rows).drop_duplicates(["site","sub_id"])

df_t1 = build_t1_index()
sites = sorted(df_t1["site"].unique())
print("Sites (no Brown):", sites)
print("Unique T1 subjects:", len(df_t1))

# ----------------------------
# Build manifest site-by-site (participants.tsv only)
# ----------------------------
all_parts = []

for site in sites:
    p = os.path.join(DATA_ROOT, site, "participants.tsv")
    if not os.path.exists(p):
        print(f"[WARN] {site}: no participants.tsv -> skip")
        continue

    pt = read_tsv_safe(p)

    id_col = pick_col(pt, ["participant_id"])
    dx_col = pick_col(pt, ["dx"])
    age_col = pick_col(pt, ["age"])
    sex_col = pick_col(pt, ["gender", "sex"])

    # anatomical QC columns
    qc1 = pick_col(pt, ["qc_anatomical_1"])
    qc_s1 = pick_col(pt, ["qc_s1_anat"])  # WashU
    qc_s2 = pick_col(pt, ["qc_s2_anat"])  # WashU

    if id_col is None or dx_col is None:
        print(f"[WARN] {site}: participants.tsv missing participant_id/dx -> skip")
        continue

    meta = pd.DataFrame()
    meta["sub_id"] = pt[id_col].apply(norm_sub)
    meta["dx_raw"] = pt[dx_col]
    meta["age"] = pt[age_col] if age_col else np.nan
    meta["sex"] = pt[sex_col] if sex_col else np.nan

    # choose a single QC column for strict filtering:
    # - prefer qc_anatomical_1
    # - else use qc_s1_anat (WashU primary)
    if qc1:
        meta["qc_anat"] = pt[qc1]
    elif qc_s1:
        meta["qc_anat"] = pt[qc_s1]
    else:
        meta["qc_anat"] = np.nan

    # IMPORTANT: do NOT hard-filter on qc_s2_anat (most are nan in WashU)
    meta["qc_anat_s2"] = pt[qc_s2] if qc_s2 else np.nan

    # label
    meta["y"] = dx_text_to_y(meta["dx_raw"])
    meta = meta.dropna(subset=["y"]).copy()
    meta["y"] = meta["y"].astype(int)

    # merge to T1 list (only subjects with T1)
    m = df_t1[df_t1["site"] == site].merge(meta, on="sub_id", how="inner")

    # STRICT QC pass on qc_anat (pass/1 only)
    m = m[m["qc_anat"].apply(qc_strict_pass)].copy()

    # sanity
    if len(m) == 0 or m["y"].nunique() < 2:
        print(f"[WARN] {site}: after strict QC, insufficient labels. N={len(m)}")
        continue

    # final columns
    out = m[["sub_id","site","t1_path","y","sex","age"]].copy()

    all_parts.append(out)
    print(f"{site:12s} N={len(out)} y-dist={out['y'].value_counts().to_dict()}")

manifest = pd.concat(all_parts, ignore_index=True) if len(all_parts) else pd.DataFrame()

print("\nFinal manifest rows:", len(manifest))
if len(manifest):
    print(manifest.groupby("site")["y"].value_counts())

manifest.to_csv(OUT_PATH, index=False)
print("\nSaved manifest:", OUT_PATH)

"""'''
【多站点数据统一，我们做了哪三件事？】

1) 空间统一（Spatial normalization）
把每个被试的 T1 都配准到 MNI152 2mm，
这样同一个 voxel / slice 在不同 site 之间具有相同解剖意义。

2) 语义统一（ROI definition）
用 Harvard-Oxford atlas 在 MNI 空间定义 ROI，
只在假设相关的脑区上采样 slices，减少全脑噪声与站点差异带来的干扰。

3) 强度统一（Intensity normalization）
结构 MRI 强度没有统一物理量纲，不同 site 强度范围差异很大。
我们对每个 slice 做标准化（z-score + clip），
让模型更难“靠强度范围猜 site”，更聚焦于结构差异。
'''

"""

# ============================================
# ROI-guided ADHD classification on NEW manifest (900+ subjects)
# - Subject-level 5-fold CV (stable AUC)
# - Harvard-Oxford atlas ROI mask
# - Rigid registration to MNI152 2mm (ANTsPy) + caching
# - 2D CNN on ROI-selected slices
# - Subject AUC + Bootstrap CI
# ============================================

# ---------- 0) Mount Drive ----------
from google.colab import drive
drive.mount('/content/drive')

# ---------- 1) Install deps (run once) ----------
!pip -q install nilearn antspyx nibabel scikit-learn tensorflow

# ---------- 2) Imports / seeds ----------
import os, hashlib
import numpy as np
import pandas as pd

import nibabel as nib
import ants
from nilearn import datasets, image

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

import tensorflow as tf
from tensorflow.keras import layers, models

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ---------- 3) EDIT paths ----------
MANIFEST_PATH = "/content/drive/MyDrive/ADHD200-data/manifest_all_sitefirst_strictpass_noBrown.csv"
CACHE_DIR     = "/content/drive/MyDrive/ADHD200-cache/mni2mm_rigid"   # cached warped T1s
os.makedirs(CACHE_DIR, exist_ok=True)

assert os.path.exists(MANIFEST_PATH), f"Manifest not found: {MANIFEST_PATH}"

# ---------- 4) Hyperparams ----------
IMG_SIZE = 128          # 2D slice resize
BATCH    = 32
EPOCHS   = 12
PATIENCE = 2
LR       = 1e-3

# ROI-guided slice sampling:
MIN_ROI_VOXELS_PER_SLICE = 200     # slice must have at least this many ROI voxels to be used
MAX_SLICES_PER_SUBJECT   = 16      # sample at most this many z-slices per subject
USE_EVENLY_SPACED_SLICES = True    # if True: evenly sample across ROI z-slices

# ---------- 5) Utilities ----------
def resize_slice(x2d, out=IMG_SIZE):
    # x2d: (H,W) float
    x = tf.convert_to_tensor(x2d[..., None], dtype=tf.float32)  # (H,W,1)
    x = tf.image.resize(x, (out, out), method="bilinear")
    return x.numpy()[..., 0]

def normalize_slice(x2d):
    # robust normalization per slice
    x = x2d.astype(np.float32)
    m = np.nanmean(x)
    s = np.nanstd(x)
    if not np.isfinite(s) or s < 1e-6:
        return np.zeros_like(x, dtype=np.float32)
    x = (x - m) / s
    x = np.clip(x, -5, 5)
    return x.astype(np.float32)

def bootstrap_auc_ci(y_true, y_score, n_boot=2000, seed=42):
    rng = np.random.default_rng(seed)
    y_true = np.asarray(y_true)
    y_score = np.asarray(y_score)
    n = len(y_true)
    aucs = []
    for _ in range(n_boot):
        idx = rng.integers(0, n, size=n)
        if len(np.unique(y_true[idx])) < 2:
            continue
        aucs.append(roc_auc_score(y_true[idx], y_score[idx]))
    if len(aucs) == 0:
        return float("nan"), (float("nan"), float("nan"))
    aucs = np.array(aucs)
    return float(np.mean(aucs)), (float(np.percentile(aucs, 2.5)), float(np.percentile(aucs, 97.5)))

def cache_path(t1_path):
    h = hashlib.md5(t1_path.encode("utf-8")).hexdigest()
    return os.path.join(CACHE_DIR, f"{h}_mni2mm_rigid.nii.gz")

def as_nii(maps_obj):
    """
    nilearn fetchers sometimes return:
      - a filepath (str)   OR
      - a nibabel image (Nifti1Image)
    This wrapper makes it safe across versions.
    """
    if isinstance(maps_obj, nib.spatialimages.SpatialImage):
        return maps_obj
    return nib.load(maps_obj)

def nii_to_ants(nii_img):
    """
    Convert nibabel NIfTI -> ANTs image preserving spacing+origin+direction.
    Make sure origin/spacing/direction are Python lists (ANTsPy requirement).
    """
    data = nii_img.get_fdata().astype(np.float32)
    aff  = np.array(nii_img.affine, dtype=np.float64)

    # spacing (x,y,z)
    spacing = list(map(float, nii_img.header.get_zooms()[:3]))

    # origin must be list/tuple of length 3
    origin = list(map(float, aff[:3, 3].tolist()))

    # direction must be 3x3 (list of lists)
    direction = (aff[:3, :3] / np.array(spacing)[None, :]).astype(np.float64)
    direction = direction.tolist()

    return ants.from_numpy(
        data,
        spacing=spacing,
        origin=origin,
        direction=direction
    )


# ---------- 6) Load manifest ----------
df = pd.read_csv(MANIFEST_PATH).copy()
df["y"] = df["y"].astype(int)
df = df.dropna(subset=["t1_path", "y"]).reset_index(drop=True)

print("Manifest subjects:", len(df))
print(df.groupby("site")["y"].value_counts())

# ---------- 7) Fetch MNI 2mm + Harvard-Oxford atlas (in MNI space) ----------
mni_2mm = datasets.load_mni152_template(resolution=2)  # nibabel image

ho_cort = datasets.fetch_atlas_harvard_oxford("cort-maxprob-thr25-2mm")
ho_sub  = datasets.fetch_atlas_harvard_oxford("sub-maxprob-thr25-2mm")

# ✅ FIX: ho_*.maps may already be a Nifti1Image; don't nib.load() blindly
cort_img = as_nii(ho_cort.maps)
sub_img  = as_nii(ho_sub.maps)

cort = cort_img.get_fdata().astype(int)
subc = sub_img.get_fdata().astype(int)

cort_labels = list(ho_cort.labels)  # index aligned with integer values
sub_labels  = list(ho_sub.labels)

# ---------- 8) Define ROIs ----------
CORT_ROI_NAMES = [
    "Frontal Pole",
    "Superior Frontal Gyrus",
    "Middle Frontal Gyrus",
    "Inferior Frontal Gyrus, pars triangularis",
    "Inferior Frontal Gyrus, pars opercularis",
    "Frontal Medial Cortex",
    "Frontal Orbital Cortex",
    "Paracingulate Gyrus",
    "Cingulate Gyrus, anterior division",
    "Cingulate Gyrus, posterior division",
]
SUB_ROI_NAMES = [
    "Thalamus",
    "Caudate",
    "Putamen",
    "Pallidum",
    "Accumbens",
]

def idx_by_name(labels, name_contains):
    out = []
    key = name_contains.lower()
    for i, lab in enumerate(labels):
        if isinstance(lab, bytes):
            lab = lab.decode("utf-8", errors="ignore")
        if key in str(lab).lower():
            out.append(i)
    return out

cort_ids = []
for nm in CORT_ROI_NAMES:
    cort_ids += idx_by_name(cort_labels, nm)
cort_ids = sorted(set([i for i in cort_ids if i != 0]))

sub_ids = []
for nm in SUB_ROI_NAMES:
    sub_ids += idx_by_name(sub_labels, nm)
sub_ids = sorted(set([i for i in sub_ids if i != 0]))

roi_mask = np.zeros_like(cort, dtype=bool)
for rid in cort_ids:
    roi_mask |= (cort == rid)
for rid in sub_ids:
    roi_mask |= (subc == rid)

print("Selected cortical ROI label indices:", cort_ids)
print("Selected subcortical ROI label indices:", sub_ids)
print("ROI voxels:", int(roi_mask.sum()))

roi_counts_by_z = roi_mask.sum(axis=(0,1))
roi_z_all = np.where(roi_counts_by_z >= MIN_ROI_VOXELS_PER_SLICE)[0].tolist()
print("Eligible ROI z-slices:", len(roi_z_all),
      "| z min/max:", (min(roi_z_all) if roi_z_all else None, max(roi_z_all) if roi_z_all else None))
assert len(roi_z_all) > 0, "No ROI slices found. Lower MIN_ROI_VOXELS_PER_SLICE or check atlas."

def pick_z_slices(roi_z_list, k=MAX_SLICES_PER_SUBJECT):
    if len(roi_z_list) <= k:
        return roi_z_list
    if USE_EVENLY_SPACED_SLICES:
        idx = np.linspace(0, len(roi_z_list)-1, k).round().astype(int)
        return [roi_z_list[i] for i in idx]
    else:
        rng = np.random.default_rng(SEED)
        return sorted(rng.choice(roi_z_list, size=k, replace=False).tolist())

roi_z = pick_z_slices(roi_z_all, MAX_SLICES_PER_SUBJECT)
print("Using z-slices:", roi_z)

# ---------- 9) Registration to MNI2mm (Rigid) with caching ----------
# NOTE: We register moving subject T1 -> fixed MNI2mm.
# We then write the warped image to disk for re-use.
def get_warped_mni2mm(sub_id, t1_path):
    out = cache_path(t1_path)
    if os.path.exists(out):
        return out

    # fixed (MNI) as nibabel image
    fixed_nii = image.load_img(mni_2mm)  # nibabel-ish
    fixed_nii = fixed_nii if isinstance(fixed_nii, nib.spatialimages.SpatialImage) else nib.load(fixed_nii)

    # moving (subject)
    mov_nii = nib.load(t1_path)

    # convert to ANTs with geometry preserved
    fixed  = nii_to_ants(fixed_nii)
    moving = nii_to_ants(mov_nii)

    reg = ants.registration(fixed=fixed, moving=moving, type_of_transform="Rigid")
    warped = reg["warpedmovout"]

    ants.image_write(warped, out)
    return out

# ---------- 10) Build ROI-guided slice dataset (subject-level) ----------
def build_roi_dataset(df_sub):
    """
    Returns:
      X: (n_slices, H, W, 1)
      y: (n_slices,)
      sub: (n_slices,) subject ids for aggregation
    """
    X_list, y_list, sub_list = [], [], []
    for _, row in df_sub.iterrows():
        sub_id = row["sub_id"]
        t1_path = row["t1_path"]
        y = int(row["y"])

        warped_path = get_warped_mni2mm(sub_id, t1_path)
        vol = nib.load(warped_path).get_fdata().astype(np.float32)  # (X,Y,Z)

        for z in roi_z:
            sl = vol[:, :, z]
            sl = normalize_slice(sl)
            sl = resize_slice(sl, IMG_SIZE)
            X_list.append(sl[..., None])  # (H,W,1)
            y_list.append(y)
            sub_list.append(sub_id)

    return np.stack(X_list), np.array(y_list), np.array(sub_list)

# ---------- 11) Small 2D CNN ----------
def build_small_cnn(input_shape=(IMG_SIZE, IMG_SIZE, 1), lr=LR):
    inp = layers.Input(shape=input_shape)
    x = layers.Conv2D(16, 3, padding="same", activation="relu")(inp)
    x = layers.MaxPool2D()(x)
    x = layers.Conv2D(32, 3, padding="same", activation="relu")(x)
    x = layers.MaxPool2D()(x)
    x = layers.Conv2D(64, 3, padding="same", activation="relu")(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.2)(x)
    out = layers.Dense(1, activation="sigmoid")(x)

    m = models.Model(inp, out)
    m.compile(optimizer=tf.keras.optimizers.Adam(lr),
              loss="binary_crossentropy")
    return m

# ---------- 12) 5-fold subject-level CV ----------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

y_sub = df["y"].values
oof_subject_prob = np.zeros(len(df), dtype=float)
fold_stats = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(np.arange(len(df)), y_sub), 1):
    df_tr = df.iloc[tr_idx].reset_index(drop=True)
    df_te = df.iloc[te_idx].reset_index(drop=True)

    print(f"\n===== Fold {fold} =====")
    print("Train subjects:", len(df_tr), "Test subjects:", len(df_te),
          "Train y-dist:", df_tr["y"].value_counts().to_dict(),
          "Test y-dist:", df_te["y"].value_counts().to_dict())

    # Build slice datasets
    X_tr, y_tr, sub_tr = build_roi_dataset(df_tr)
    X_te, y_te, sub_te = build_roi_dataset(df_te)

    print("Train slices:", len(y_tr), "Test slices:", len(y_te))

    # Train CNN
    model = build_small_cnn()
    cb = tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True)

    model.fit(
        X_tr, y_tr,
        validation_split=0.1,
        epochs=EPOCHS,
        batch_size=BATCH,
        callbacks=[cb],
        verbose=1
    )

    # Predict slice probs on test fold
    p_te = model.predict(X_te, batch_size=BATCH, verbose=0).reshape(-1)

    # Aggregate to subject probs (mean of slice probs)
    df_pred = pd.DataFrame({"sub_id": sub_te, "y": y_te, "p": p_te})
    subj = df_pred.groupby("sub_id").agg(y=("y","first"), p=("p","mean")).reset_index()

    auc_fold = roc_auc_score(subj["y"].values, subj["p"].values)
    print(f"Fold {fold} subject-level AUC: {auc_fold:.4f}")

        # ===== SAVE subject-level predictions (for error analysis) =====
    save_path = f"/content/drive/MyDrive/ADHD200-data/preds_subject_fold{fold}.csv"
    subj.to_csv(save_path, index=False)
    print("Saved subject-level preds to:", save_path)


    # Write fold subject probs back into OOF vector
    prob_map = dict(zip(subj["sub_id"].values, subj["p"].values))
    for i, r in df.iloc[te_idx].iterrows():
        oof_subject_prob[i] = prob_map[r["sub_id"]]

    fold_stats.append({
        "fold": fold,
        "auc_subject": float(auc_fold),
        "n_test_subjects": int(len(subj)),
        "n_test_slices": int(len(y_te))
    })

# Overall OOF AUC
auc_oof = roc_auc_score(df["y"].values, oof_subject_prob)
print("\n===== FINAL =====")
print("ROI-guided subject-level OOF AUC:", auc_oof)

# Bootstrap CI
mean_boot, (ci_lo, ci_hi) = bootstrap_auc_ci(df["y"].values, oof_subject_prob, n_boot=2000, seed=SEED)
print(f"Bootstrap AUC: mean={mean_boot:.3f}, 95% CI=({ci_lo:.3f}, {ci_hi:.3f})")

# Save results
out = pd.DataFrame(fold_stats)
out.loc[len(out)] = {
    "fold": "OOF",
    "auc_subject": float(auc_oof),
    "n_test_subjects": int(len(df)),
    "n_test_slices": int(len(df) * len(roi_z))
}
save_path = "/content/drive/MyDrive/ADHD200-data/roi_guided_results_5fold_oof.csv"
out.to_csv(save_path, index=False)
print("Saved:", save_path)

# =========================================
# ADHD200 ROI-guided CNN (T1) — 5-fold CV
# Cache-first version (Colab-ready)
# =========================================

# -----------------------------
# 0) Install/import basics
# -----------------------------
!pip install -q nilearn nibabel
import os, glob, warnings, math
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

import tensorflow as tf
from tensorflow.keras import layers, models

import nibabel as nib
from nilearn import image
from nilearn.datasets import fetch_atlas_harvard_oxford

# -----------------------------
# 1) Mount Drive
# -----------------------------
from google.colab import drive
drive.mount("/content/drive")

# -----------------------------
# 2) USER SETTINGS (edit here)
# -----------------------------
# (A) Your manifest CSV must contain at least:
#     sub_id, t1_path, y, site
MANIFEST_CSV = "/content/drive/MyDrive/ADHD200/manifest.csv"   # <-- 改成你的
OUT_DIR = "/content/drive/MyDrive/ADHD200/outputs_5fold"
os.makedirs(OUT_DIR, exist_ok=True)

# (B) Cache directories (use your existing cache)
#     你说你已经存了 cache：把这里指向你已有的缓存目录
CACHE_ROOT = "/content/drive/MyDrive/ADHD200-cache"
WARP_CACHE_DIR  = f"{CACHE_ROOT}/warp_mni2mm"   # 每个 subject 一个 *_mni2mm.nii.gz
SLICE_CACHE_DIR = f"{CACHE_ROOT}/roi_slices_npz" # 每个 subject 一个 *_roi_z*.npz

os.makedirs(WARP_CACHE_DIR, exist_ok=True)
os.makedirs(SLICE_CACHE_DIR, exist_ok=True)

print("MANIFEST_CSV:", MANIFEST_CSV)
print("OUT_DIR:", OUT_DIR)
print("WARP_CACHE_DIR:", WARP_CACHE_DIR)
print("SLICE_CACHE_DIR:", SLICE_CACHE_DIR)

# -----------------------------
# 3) Reproducibility
# -----------------------------
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# -----------------------------
# 4) Load manifest
# -----------------------------
df = pd.read_csv(MANIFEST_CSV)

need_cols = ["sub_id", "t1_path", "y", "site"]
missing = [c for c in need_cols if c not in df.columns]
if missing:
    raise ValueError(f"Manifest missing columns: {missing}\nNeed at least: {need_cols}")

df["y"] = df["y"].astype(int)
df = df.reset_index(drop=True)

print("\nManifest subjects:", len(df))
print(df.groupby(["site","y"]).size())

# -----------------------------
# 5) Build ROI mask (Harvard-Oxford, MNI 2mm)
# -----------------------------
atlas = fetch_atlas_harvard_oxford("cort-maxprob-thr25-2mm")
atlas_img = nib.load(atlas.maps)  # MNI 2mm label image
atlas_data = atlas_img.get_fdata().astype(np.int16)
mni_shape = atlas_data.shape
print("\nMNI 2mm shape:", mni_shape)

# Use same ROI indices style as your previous output (example)
# You can adjust these later for ablation
CORTICAL_IDX = [1, 3, 4, 5, 6, 25, 28, 29, 30, 33]
# Harvard-Oxford subcortical atlas is separate; to keep code simple and stable,
# we make ROI from cortical atlas only here.
# (If你已经有subcortical atlas in your old script, we can merge later.)
roi_mask = np.isin(atlas_data, CORTICAL_IDX).astype(np.uint8)

ROI_VOX = int(roi_mask.sum())
print("ROI voxels:", ROI_VOX)

# Pick z slices that have enough ROI voxels
MIN_ROI_VOX_PER_SLICE = 200
eligible_z = [z for z in range(mni_shape[2]) if roi_mask[:, :, z].sum() >= MIN_ROI_VOX_PER_SLICE]
print("Eligible ROI z-slices:", len(eligible_z),
      "| z min/max:", (min(eligible_z), max(eligible_z)) if eligible_z else None)

# Choose fixed number of z slices (keep same style)
N_Z = 16
if len(eligible_z) < N_Z:
    raise ValueError("Not enough eligible z-slices. Lower MIN_ROI_VOX_PER_SLICE or change ROI indices.")
z_min, z_max = min(eligible_z), max(eligible_z)
Z_SLICES = list(np.linspace(z_min, z_max, N_Z).round().astype(int))
Z_SLICES = sorted(list(dict.fromkeys(Z_SLICES)))  # unique & sorted

print("Using z-slices:", Z_SLICES)

# -----------------------------
# 6) Cache helpers
# -----------------------------
def warp_cache_path(sub_id: str) -> str:
    # You can adjust naming to match your existing cache file names.
    # This assumes: {sub_id}_mni2mm.nii.gz
    return os.path.join(WARP_CACHE_DIR, f"{sub_id}_mni2mm.nii.gz")

def slice_cache_path(sub_id: str, z_list) -> str:
    z_sig = "-".join(map(str, z_list))
    return os.path.join(SLICE_CACHE_DIR, f"{sub_id}_roi_z{z_sig}.npz")

def load_warp_from_cache(sub_id: str):
    path = warp_cache_path(sub_id)
    if os.path.exists(path):
        return nib.load(path)
    return None

def load_or_build_subject_slices(sub_id: str, t1_path: str, z_list, roi_mask_3d: np.ndarray):
    """
    Cache-first:
      1) If slice cache exists -> load X (Z,H,W)
      2) Else load warped NIfTI from WARP cache -> cut ROI slices -> save slice cache
      3) If warp cache missing -> return None (skip subject)
    """
    spath = slice_cache_path(sub_id, z_list)
    if os.path.exists(spath):
        try:
            return np.load(spath)["X"].astype(np.float32)
        except Exception:
            pass  # fall through

    wimg = load_warp_from_cache(sub_id)
    if wimg is None:
        # Cache missing: skip
        return None

    vol = wimg.get_fdata().astype(np.float32)
    if vol.shape != roi_mask_3d.shape:
        # Sometimes cached warp might not match atlas grid; try resample to atlas
        try:
            vol_img = nib.Nifti1Image(vol, wimg.affine, wimg.header)
            vol_rs = image.resample_to_img(vol_img, atlas_img, interpolation="continuous")
            vol = vol_rs.get_fdata().astype(np.float32)
        except Exception:
            return None

    X_list = []
    for z in z_list:
        sl = vol[:, :, z]
        m  = roi_mask_3d[:, :, z]
        X_list.append(sl * m)

    X = np.stack(X_list, axis=0).astype(np.float32)
    np.savez_compressed(spath, X=X)
    return X

def build_roi_dataset_cached(df_sub: pd.DataFrame):
    """
    Build slice-level dataset from cached subject slices.
    Returns:
      X: (N_slices, H, W, 1)
      y: (N_slices,)
      sub_ids: (N_slices,)
      kept_subjects: number of subjects kept
      skipped_subjects: number skipped due to missing cache
    """
    X_list, y_list, sub_list = [], [], []
    kept, skipped = 0, 0

    for _, row in df_sub.iterrows():
        sub_id = row["sub_id"]
        t1_path = row["t1_path"]
        y = int(row["y"])

        X_sub = load_or_build_subject_slices(sub_id, t1_path, Z_SLICES, roi_mask)
        if X_sub is None:
            skipped += 1
            continue

        kept += 1
        for i in range(X_sub.shape[0]):
            X_list.append(X_sub[i])
            y_list.append(y)
            sub_list.append(sub_id)

    if kept == 0:
        raise RuntimeError("No subjects kept. Check WARP cache naming/path and atlas alignment.")

    X = np.stack(X_list, axis=0).astype(np.float32)[..., None]
    y = np.array(y_list, dtype=np.int32)
    sub_ids = np.array(sub_list)

    return X, y, sub_ids, kept, skipped

# -----------------------------
# 7) Small CNN
# -----------------------------
def build_small_cnn(input_shape):
    inp = layers.Input(shape=input_shape)
    x = layers.Conv2D(16, 3, padding="same", activation="relu")(inp)
    x = layers.MaxPool2D()(x)
    x = layers.Conv2D(32, 3, padding="same", activation="relu")(x)
    x = layers.MaxPool2D()(x)
    x = layers.Conv2D(64, 3, padding="same", activation="relu")(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(64, activation="relu")(x)
    out = layers.Dense(1, activation="sigmoid")(x)

    model = models.Model(inp, out)
    model.compile(
        optimizer=tf.keras.optimizers.Adam(1e-3),
        loss="binary_crossentropy"
    )
    return model

# -----------------------------
# 8) 5-fold CV (subject-level)
# -----------------------------
N_FOLDS = 5
EPOCHS = 12
BATCH = 32
PATIENCE = 2

y_sub = df["y"].values
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)

fold_stats = []
all_fold_preds = []

print("\n===== START 5-FOLD CV =====")

for fold, (tr_idx, te_idx) in enumerate(skf.split(np.arange(len(df)), y_sub), 1):
    df_tr = df.iloc[tr_idx].reset_index(drop=True)
    df_te = df.iloc[te_idx].reset_index(drop=True)

    print(f"\n===== Fold {fold} =====")
    print("Train subjects:", len(df_tr), "Test subjects:", len(df_te),
          "Train y-dist:", df_tr["y"].value_counts().to_dict(),
          "Test y-dist:", df_te["y"].value_counts().to_dict())

    # Build datasets from cache
    X_tr, y_tr, sub_tr, kept_tr, skipped_tr = build_roi_dataset_cached(df_tr)
    X_te, y_te, sub_te, kept_te, skipped_te = build_roi_dataset_cached(df_te)

    print(f"Train slices: {len(y_tr)} (kept subj {kept_tr}, skipped {skipped_tr})")
    print(f"Test  slices: {len(y_te)} (kept subj {kept_te}, skipped {skipped_te})")

    # Train
    model = build_small_cnn(input_shape=X_tr.shape[1:])
    cb = tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True)

    model.fit(
        X_tr, y_tr,
        validation_split=0.1,
        epochs=EPOCHS,
        batch_size=BATCH,
        callbacks=[cb],
        verbose=1
    )

    # Predict slice probs
    p_te = model.predict(X_te, batch_size=BATCH, verbose=0).reshape(-1)

    # Aggregate to subject probs
    df_pred = pd.DataFrame({"sub_id": sub_te, "y": y_te, "p": p_te})
    subj = df_pred.groupby("sub_id").agg(y=("y","first"), p=("p","mean")).reset_index()

    auc_fold = roc_auc_score(subj["y"].values, subj["p"].values)
    print(f"Fold {fold} subject-level AUC: {auc_fold:.4f}")

    # Save per-fold subject preds (for error analysis)
    subj_out = subj.copy()
    subj_out["fold"] = fold
    # attach site info
    site_map = df_te.set_index("sub_id")["site"].to_dict()
    subj_out["site"] = subj_out["sub_id"].map(site_map)

    fold_pred_path = os.path.join(OUT_DIR, f"preds_subject_fold{fold}.csv")
    subj_out.to_csv(fold_pred_path, index=False)
    print("Saved subject-level preds to:", fold_pred_path)

    all_fold_preds.append(subj_out)

    fold_stats.append({
        "fold": fold,
        "auc_subject": float(auc_fold),
        "n_test_subjects_total": int(len(df_te)),
        "n_test_subjects_kept": int(len(subj)),
        "n_test_subjects_skipped": int(skipped_te),
        "n_test_slices": int(len(y_te))
    })

# -----------------------------
# 9) Final summary
# -----------------------------
stats_df = pd.DataFrame(fold_stats)
print("\n===== FINAL (5-fold) =====")
display(stats_df)

mean_auc = stats_df["auc_subject"].mean()
std_auc  = stats_df["auc_subject"].std(ddof=1)
print(f"\nMean AUC: {mean_auc:.4f} | Std AUC: {std_auc:.4f}")

stats_path = os.path.join(OUT_DIR, "roi_guided_5fold_stats.csv")
stats_df.to_csv(stats_path, index=False)
print("Saved fold stats to:", stats_path)

# Combine all fold preds into one OOF-like table
preds_all = pd.concat(all_fold_preds, ignore_index=True)
preds_path = os.path.join(OUT_DIR, "preds_subject_all_folds.csv")
preds_all.to_csv(preds_path, index=False)
print("Saved all fold subject preds to:", preds_path)

"""# 上一节课结果回顾 & 本节课研究目标：Error Analysis/ Ablation

---

在开始今天的内容之前，我先说一句非常重要的话。

从这一节课开始，我们做的事情，已经不再是“学怎么用深度学习”，而是**在用模型做研究**。  
这两件事情的差别非常大。

当你只是学模型的时候，你关心的是：
- 代码能不能跑
- loss 会不会降
- AUC 能不能再高一点

但当你在做研究的时候，你真正关心的是：
- 这个结果说明了什么？
- 它为什么是这样，而不是那样？
- 如果我要把它写成一篇论文，我要讲一个什么逻辑？

今天这节课的目标，就是完成这个转变。

---

## 一、上一节课我们做了什么？得到了什么结果？

在上一节课中，我们使用 **ADHD200 数据集**，构建了一个基于 **结构性磁共振成像（T1 MRI）** 的分类模型。

这个任务本身并不简单。  
我们要做的是：  
**仅仅根据大脑的结构信息，判断一个人是否被诊断为 ADHD。**

我们的模型有三个非常关键的设计点。

第一，我们使用的是 **多站点数据**。  
这些数据来自不同的医院、不同的扫描仪、不同的扫描参数。  
也就是说，数据中不仅包含“人和人的差异”，还包含“机器和机器的差异”。

第二，我们采用的是 **subject-level 的交叉验证**。  
这意味着，同一个人的数据，永远不会同时出现在训练集和测试集里。  
这是医学影像中最基本、但也最容易被忽视的规范。

第三，我们在 slice 层面进行预测，但**在 subject 层面进行评估**。  
换句话说：
- slice 只是模型的输入单位  
- subject 才是科研结论的评估单位  

在这样的设置下，我们得到的结果是：  
模型在 subject 层面取得了 **大约 0.71 的 AUC**。

---

## 二、AUC ≈ 0.71 到底意味着什么？

当你第一次看到 0.71 的时候，很自然会产生一个反应：

> “这个结果是不是不够好？”

在科研中，这种反应非常常见，但它本身并不是一个“科学问题”。

我们先退一步，问一个更基础的问题。

---

### 什么是 AUC？

AUC 是一个衡量分类模型能力的指标。  
它回答的不是“预测对了多少”，而是：

> **模型有没有能力把真正的 ADHD 个体，整体排在更前面？**

- AUC = 0.5：模型和随机猜测没有区别  
- AUC = 1.0：模型在所有情况下都完全正确  
- AUC ≈ 0.7：模型明显学到了一些东西，但远不完美  

这非常重要，因为 **AUC ≈ 0.7 并不等于模型“没学到东西”**。

---

### 把这个结果放在 ADHD200 的研究背景中

ADHD200 是一个非常著名、也非常“难”的数据集。

在过去十多年里，有大量研究尝试用不同方法做 ADHD 分类，包括：
- 只用结构像（sMRI）
- 只用静息态功能像（fMRI）
- 把结构像和功能像简单拼在一起

一个反复出现、而且非常稳定的结论是：

> **如果只使用结构像，ADHD 分类的 AUC 通常稳定在 0.65–0.75 之间**

这并不是因为研究者不够聪明，也不是因为模型不够复杂，而是因为：

- ADHD 在大脑结构上的差异本身就非常微弱  
- 不同 ADHD 个体之间的差异非常大  
- 多站点数据引入了额外的噪声和偏差  

因此，我们得到的 **AUC ≈ 0.71**，并不是一个“失败的结果”，  
而是一个**非常真实、非常符合领域认知的结果**。

---

## 三、为什么我们现在不继续“把模型调得更好”？

在这个阶段，我们完全可以继续做很多事情：
- 训练更久
- 换更深的网络
- 加更多参数
- 反复调学习率

但所有这些操作，本质上只是在回答一个问题：

> “我们能不能把 0.71 变成 0.72 或 0.73？”

而这个问题，在科研中往往并不是最重要的。

真正重要的问题是：

> **这个 0.71 是怎么来的？  
> 它是由哪些“成功”和哪些“失败”共同组成的？**

这正是我们今天要做的事情。

---

## 四、本节课的核心转变：从“结果”到“错误”

从这一节课开始，我们不再只盯着一个整体指标。  
我们要做的，是把这个指标 **拆开来看**。

在科研中，这一步叫做 **Error Analysis（错误分析）**。

你可以把它理解为：  
我们不再只看“平均分”，而是开始看“错题本”。

---

## 五、什么是 Error Analysis？一个非常直观的类比

想象你在给学生批改一张考试卷。

如果你只看总分，你只知道：
- 这个学生考了 71 分

但你完全不知道：
- 他错的是哪一类题？
- 是计算题错得多，还是概念题错得多？
- 是粗心，还是根本没理解？

Error analysis 做的事情，就是把“71 分”拆解成：
- 哪些题答对了
- 哪些题答错了
- 错得有没有规律

模型也是一样。

---

## 六、第一步：把每一个被试分成四类

在 error analysis 中，我们做的第一件事，是把每一个被试分成四种情况。

- **TP（True Positive）**  
  ADHD，被模型正确预测为 ADHD

- **TN（True Negative）**  
  非 ADHD，被模型正确预测为非 ADHD

- **FP（False Positive）**  
  非 ADHD，但模型预测成 ADHD

- **FN（False Negative）**  
  ADHD，但模型预测成非 ADHD

这一步非常重要，因为它让我们第一次从“数字”回到“人”。

我们开始关心的是：

> **模型具体是在哪些人身上做对了？  
> 又是在哪些人身上做错了？**

---

## 七、第二步：区分“模糊错误”和“高置信错误”

模型并不是只输出“对”或“错”。  
它输出的是一个 **概率**。

例如：
- 0.51：模型其实非常犹豫  
- 0.95：模型非常自信  

这意味着，所有错误其实并不一样。

我们会重点区分两类错误：

第一类，是**接近 0.5 的错误**。  
这些错误往往意味着：
- 个体本身处在诊断边界附近  
- ADHD 的结构特征并不明显  

第二类，是**非常自信但预测错误的情况**。  
这些错误非常有研究价值，因为它们可能暗示：
- 站点差异  
- 扫描协议偏差  
- 甚至标签本身存在不确定性  

在真正的研究中，这一类错误往往比“整体 AUC”更值得分析。

---

## 八、第三步：错误是否和站点有关？

ADHD200 是一个多站点数据集。  
这意味着一个非常现实的问题：

> 模型到底是在学习 ADHD，  
> 还是在学习“这是哪个医院的数据”？

因此，在 error analysis 中，我们一定要做的一件事是：

- 按站点分别看模型表现  
- 比较不同站点的错误率  
- 看错误是否集中在某几个站点  

如果我们发现：
- 某些站点的 FN 特别多  
- 或者 FP 明显偏高  

那说明模型的失败，很可能和 **domain shift** 有关，而不只是 ADHD 本身。

---

## 九、为什么 Error Analysis 在科研中非常重要？

Error analysis 有三个非常重要的作用。

第一，它让模型不再是黑箱。  
我们开始理解模型“在想什么”。

第二，它帮助我们区分：
- 哪些问题是模型可以改进的  
- 哪些问题是数据或任务本身就很难的  

第三，它直接决定下一步研究该怎么走。

---

## 十、下一步为什么要做 Ablation？

当我们做完 error analysis 之后，一个问题自然会出现：

> 模型现在的表现，是因为“我们这样设计模型”，  
> 还是因为“无论怎么设计，结构像就只能到这里”？

这时候，就需要 **Ablation Study（消融实验）**。

Ablation 的核心思想非常简单：

> **有意识地拿掉模型的一部分，  
> 看结果会发生什么变化。**

例如：
- 不用 ROI，只用全脑  
- 只用皮层，不用皮层下结构  
- 减少 slice 数量  

Ablation 并不是为了“让分数更好看”，  
而是为了回答一个更重要的问题：

> **我们模型中的哪些设计，真的有意义？**

---

## 十一、总结：今天这一节课在整篇研究中的位置

到这里，我们可以总结一下。

在这项研究中：
- 模型不是最终目标  
- AUC 也不是最终目标  

模型只是一个 **研究工具（probe）**，  
用来帮助我们理解：

- ADHD 在结构层面的异质性  
- 多站点数据带来的挑战  
- 以及机器学习模型在真实神经影像数据中的失败模式  

这正是今天这节课的核心意义。

下一步，我们会在这个基础上，正式进入 **Ablation Study**，  
而那一步，是真正把结果推向“可以写论文”的关键。

"""

# =========================================
# STEP 1: Error Analysis (paper-ready)
# Colab-ready script
# =========================================

import os, glob, warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    roc_auc_score, roc_curve,
    accuracy_score, balanced_accuracy_score,
    confusion_matrix
)
from sklearn.calibration import calibration_curve


# -------------------------
# 0) Mount Google Drive
# -------------------------
from google.colab import drive
drive.mount("/content/drive")


# -------------------------
# 1) Locate prediction file
# -------------------------
SEARCH_DIR = "/content/drive/MyDrive"   # 你也可以改成更具体的目录，比如 /content/drive/MyDrive/ADHD200-data
CANDIDATES = sorted(
    glob.glob(os.path.join(SEARCH_DIR, "**", "*pred*.csv"), recursive=True)
)

print(f"Search dir: {SEARCH_DIR}")
print(f"Found {len(CANDIDATES)} candidate pred csv files (showing up to 30):")
for p in CANDIDATES[:30]:
    print(" -", p)

# ✅ 你可以在这里手动指定你要用的文件
PRED_PATH = None  # <-- 改成你的路径字符串，例如: "/content/drive/MyDrive/ADHD200-data/preds_subject_oof.csv"

if PRED_PATH is None:
    if len(CANDIDATES) == 0:
        raise FileNotFoundError(
            "No *pred*.csv found under SEARCH_DIR. "
            "Please set SEARCH_DIR to the folder you saved preds into, "
            "or manually set PRED_PATH."
        )
    # 默认用第一个（你也可以改成最后一个）
    PRED_PATH = CANDIDATES[0]
    print("\n[Auto-select] Using:", PRED_PATH)
else:
    print("\n[Manual] Using:", PRED_PATH)


# -------------------------
# 2) Load predictions
# -------------------------
df = pd.read_csv(PRED_PATH)
print("\nLoaded shape:", df.shape)
print("Columns:", list(df.columns))
display(df.head())


# -------------------------
# 3) Standardize columns
# -------------------------
# 你可能的列名：y_true/y, y_pred/p/p_oof, subject id: sub_id, site: site
# 我们做一个“智能映射”，把它统一成：sub_id, y_true, y_pred, site(可选)

def pick_first_existing(cols, candidates):
    for c in candidates:
        if c in cols:
            return c
    return None

cols = set(df.columns)

sub_col  = pick_first_existing(cols, ["sub_id", "subject", "subject_id", "SubID", "SUB_ID"])
y_col    = pick_first_existing(cols, ["y_true", "y", "label", "target"])
p_col    = pick_first_existing(cols, ["y_pred", "p", "p_oof", "prob", "pred", "pred_prob", "y_score"])
site_col = pick_first_existing(cols, ["site", "Site", "scanner_site", "dataset", "center"])

if sub_col is None or y_col is None or p_col is None:
    raise ValueError(
        f"Missing required columns.\n"
        f"Detected sub_id col: {sub_col}\n"
        f"Detected y col: {y_col}\n"
        f"Detected pred col: {p_col}\n"
        f"Please make sure your csv includes subject id + label + probability."
    )

work = df.copy()
work = work.rename(columns={sub_col:"sub_id", y_col:"y_true", p_col:"y_pred"})
if site_col is not None:
    work = work.rename(columns={site_col:"site"})
else:
    work["site"] = "NA"

# 确保类型正确
work["y_true"] = work["y_true"].astype(int)
work["y_pred"] = work["y_pred"].astype(float)

print("\nStandardized columns:", list(work.columns))
display(work[["sub_id","y_true","y_pred","site"]].head())


# -------------------------
# 4) If slice-level (duplicate sub_id), aggregate to subject-level
# -------------------------
dup = work["sub_id"].duplicated().any()
if dup:
    print("\nDetected duplicated sub_id -> assuming slice-level rows. Aggregating to subject-level by mean prob.")
    subj = (work
            .groupby(["sub_id","y_true","site"], as_index=False)["y_pred"]
            .mean())
else:
    subj = work[["sub_id","y_true","y_pred","site"]].copy()

print("\nSubject-level table shape:", subj.shape)
display(subj.head())


# -------------------------
# 5) Global metrics + best threshold (Youden J)
# -------------------------
y = subj["y_true"].values
p = subj["y_pred"].values

auc = roc_auc_score(y, p)
fpr, tpr, thr = roc_curve(y, p)
j = tpr - fpr
best_i = int(np.argmax(j))
best_thr = float(thr[best_i])

y_hat = (p >= best_thr).astype(int)
acc  = accuracy_score(y, y_hat)
bacc = balanced_accuracy_score(y, y_hat)
cm   = confusion_matrix(y, y_hat)

print("\n===== Global performance =====")
print(f"AUC: {auc:.4f}")
print(f"Best threshold (Youden J): {best_thr:.4f}")
print(f"Accuracy: {acc:.4f}")
print(f"Balanced Accuracy: {bacc:.4f}")
print("Confusion matrix [ [TN FP], [FN TP] ]:\n", cm)


# -------------------------
# 6) Add TP/TN/FP/FN groups + error flags
# -------------------------
subj = subj.copy()
subj["y_hat"] = (subj["y_pred"] >= best_thr).astype(int)

subj["group"] = np.where((subj.y_true==1) & (subj.y_hat==1), "TP",
                 np.where((subj.y_true==0) & (subj.y_hat==0), "TN",
                 np.where((subj.y_true==0) & (subj.y_hat==1), "FP", "FN")))

subj["is_error"] = (subj["y_hat"] != subj["y_true"]).astype(int)

print("\nGroup counts:")
display(subj["group"].value_counts())


# -------------------------
# 7) Plot distributions by group (paper-friendly)
# -------------------------
def hist_by_group(df, group, bins=30):
    vals = df.loc[df.group==group, "y_pred"].values
    plt.figure()
    plt.hist(vals, bins=bins)
    plt.title(f"Pred prob distribution: {group} (n={len(vals)})")
    plt.xlabel("y_pred")
    plt.ylabel("count")
    plt.show()

for g in ["TP","TN","FP","FN"]:
    hist_by_group(subj, g)


# -------------------------
# 8) Confident wrong lists (case study table)
# -------------------------
CONF_FP_THR = 0.80
CONF_FN_THR = 0.20

conf_fp = subj[(subj.y_true==0) & (subj.y_pred>=CONF_FP_THR)].sort_values("y_pred", ascending=False)
conf_fn = subj[(subj.y_true==1) & (subj.y_pred<=CONF_FN_THR)].sort_values("y_pred", ascending=True)

print("\n===== Confident wrong =====")
print("Confident FP (true=0, pred>=0.80):", len(conf_fp))
print("Confident FN (true=1, pred<=0.20):", len(conf_fn))

display(conf_fp.head(20))
display(conf_fn.head(20))


# -------------------------
# 9) Site-wise performance + error concentration
# -------------------------
rows = []
for site, d in subj.groupby("site"):
    y_s = d["y_true"].values
    p_s = d["y_pred"].values

    # AUC requires both classes
    if np.unique(y_s).size < 2:
        site_auc = np.nan
    else:
        site_auc = roc_auc_score(y_s, p_s)

    site_acc  = accuracy_score(y_s, (p_s >= best_thr).astype(int))
    site_bacc = balanced_accuracy_score(y_s, (p_s >= best_thr).astype(int))

    err_rate = float(np.mean(d["is_error"].values))
    fn_rate  = float(np.mean((d["group"].values=="FN").astype(int)))
    fp_rate  = float(np.mean((d["group"].values=="FP").astype(int)))

    rows.append([site, len(d), float(np.mean(y_s)), site_auc, site_acc, site_bacc, err_rate, fn_rate, fp_rate])

site_perf = pd.DataFrame(
    rows,
    columns=["site","n","pos_rate","auc","acc","bacc","err_rate","fn_rate","fp_rate"]
).sort_values(["n"], ascending=False)

print("\n===== Site-wise performance =====")
display(site_perf)

plt.figure()
vals = site_perf["auc"].fillna(0).values
plt.bar(site_perf["site"].values, vals)
plt.xticks(rotation=45, ha="right")
plt.title("Site-wise AUC (NaN -> 0 for display)")
plt.ylabel("AUC")
plt.show()

plt.figure()
plt.bar(site_perf["site"].values, site_perf["err_rate"].values)
plt.xticks(rotation=45, ha="right")
plt.title("Site-wise error rate")
plt.ylabel("Error rate")
plt.show()


# -------------------------
# 10) Calibration curve (optional but strong for paper)
# -------------------------
prob_true, prob_pred = calibration_curve(y, p, n_bins=10, strategy="quantile")

plt.figure()
plt.plot(prob_pred, prob_true, marker="o")
plt.plot([0,1],[0,1])
plt.title("Calibration curve (subject-level)")
plt.xlabel("Mean predicted probability")
plt.ylabel("Fraction of positives")
plt.show()


# -------------------------
# 11) Save outputs for paper / next steps
# -------------------------
OUT_DIR = os.path.join(os.path.dirname(PRED_PATH), "error_analysis_outputs")
os.makedirs(OUT_DIR, exist_ok=True)

subj_out_path = os.path.join(OUT_DIR, "subject_error_table.csv")
site_out_path = os.path.join(OUT_DIR, "site_performance.csv")
fp_out_path   = os.path.join(OUT_DIR, "confident_FP.csv")
fn_out_path   = os.path.join(OUT_DIR, "confident_FN.csv")

subj.to_csv(subj_out_path, index=False)
site_perf.to_csv(site_out_path, index=False)
conf_fp.to_csv(fp_out_path, index=False)
conf_fn.to_csv(fn_out_path, index=False)

print("\nSaved:")
print(" -", subj_out_path)
print(" -", site_out_path)
print(" -", fp_out_path)
print(" -", fn_out_path)