# -*- coding: utf-8 -*-
"""ADHD_abalation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6yFuOpf0oXHFQxz67nx2-Q-8HVbMVEV

# 📚 项目阶段性回顾：我们到底做了什么？


我们到底构建了一个怎样的模型？

我们已经做了哪些选择？

这些选择背后有哪些假设？

---

# 第一阶段：我们的问题是什么？

我们的目标是：

利用结构性 MRI（T1）预测一个人是否 ADHD。

输入：
3D 大脑结构图像

输出：
ADHD 概率

评估方式：
Subject-level AUC

---

# 第二阶段：数据层面我们做了什么？

我们使用的是 ADHD200 多站点数据。

这意味着：

- 来自多个医院
- 不同 scanner
- 不同扫描协议
- 不同人群结构

这带来两个问题：

1️⃣ 数据分布不一致  
2️⃣ Site bias 风险  

---

# 第三阶段：空间统一（Registration）

我们做了：

Rigid registration 到 MNI 2mm 空间。

目的：

让不同人的大脑在空间上对齐。

假设：

空间对齐有助于模型比较结构差异。

---

# 第四阶段：语义选择（ROI）

我们没有用全脑。

我们使用 Harvard-Oxford atlas，

选择：

- Frontal cortex
- Cingulate
- Striatum 相关区域

假设：

ADHD 差异集中在 fronto-striatal circuit。

---

# 第五阶段：强度标准化（Normalization）

我们对每个 slice 做 z-score normalization。

原因：

不同 site 的强度范围不同。

假设：

强度差异是噪声，不是疾病信号。

---

# 第六阶段：模型结构

我们使用：

- 2D CNN
- Slice-level prediction
- Subject-level aggregation（mean）

假设：

ADHD 是分布式弱效应，
多个 slice 共同提供信息。

---

# 第七阶段：评估方式

我们使用：

- Subject-level 5-fold CV
- Out-of-fold AUC
- Bootstrap CI

原因：

避免数据泄漏，
提高结果稳定性。

---

# 第八阶段：我们现在有什么？

我们现在有：

一个完整 pipeline：

Registration  
→ ROI selection  
→ Normalization  
→ CNN  
→ Aggregation  
→ CV AUC  

结果：

Subject-level AUC = X

---

# 📄 如果你是 Reviewer…

我们今天换一个身份。

假设你不是学生。

假设你是期刊审稿人（reviewer）。

有人给你提交了一篇论文：

“Using Structural MRI to Predict ADHD with Deep Learning  
Subject-level AUC = 0.8”

你会怎么审稿？

---

## 🧠 如果你是 reviewer，你会问什么？

你可能会问：

- 是否做了 ablation study？
- 是否检测了 site bias？
- 是否报告了置信区间？
- 是否做了 cross-site validation？
- 是否排除了 shortcut learning？

如果这些都没有，

那这个结果——

是不可信的。

---

# 为什么 reviewer 会问这些？

因为在医学 AI 领域，

一个模型“有效”并不等于“真实”。

模型可能学到：

- scanner 差异
- site 分布
- 年龄结构
- 数据处理流程
- 标签比例不均衡

而不是疾病本身。

---

# 🔥 关键问题

如果模型可以通过 site 信息间接预测 ADHD，

那它真的在学脑结构吗？

如果模型的结果没有置信区间，

那我们知道这个结果稳定吗？

如果模型没有做 cross-site 验证，

那它真的能泛化吗？

---

# 所以今天这节课要做什么？

我们今天不再讨论：

“模型效果好不好？”

我们要讨论：

“模型为什么有效？”

以及：

“它是不是在作弊？”

---

# 今天的核心主题

在科研中，有一个非常重要的工具，

专门用来回答这些问题。

它叫：

# Ablation Study（消融实验）

---

Ablation study 的核心目标不是提高 AUC。

而是验证：

模型是否依赖我们认为重要的机制。

它是：

模型可信度的审查工具。

今天我们要学习的，

不是如何调参，

而是如何审问模型。

# 🧠 Ablation Study：我们如何判断一个模型是否可信？

---

# 第一部分：我们到底在做什么？

我们现在有一个模型。

它输入一张大脑 MRI，
输出一个概率：

这个人是否 ADHD。

模型的效果用一个数字表示：

AUC = 0.83。

听起来不错。

但问题来了：

我们真的理解这个数字吗？

---

# 第二部分：基础概念

在讨论 ablation 之前，我们必须先理解几个核心概念。

---

## 1️⃣ 什么是“模型”？

模型就是：

一个从输入到输出的函数。

输入：MRI 图像  
输出：ADHD 概率  

本质上，它在寻找：

输入中的某种模式 → 与标签的关系。

---

## 2️⃣ 什么是 AUC？

AUC 是一种衡量模型区分能力的指标。

简单理解：

AUC = 随机抽一个 ADHD 和一个 非ADHD，
模型给 ADHD 更高分的概率。

- AUC = 0.5 → 随机猜
- AUC = 1.0 → 完美区分
- AUC < 0.5 → 方向反了

---

## 提问

AUC = 0.83 是什么意思？





意味着：

随机抽一对 ADHD / 非ADHD，

模型有 83% 的概率把 ADHD 排在前面。

这不是 83% 准确率。

这是排序能力。

---

## 3️⃣ 什么是“偏差”？

在机器学习中，偏差有两种：

1. 数据偏差（dataset bias）
2. 模型偏差（model bias）

例如：

如果一个医院 ADHD 比例更高，

模型可能学到：

“这个医院 → ADHD”

而不是：

“这个脑结构 → ADHD”

---

## 4️⃣ 什么是“泛化”？

泛化指的是：

模型在新数据上是否仍然有效。

如果模型只在一个 site 表现好，

在其他 site 表现差，

那它没有泛化能力。

---

# 第三部分：因果 vs 相关

一个非常重要的概念：

相关不等于因果。

如果：

scanner 强度 与 ADHD 有相关，

模型可能利用这个相关。

但 scanner 强度不是 ADHD 的原因。

这就是 shortcut learning。

---

# 第四部分：什么是 Shortcut Learning？

Shortcut learning 指：

模型选择一个“更容易”的路径，

而不是我们希望的机制。

在多站点 MRI 中：

容易路径：

scanner → site → label

困难路径：

brain structure → label

如果我们不做 ablation，

我们无法检测 shortcut。

---

# 第五部分：什么是 Ablation Study？
医学 AI 领域有一个非常常见的问题：

模型能预测。

但模型不知道自己在预测什么。

更准确地说：

我们不知道模型在用什么做判断。

这节课，我们要做一件非常重要的事情：

我们要拆解模型。

Ablation 原本是医学术语，意思是“切除”。

在机器学习中：

Ablation study = 有控制地移除模型的某个组件，观察性能如何变化。

这听起来很简单。

但它的意义非常深。

它意味着：

我们不再满足于“结果”，

我们开始研究“机制”。

#如果不做 Ablation，会发生什么？

想象一个场景：

我们有多站点 MRI 数据。

Site A：
- ADHD 比例 60%
- 强度范围偏高

Site B：
- ADHD 比例 30%
- 强度范围偏低

如果我们不做 normalization，

模型可能学到：

“强度偏高 → ADHD”

AUC 可能很高。

但模型学到的不是脑结构差异，
而是 scanner 差异。

这叫做：

Shortcut learning。

Shortcut learning 是医学 AI 最大的风险之一。
# Ablation 的哲学意义

Ablation study 本质上是一个因果问题。

我们在问：

这个组件是因吗？

性能变化是果吗？

如果移除 A，结果变化，

我们可以推断：

A 对结果有因果贡献。

这是一种接近因果推断的实验设计。
# 我们模型的结构拆解

我们当前 pipeline 包含：

1. ROI selection
2. Registration 到 MNI
3. Slice normalization
4. CNN
5. Subject aggregation

每一个步骤都包含一个假设。

---

ROI 的假设：

ADHD 主要影响 fronto-striatal circuit。

Registration 的假设：

空间对齐能增强结构对比。

Normalization 的假设：

强度差异是噪声。

Aggregation 的假设：

ADHD 是分布式弱效应。

---

每一个假设都可以被验证。

这就是 ablation 的意义。

---

---

# 如何科学地设计 Ablation？

三个原则：

1. 一次只改变一个变量
2. 保持其他条件完全一致
3. 使用相同的 CV 划分

否则我们无法解释结果。

---

# 统计层面的分析

很多人做 ablation 只看 AUC。

这是不够的。

我们需要看：

1. ΔAUC
2. fold consistency
3. 置信区间

如果一个组件真的重要：

- 每个 fold 都下降
- CI 明显分离

如果只是随机波动：

- 有的 fold 上升，有的下降

---

# 三种典型结果模式

模式一：

去掉 ROI，AUC 明显下降。

解释：

神经科学假设得到支持。

模式二：

去掉 ROI，AUC 不变。

解释：

信号可能分布在全脑。

模式三：

去掉 normalization，AUC 上升。

解释：

模型在利用 scanner 差异。

这是危险信号。

---

# 医学 AI 中的真实案例

历史上有很多模型：

预测肺炎时，

模型关注的是：

X-ray 上的医院水印。

而不是肺部区域。

AUC 很高。

但完全不可泛化。

这就是没有做 ablation 的后果。

---

# 我们真正要问的问题

当我们做完 ablation，

我们真正要回答的是：

模型在学什么？

如果我们确认：

ROI 有贡献  
Registration 必要  
Normalization 防止 shortcut  

那么我们可以说：

模型学到的是结构差异。

---

# 更高阶的思考

Ablation 其实也是模型解释的一种形式。

它比 SHAP 更宏观。

SHAP 解释 feature。

Ablation 解释模块。

它回答：

哪个模块在驱动整体 performance。



---

# 第六部分：对抗式思考开始

现在我们开始质疑模型。

---

## 🔥 提问 1

如果去掉 ROI，

AUC 不变，

说明什么？

是不是说明模型没有真正依赖 hypothesized circuit？

---

## 🔥 提问 2

如果 random slices 和 ROI slices 一样好，

说明什么？

是不是说明模型在学 global intensity？

---

# 第七部分：统计波动的概念

假设：

Full AUC = 0.63  
No ROI = 0.60  

差 0.03。

这个差异大吗？

---

我们必须理解：

统计波动（statistical variance）。

如果测试样本很少，

AUC 会波动很大。

这就是为什么我们要：

- 5-fold CV
- bootstrap CI

---

## 什么是 bootstrap？

简单理解：

重复随机抽样，
看 AUC 分布。

如果 CI 很窄，

结果稳定。

如果 CI 很宽，

结果不可靠。

---

# 第八部分：Registration 的机制问题

Registration 是空间对齐。

如果去掉 registration，

AUC 下降很多，

说明模型依赖解剖结构。

如果不变，

说明模型可能依赖非空间信息。

---

# 第九部分：Normalization 的风险

如果去掉 normalization，

AUC 上升，

说明什么？

说明模型可能在利用 scanner 强度差异。

这不是疾病机制。

---

## 🔥 问题

如果 normalization 让 AUC 降低，

我们应该去掉 normalization 吗？

答案：

不能为了更高 AUC，
牺牲泛化能力。

---

# 第十部分：Aggregation 的哲学问题

Mean aggregation：

假设 ADHD 是分布式弱效应。

Max aggregation：

假设 ADHD 是局部强效应。

---

如果 max 更好，

说明什么？

是不是说明 ADHD 有局部异常？

还是说明 max 更容易过拟合？

---


# 课堂讨论

1. 如果 ROI 不重要，是否说明神经科学假设错误？
2. 如果 normalization 提高泛化但降低 AUC，我们是否应该保留？
3. 如何设计一个“反例模型”来证明 shortcut？



---

# 🧨 如何设计一个“反例模型”来证明 Shortcut Learning？

---

# 第一部分：我们想证明什么？

我们怀疑：

模型可能没有学到脑结构差异，

而是在学：

scanner → site → ADHD 比例

这叫做：

Shortcut learning（捷径学习）。

现在问题来了：

我们怎么证明模型在走捷径？

---

# 第二部分：科学思维的关键

如果我们怀疑模型在作弊，

我们应该做什么？

我们应该：

设计一个“故意作弊”的模型。

如果这个作弊模型效果也不错，

说明 shortcut 确实存在。

这叫：

构造反例（counterexample）。

---

# 第三部分：反例模型思路一 —— 只用 Site 预测 ADHD

我们做一个极端实验：

完全不用 MRI 图像。

只用一个变量：

site。

---

# 🔥 提问

如果某些医院 ADHD 比例更高，

site 本身是否可以提供预测信息？

答案是：可以。

---

## 设计方法

Step 1：
统计每个 site 的 ADHD 比例。

例如：

Site A：60% ADHD  
Site B：30% ADHD  
Site C：50% ADHD  

Step 2：
对所有 Site A 的被试，

预测概率 = 0.60。

对 Site B：

预测概率 = 0.30。

Step 3：
计算 AUC。

---

如果这个“零图像模型”的 AUC 也接近 0.60，

说明：

site 本身已经包含大量标签信息。

模型很可能在利用 site。

---

# 第四部分：反例模型思路二 —— 打乱图像但保留 Site

另一个更强的反例：

我们把所有图像随机打乱，

但保留 site 信息。

也就是说：

图像内容完全错位，

但 site → label 关系保留。

如果模型仍然表现不错，

说明它根本没有依赖脑结构。

---

# 第五部分：反例模型思路三 —— 只用强度统计量

我们构造一个“简化模型”：

只提取每个被试的：

- 平均强度
- 强度标准差
- 最大值

不输入图像，

只输入这些统计量。

如果这个模型 AUC 也不错，

说明强度分布本身具有预测性。

那 normalization 的重要性就被验证了。

---

# 第六部分：反例模型思路四 —— 标签随机化测试

最经典的方法：

随机打乱标签。

如果模型在随机标签下仍然得到 AUC > 0.6，

说明模型在过拟合数据结构。

这是检测“伪信号”的方法。

---

# 第七部分：为什么这种方法有效？

因为我们在构造一个逻辑链条：

如果模型学的是脑结构，

那打乱图像 → 性能应崩溃。

如果模型学的是 site，

那即使图像错位，

性能可能仍然存在。

---

# 第八部分：对抗式提问

## 🔥 提问 1

如果 site-only 模型 AUC = 0.58，

而我们完整模型 AUC = 0.63，

差距只有 0.05。

我们还能说模型主要学到脑结构吗？

---

## 🔥 提问 2

如果 random-label 模型 AUC 仍然 0.55，

说明什么？

说明模型在利用数据分布不平衡。

---

## 🔥 提问 3

如果强度统计量模型 AUC = 0.60，

说明什么？

说明 scanner 强度差异已经可以预测标签。

---

# 第九部分：科研意义

反例模型的目的不是让模型变差。

而是证明：

“真正有效的模型必须比这些作弊模型更强。”

如果 Full model 远高于：

- site-only
- intensity-only
- random-label

我们才可以说：

模型确实利用了脑结构。

---

# 第十部分：更高阶思维

这是一种“可证伪”的思维方式。

我们不是在证明模型是对的。

我们是在努力证明模型可能是错的。

如果它经得起攻击，

我们才相信它。

---

# 最后的核心思想

一个模型如果无法击败一个作弊模型，

那它就不值得信任。

Ablation 是拆解模型。

反例模型是攻击模型。

真正可信的模型，

必须在攻击中幸存。
"""

# ============================================
# Ablation Study: ROI-guided ADHD T1 MRI Classification (Colab-ready)
# - Subject-level 5-fold CV
# - Configurable ablations:
#   A) Slice sampling: ROI / Whole-brain / Random
#   B) Registration: ON / OFF
#   C) Normalization: ON / OFF
#   D) Subject aggregation: mean / max
# - Output: ablation_results.csv
# ============================================
from google.colab import drive
drive.mount('/content/drive')

!pip -q install nilearn antspyx nibabel scikit-learn tensorflow

import os, glob, re, hashlib, json
import numpy as np
import pandas as pd

import nibabel as nib
import ants
from nilearn import datasets, image

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

import tensorflow as tf
from tensorflow.keras import layers, models

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ===== EDIT HERE =====
MANIFEST_PATH = "/content/drive/MyDrive/ADHD200-data/manifest_all_sitefirst_strictpass_noBrown.csv"

# Cache for warped T1 (only used when registration ON)
CACHE_DIR = "/content/drive/MyDrive/ADHD200-cache/mni2mm_rigid"
os.makedirs(CACHE_DIR, exist_ok=True)

# ===== Training hyperparams =====
IMG_SIZE = 128
BATCH = 32
EPOCHS = 12
PATIENCE = 2
LR = 1e-3

# ===== Slice sampling defaults =====
MAX_SLICES_PER_SUBJECT = 16          # used by ROI and Random and Whole-brain (we will sample to this size)
MIN_ROI_VOXELS_PER_SLICE = 200       # ROI slice eligibility threshold (in MNI space)
USE_EVENLY_SPACED_SLICES = True      # ROI selection method

assert os.path.exists(MANIFEST_PATH), f"Manifest not found: {MANIFEST_PATH}"
print("OK manifest:", MANIFEST_PATH)

def resize_slice(x2d, out=IMG_SIZE):
    x = tf.convert_to_tensor(x2d[..., None], dtype=tf.float32)  # (H,W,1)
    x = tf.image.resize(x, (out, out), method="bilinear")
    return x.numpy()[..., 0]

def normalize_slice(x2d):
    x = x2d.astype(np.float32)
    m = np.nanmean(x)
    s = np.nanstd(x)
    if not np.isfinite(s) or s < 1e-6:
        return np.zeros_like(x, dtype=np.float32)
    x = (x - m) / s
    x = np.clip(x, -5, 5)
    return x.astype(np.float32)

def as_nii(maps_obj):
    if isinstance(maps_obj, nib.spatialimages.SpatialImage):
        return maps_obj
    return nib.load(maps_obj)

def nii_to_ants(nii_img):
    data = nii_img.get_fdata().astype(np.float32)
    aff  = np.array(nii_img.affine, dtype=np.float64)
    spacing = list(map(float, nii_img.header.get_zooms()[:3]))
    origin  = list(map(float, aff[:3, 3].tolist()))
    direction = (aff[:3, :3] / np.array(spacing)[None, :]).astype(np.float64).tolist()
    return ants.from_numpy(data, spacing=spacing, origin=origin, direction=direction)

def cache_path(t1_path):
    h = hashlib.md5(t1_path.encode("utf-8")).hexdigest()
    return os.path.join(CACHE_DIR, f"{h}_mni2mm_rigid.nii.gz")

df = pd.read_csv(MANIFEST_PATH).copy()
df = df.dropna(subset=["t1_path", "y"]).reset_index(drop=True)
df["y"] = df["y"].astype(int)

print("N subjects:", len(df))
print(df.groupby("site")["y"].value_counts())

# MNI 2mm template (nibabel image)
mni_2mm = datasets.load_mni152_template(resolution=2)

# Harvard-Oxford atlas in MNI space
ho_cort = datasets.fetch_atlas_harvard_oxford("cort-maxprob-thr25-2mm")
ho_sub  = datasets.fetch_atlas_harvard_oxford("sub-maxprob-thr25-2mm")

cort_img = as_nii(ho_cort.maps)
sub_img  = as_nii(ho_sub.maps)

cort = cort_img.get_fdata().astype(int)
subc = sub_img.get_fdata().astype(int)

cort_labels = list(ho_cort.labels)
sub_labels  = list(ho_sub.labels)

# Define ADHD-relevant ROI set (可按你们课上说法改)
CORT_ROI_NAMES = [
    "Frontal Pole",
    "Superior Frontal Gyrus",
    "Middle Frontal Gyrus",
    "Inferior Frontal Gyrus, pars triangularis",
    "Inferior Frontal Gyrus, pars opercularis",
    "Frontal Medial Cortex",
    "Frontal Orbital Cortex",
    "Paracingulate Gyrus",
    "Cingulate Gyrus, anterior division",
    "Cingulate Gyrus, posterior division",
]
SUB_ROI_NAMES = [
    "Thalamus",
    "Caudate",
    "Putamen",
    "Pallidum",
    "Accumbens",
]

def idx_by_name(labels, name_contains):
    out = []
    key = name_contains.lower()
    for i, lab in enumerate(labels):
        if isinstance(lab, bytes):
            lab = lab.decode("utf-8", errors="ignore")
        if key in str(lab).lower():
            out.append(i)
    return out

cort_ids = []
for nm in CORT_ROI_NAMES:
    cort_ids += idx_by_name(cort_labels, nm)
cort_ids = sorted(set([i for i in cort_ids if i != 0]))

sub_ids = []
for nm in SUB_ROI_NAMES:
    sub_ids += idx_by_name(sub_labels, nm)
sub_ids = sorted(set([i for i in sub_ids if i != 0]))

roi_mask = np.zeros_like(cort, dtype=bool)
for rid in cort_ids:
    roi_mask |= (cort == rid)
for rid in sub_ids:
    roi_mask |= (subc == rid)

roi_counts_by_z = roi_mask.sum(axis=(0,1))
roi_z_all = np.where(roi_counts_by_z >= MIN_ROI_VOXELS_PER_SLICE)[0].tolist()

print("ROI voxels:", int(roi_mask.sum()))
print("Eligible ROI z-slices:", len(roi_z_all),
      "| z min/max:", (min(roi_z_all) if roi_z_all else None, max(roi_z_all) if roi_z_all else None))

assert len(roi_z_all) > 0, "No ROI slices found. Lower MIN_ROI_VOXELS_PER_SLICE."

def pick_z_slices(roi_z_list, k=MAX_SLICES_PER_SUBJECT):
    if len(roi_z_list) <= k:
        return roi_z_list
    if USE_EVENLY_SPACED_SLICES:
        idx = np.linspace(0, len(roi_z_list)-1, k).round().astype(int)
        return [roi_z_list[i] for i in idx]
    rng = np.random.default_rng(SEED)
    return sorted(rng.choice(roi_z_list, size=k, replace=False).tolist())

ROI_Z = pick_z_slices(roi_z_all, MAX_SLICES_PER_SUBJECT)
print("Using ROI z-slices:", ROI_Z)

def get_warped_mni2mm_path(t1_path):
    out = cache_path(t1_path)
    if os.path.exists(out):
        return out

    # fixed: MNI
    fixed_nii = image.load_img(mni_2mm)
    fixed_nii = fixed_nii if isinstance(fixed_nii, nib.spatialimages.SpatialImage) else nib.load(fixed_nii)

    # moving: subject T1
    mov_nii = nib.load(t1_path)

    fixed  = nii_to_ants(fixed_nii)
    moving = nii_to_ants(mov_nii)

    reg = ants.registration(fixed=fixed, moving=moving, type_of_transform="Rigid")
    warped = reg["warpedmovout"]

    ants.image_write(warped, out)
    return out

def sample_z_slices(vol_shape_z, mode, roi_z=ROI_Z, k=MAX_SLICES_PER_SUBJECT, seed=SEED):
    """
    mode:
      - "roi": use ROI_Z
      - "whole": evenly sample across whole brain z
      - "random": random sample k slices from whole brain z
    """
    Z = vol_shape_z
    if mode == "roi":
        return [z for z in roi_z if 0 <= z < Z]

    all_z = list(range(Z))
    if len(all_z) <= k:
        return all_z

    if mode == "whole":
        idx = np.linspace(0, Z-1, k).round().astype(int)
        return sorted(set(idx.tolist()))

    if mode == "random":
        rng = np.random.default_rng(seed)
        return sorted(rng.choice(all_z, size=k, replace=False).tolist())

    raise ValueError(f"Unknown mode: {mode}")

def load_volume(t1_path, use_registration):
    """
    Returns vol float32 array (X,Y,Z).
    - If registration ON: warped image in MNI space (cached)
    - If OFF: raw subject space
    """
    if use_registration:
        warped_path = get_warped_mni2mm_path(t1_path)
        vol = nib.load(warped_path).get_fdata().astype(np.float32)
        return vol
    else:
        vol = nib.load(t1_path).get_fdata().astype(np.float32)
        return vol

def build_slice_dataset(df_sub, cfg):
    """
    cfg fields:
      - slice_mode: "roi" | "whole" | "random"
      - use_registration: bool
      - use_normalization: bool
    Returns:
      X: (n_slices, H, W, 1)
      y: (n_slices,)
      sub: (n_slices,)
    """
    X_list, y_list, sub_list = [], [], []

    for _, row in df_sub.iterrows():
        sub_id = row["sub_id"]
        t1_path = row["t1_path"]
        y = int(row["y"])

        vol = load_volume(t1_path, cfg["use_registration"])
        zs = sample_z_slices(vol.shape[2], cfg["slice_mode"], k=MAX_SLICES_PER_SUBJECT, seed=SEED)

        for z in zs:
            sl = vol[:, :, z]
            if cfg["use_normalization"]:
                sl = normalize_slice(sl)
            sl = resize_slice(sl, IMG_SIZE)
            X_list.append(sl[..., None])
            y_list.append(y)
            sub_list.append(sub_id)

    return np.stack(X_list), np.array(y_list), np.array(sub_list)

def build_small_cnn(input_shape=(IMG_SIZE, IMG_SIZE, 1), lr=LR):
    inp = layers.Input(shape=input_shape)
    x = layers.Conv2D(16, 3, padding="same", activation="relu")(inp)
    x = layers.MaxPool2D()(x)
    x = layers.Conv2D(32, 3, padding="same", activation="relu")(x)
    x = layers.MaxPool2D()(x)
    x = layers.Conv2D(64, 3, padding="same", activation="relu")(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.2)(x)
    out = layers.Dense(1, activation="sigmoid")(x)

    m = models.Model(inp, out)
    m.compile(optimizer=tf.keras.optimizers.Adam(lr),
              loss="binary_crossentropy")
    return m

def aggregate_subject_probs(sub_ids, y_slice, p_slice, mode="mean"):
    dfp = pd.DataFrame({"sub_id": sub_ids, "y": y_slice, "p": p_slice})
    if mode == "mean":
        subj = dfp.groupby("sub_id").agg(y=("y","first"), p=("p","mean")).reset_index()
    elif mode == "max":
        subj = dfp.groupby("sub_id").agg(y=("y","first"), p=("p","max")).reset_index()
    else:
        raise ValueError("agg must be 'mean' or 'max'")
    return subj

def run_cv_one_config(df, cfg, n_splits=5):
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=SEED)

    y_sub = df["y"].values
    fold_rows = []
    oof_prob = np.zeros(len(df), dtype=float)

    for fold, (tr_idx, te_idx) in enumerate(skf.split(np.arange(len(df)), y_sub), 1):
        df_tr = df.iloc[tr_idx].reset_index(drop=True)
        df_te = df.iloc[te_idx].reset_index(drop=True)

        print(f"\n===== {cfg['name']} | Fold {fold} =====")
        print("Train subjects:", len(df_tr), "Test subjects:", len(df_te))

        X_tr, y_tr, sub_tr = build_slice_dataset(df_tr, cfg)
        X_te, y_te, sub_te = build_slice_dataset(df_te, cfg)

        print("Train slices:", len(y_tr), "Test slices:", len(y_te))

        model = build_small_cnn()
        cb = tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=PATIENCE, restore_best_weights=True)

        model.fit(
            X_tr, y_tr,
            validation_split=0.1,
            epochs=EPOCHS,
            batch_size=BATCH,
            callbacks=[cb],
            verbose=1
        )

        p_te = model.predict(X_te, batch_size=BATCH, verbose=0).reshape(-1)
        subj = aggregate_subject_probs(sub_te, y_te, p_te, mode=cfg["agg"])

        auc_fold = roc_auc_score(subj["y"].values, subj["p"].values)
        print(f"AUC (subject-level) fold {fold}: {auc_fold:.4f}")

        # fill OOF
        prob_map = dict(zip(subj["sub_id"].values, subj["p"].values))
        for i, r in df.iloc[te_idx].iterrows():
            oof_prob[i] = prob_map[r["sub_id"]]

        fold_rows.append({
            "config": cfg["name"],
            "fold": fold,
            "auc_subject": float(auc_fold),
            "n_test_subjects": int(len(subj)),
            "n_test_slices": int(len(y_te)),
        })

    auc_oof = roc_auc_score(df["y"].values, oof_prob)
    print(f"\n===== {cfg['name']} | FINAL OOF AUC: {auc_oof:.4f} =====")

    fold_rows.append({
        "config": cfg["name"],
        "fold": "OOF",
        "auc_subject": float(auc_oof),
        "n_test_subjects": int(len(df)),
        "n_test_slices": int(len(df) * MAX_SLICES_PER_SUBJECT),
    })

    return pd.DataFrame(fold_rows), oof_prob

CONFIGS = [
    # Full model
    dict(
        name="FULL: ROI + Reg + Norm + mean",
        slice_mode="roi",
        use_registration=True,
        use_normalization=True,
        agg="mean",
    ),

    # Ablation 1: No ROI (whole brain slices)
    dict(
        name="ABL: WholeSlices + Reg + Norm + mean",
        slice_mode="whole",
        use_registration=True,
        use_normalization=True,
        agg="mean",
    ),

    # Ablation 2: Random slices (control)
    dict(
        name="ABL: RandomSlices + Reg + Norm + mean",
        slice_mode="random",
        use_registration=True,
        use_normalization=True,
        agg="mean",
    ),

    # Ablation 3: No registration
    dict(
        name="ABL: ROI + NO-Reg + Norm + mean",
        slice_mode="roi",
        use_registration=False,
        use_normalization=True,
        agg="mean",
    ),

    # Ablation 4: No normalization
    dict(
        name="ABL: ROI + Reg + NO-Norm + mean",
        slice_mode="roi",
        use_registration=True,
        use_normalization=False,
        agg="mean",
    ),

    # Optional: aggregation variant
    dict(
        name="ABL: ROI + Reg + Norm + max",
        slice_mode="roi",
        use_registration=True,
        use_normalization=True,
        agg="max",
    ),
]

print("Configs:")
for c in CONFIGS:
    print("-", c["name"])

all_rows = []
oof_store = {}

for cfg in CONFIGS:
    df_rows, oof_prob = run_cv_one_config(df, cfg, n_splits=5)
    all_rows.append(df_rows)
    oof_store[cfg["name"]] = oof_prob

results = pd.concat(all_rows, ignore_index=True)

# Summaries
summary = (results[results["fold"].eq("OOF")]
           .sort_values("auc_subject", ascending=False)
           .reset_index(drop=True))

print("\n=== OOF Summary (sorted) ===")
print(summary[["config","auc_subject","n_test_subjects","n_test_slices"]])

# Save
OUT_CSV = "/content/drive/MyDrive/ADHD200-data/ablation_results.csv"
results.to_csv(OUT_CSV, index=False)
print("\nSaved:", OUT_CSV)

# Optional: save OOF probs for plotting later
OUT_OOF = "/content/drive/MyDrive/ADHD200-data/ablation_oof_probs.npz"
np.savez_compressed(OUT_OOF, **{k: v for k, v in oof_store.items()})
print("Saved OOF probs:", OUT_OOF)

import matplotlib.pyplot as plt

tmp = summary.copy()
plt.figure(figsize=(10, 4))
plt.bar(range(len(tmp)), tmp["auc_subject"].values)
plt.xticks(range(len(tmp)), tmp["config"].values, rotation=45, ha="right")
plt.ylabel("OOF Subject AUC")
plt.title("Ablation Study (OOF AUC)")
plt.tight_layout()
plt.show()

"""# 📊 Ablation Study Results

---

# 一、我们先看最终结果

Baseline（FULL）：

ROI + Registration + Normalization + mean aggregation  
👉 Subject-level OOF AUC = **0.5619**

接下来我们逐个拆解。

---

# 二、各个 Ablation 结果总结

| 模型配置 | OOF AUC |
|----------|---------|
| ROI + Reg + Norm + mean (FULL) | 0.5619 |
| WholeSlices + Reg + Norm + mean | 0.5651 |
| RandomSlices + Reg + Norm + mean | 0.5806 |
| ROI + NO-Reg + Norm + mean | 0.5658 |
| ROI + Reg + NO-Norm + mean | **0.6347** |
| ROI + Reg + Norm + max | 0.5951 |

---

# 三、核心观察（最重要的四个点）

## 1️⃣ 去掉 normalization，AUC 最高（0.6347）

这是最强信号。

说明：

模型可能在利用 scanner / site 强度分布差异。

因为 normalization 本来就是用来消除这种差异的。

如果去掉它反而更好，

那我们必须怀疑：

模型在走 shortcut。

---

## 2️⃣ Random slices > FULL

这非常关键。

如果随机选 slices 都可以接近甚至超过 ROI，

说明：

模型并没有真正依赖 hypothesized fronto-striatal circuit。

---

## 3️⃣ ROI vs Whole brain 几乎没差

说明：

ROI 限制并没有带来明显机制优势。

可能原因：

- ADHD 结构差异分布广泛
- 2D slice 丢失 3D 形态
- 疾病信号本身很弱

---

## 4️⃣ Registration 去不去影响不大

说明：

模型并没有强依赖精确空间对齐。

---

# 四、一个重要结论

当前结果显示：

👉 数据中的非疾病信号（site / scanner）可能比疾病信号更强。

👉 模型最“好”的版本（NO-Norm）可能是最像作弊的版本。

---

# 五、为什么 FULL 的 AUC 比以前低？

可能原因：

1. 现在使用的是严格的 subject-level OOF CV
2. 不同 fold 表现波动较大
3. normalization 抑制了 shortcut 信号
4. ROI slice 限制减少信息量

重要的是：

AUC 低 ≠ 模型失败

它可能更接近真实难度。

---

# 六、当前阶段的科学问题

“如何提高 AUC？”


“模型到底在学什么？”

为了回答这个问题，

我们需要做三件关键实验：

1️⃣ Site-only baseline  
2️⃣ Motion confound control  
3️⃣ Harmonization

---

# 七、下一步：Site-only Baseline

目的：

检测 site 信息本身是否可以预测 ADHD。

方法：

- 统计每个 site 的 ADHD 比例
- 对该 site 的被试输出该比例
- 计算 AUC

如果 site-only AUC 接近 0.56–0.60，

说明 site bias 很强。

---

# 八、下一步：Motion Confound Control

问题：

ADHD 被试通常 head motion 更严重。

motion 可能成为分类线索。

方法：

- 提取每个被试的 mean FD（framewise displacement）
- 用 motion 作为单一特征做 baseline
- 或在模型中回归掉 motion

如果 motion-only AUC 较高，

说明 motion 是强 confound。

---

# 九、下一步：Harmonization

目的：

消除多站点差异。

可选方法：

- ComBat
- Per-site z-score
- Histogram matching

然后重新训练 FULL 模型，

观察 AUC 是否变化。

如果 harmonization 后 AUC 降到 ~0.5，

说明之前主要学的是 site。

如果仍然稳定，

说明存在真实结构信号。

---

# 十、阶段总结

Ablation 的意义不是优化模型。

而是识别：

- 哪些模块真的重要？
- 哪些模块在抑制 shortcut？
- 数据中是否存在强 confound？

现在我们已经发现：

Normalization 很可能在抑制 shortcut。

下一步，我们要系统地验证这一点。

"""

import numpy as np

path = "/content/drive/MyDrive/ADHD200-data/ablation_oof_probs.npz"

data = np.load(path)

print(data.files)

print([k for k in globals().keys() if "meta" in k.lower()])
print([k for k in globals().keys() if "subject" in k.lower()])
print([k for k in globals().keys() if "df" in k.lower()])

# =========================
# 0) Mount Drive (if needed)
# =========================
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, re, glob
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

BASE_DIR = "/content/drive/MyDrive/ADHD200-data"  # 你结果保存的同目录
assert os.path.exists(BASE_DIR), f"BASE_DIR not found: {BASE_DIR}"

# =========================
# 1) Find candidate metadata files
# =========================
patterns = [
    "**/phenotypic*.csv",
    "**/Phenotypic*.csv",
    "**/*phenotypic*.csv",
    "**/participants*.tsv",
    "**/participants*.csv",
    "**/*meta*.csv",
    "**/*subject*.csv",
    "**/*phenotype*.csv",
]
cands = []
for pat in patterns:
    cands.extend(glob.glob(os.path.join(BASE_DIR, pat), recursive=True))

# de-dup & sort
cands = sorted(list(dict.fromkeys(cands)))
print("=== Candidate metadata files found ===")
for i, p in enumerate(cands[:80]):
    print(f"[{i}] {p}")
if len(cands) > 80:
    print(f"... and {len(cands)-80} more")

assert len(cands) > 0, (
    "No metadata file found under BASE_DIR.\n"
    "Please check the path or put phenotypic/participants file under this folder."
)

# =========================
# 2) Choose one file (default: first phenotypic-ish)
# =========================
# 自动挑一个最像 phenotypic 的；你也可以手动把 idx 改掉
def score_path(p: str) -> int:
    s = p.lower()
    score = 0
    if "phenotypic" in s: score += 5
    if "participants" in s: score += 3
    if s.endswith(".tsv"): score += 1
    if "adhd" in s: score += 1
    return score

best_idx = int(np.argmax([score_path(p) for p in cands]))
META_FILE = cands[best_idx]
print("\nSelected META_FILE:", META_FILE)

# =========================
# 3) Load metadata
# =========================
if META_FILE.lower().endswith(".tsv"):
    df = pd.read_csv(META_FILE, sep="\t")
else:
    df = pd.read_csv(META_FILE)

print("Loaded meta shape:", df.shape)
print("Columns:", list(df.columns)[:40])
display(df.head())

# =========================
# 4) Heuristics to detect columns: subject_id / site / label
# =========================
def find_col(cols, candidates):
    cols_low = {c.lower(): c for c in cols}
    for cand in candidates:
        if cand in cols_low:
            return cols_low[cand]
    # fuzzy contains
    for c in cols:
        cl = c.lower()
        for cand in candidates:
            if cand in cl:
                return c
    return None

# subject id candidates
subj_col = find_col(df.columns, ["subject", "subjectid", "subject_id", "sub_id", "participant_id", "scanid", "scan_id", "id"])
# site candidates
site_col = find_col(df.columns, ["site", "site_id", "center", "centre", "scanner", "institution"])
# label candidates (ADHD200常见: DX, ADHD, diagnosis, group)
label_col = find_col(df.columns, ["dx", "adhd", "diagnosis", "label", "group", "class"])

print("\nDetected columns:")
print("  subject_id:", subj_col)
print("  site      :", site_col)
print("  label     :", label_col)

# 如果自动识别失败：给出一个可读的提示（不让你“猜半天”）
assert subj_col is not None, "Could not detect subject_id column. Please set subj_col manually."
assert site_col is not None, "Could not detect site column. Please set site_col manually."
assert label_col is not None, "Could not detect label column. Please set label_col manually."

# =========================
# 5) Clean label to 0/1
# =========================
df2 = df[[subj_col, site_col, label_col]].copy()
df2.columns = ["subject_id", "site", "label_raw"]

# 把 label 变成 y=0/1
# ADHD200里常见：DX=0/1/2（0=TD, 1=ADHD-Combined, 2=ADHD-Inattentive 等）
# 我们通常做：y = (DX > 0)
lr = df2["label_raw"]

# 尝试数值化
y = pd.to_numeric(lr, errors="coerce")

if y.notna().mean() > 0.8:
    # 数值型：>0 视为 ADHD
    df2["y"] = (y.fillna(0) > 0).astype(int)
else:
    # 字符型：包含 ADHD / Patient 等算 1
    s = lr.astype(str).str.lower()
    df2["y"] = (s.str.contains("adhd|patient|case|1|true|yes")).astype(int)

df2["site"] = df2["site"].astype(str)
df2["subject_id"] = df2["subject_id"].astype(str)

print("\nLabel distribution (y):")
print(df2["y"].value_counts(dropna=False))
print("\nSites (top 20):")
print(df2["site"].value_counts().head(20))

# =========================
# 6) Recreate folds (match your ablation setting as much as possible)
# =========================
# 你之前大概率是 StratifiedKFold(5, shuffle=True, random_state=42)
N_SPLITS = 5
SEED = 42

skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)
fold = np.full(len(df2), -1, dtype=int)

for f, (_, te_idx) in enumerate(skf.split(df2["subject_id"], df2["y"]), start=1):
    fold[te_idx] = f

df2["fold"] = fold
assert (df2["fold"] > 0).all()

print("\nFold sizes:")
print(df2["fold"].value_counts().sort_index())

# =========================
# 7) Site-only baseline (OOF)
# =========================
ALPHA = 1.0  # Laplace smoothing; set 0.0 to disable

oof_pred = np.full(len(df2), np.nan, dtype=float)
fold_auc = {}

for f in sorted(df2["fold"].unique()):
    tr = df2[df2["fold"] != f]
    te = df2[df2["fold"] == f]

    global_p = tr["y"].mean()

    g = tr.groupby("site")["y"].agg(["sum", "count"]).reset_index()
    g["p_site"] = (g["sum"] + ALPHA) / (g["count"] + 2*ALPHA)
    site2p = dict(zip(g["site"], g["p_site"]))

    te_pred = te["site"].map(site2p).fillna(global_p).astype(float).values
    oof_pred[te.index.values] = te_pred

    if te["y"].nunique() < 2:
        auc = np.nan
        print(f"[Fold {f}] only one class in test; AUC undefined.")
    else:
        auc = roc_auc_score(te["y"].values, te_pred)

    fold_auc[f] = auc
    print(f"[Fold {f}] n_test={len(te):4d}  global_p={global_p:.3f}  AUC={auc:.4f}")

oof_auc = roc_auc_score(df2["y"].values, oof_pred)

print("\n===== SITE-ONLY BASELINE SUMMARY =====")
print("Fold AUCs:", {k: (None if pd.isna(v) else round(float(v), 4)) for k,v in fold_auc.items()})
print(f"FINAL OOF AUC (site-only) = {oof_auc:.4f}")

# =========================
# 8) Save for later comparison
# =========================
out_dir = BASE_DIR
os.makedirs(out_dir, exist_ok=True)

out_csv = os.path.join(out_dir, "site_only_subject_meta_with_folds_and_oof.csv")
df2.assign(pred_site_only=oof_pred).to_csv(out_csv, index=False)
print("Saved:", out_csv)

# Optional: show site prevalence table
site_prev = df2.groupby("site")["y"].mean().sort_values(ascending=False).reset_index()
display(site_prev.head(20))

# =========================
# 0) Mount Drive (if needed)
# =========================
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os, re, glob
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

BASE_DIR = "/content/drive/MyDrive/ADHD200-data"  # 你结果保存的同目录
assert os.path.exists(BASE_DIR), f"BASE_DIR not found: {BASE_DIR}"

import os, glob, re
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score

BASE_DIR = "/content/drive/MyDrive/ADHD200-data"

# 1) 收集所有站点 phenotypic（排除 TestRelease）
all_pheno = sorted(glob.glob(os.path.join(BASE_DIR, "*_phenotypic.csv")))
train_pheno = [p for p in all_pheno if "TestRelease" not in os.path.basename(p)]

print("All phenotypic:", len(all_pheno))
print("Train phenotypic (exclude TestRelease):", len(train_pheno))
for p in train_pheno:
    print(" -", os.path.basename(p))

assert len(train_pheno) > 0, "No training phenotypic files found."

# 2) 读入并合并
dfs = []
for p in train_pheno:
    d = pd.read_csv(p)
    d["__source_file__"] = os.path.basename(p)
    dfs.append(d)

df = pd.concat(dfs, ignore_index=True)
print("\nMerged meta shape:", df.shape)
print("Columns:", list(df.columns)[:30])
display(df.head())

# 3) 标准化列名（ADHD200 通常是这些）
# ScanDir ID = subject_id, Site = site, DX = label
assert "ScanDir ID" in df.columns, "Missing 'ScanDir ID' column."
assert "Site" in df.columns, "Missing 'Site' column."
assert "DX" in df.columns, "Missing 'DX' column."

df2 = df[["ScanDir ID", "Site", "DX", "__source_file__"]].copy()
df2.columns = ["subject_id", "site", "dx", "source_file"]

# 4) 清洗 label：y = 1 if dx > 0 else 0
df2["dx_num"] = pd.to_numeric(df2["dx"], errors="coerce")
df2 = df2[df2["dx_num"].notna()].copy()

df2["y"] = (df2["dx_num"] > 0).astype(int)
df2["subject_id"] = df2["subject_id"].astype(str)
df2["site"] = df2["site"].astype(str)

print("\nLabel distribution:")
print(df2["y"].value_counts())
print("\nUnique sites:", df2["site"].nunique())
print(df2["site"].value_counts().head(10))

# 5) 只保留你 ablation 实际用到的 subjects（如果你有那个列表的话）
# 你现在 ablation 的 n_test_subjects=924。我们需要让 baseline 使用同一批 subject 才可比较。
# 如果你有一个 subject list 文件（推荐你保存一下），就在这里读进来过滤。
#
# 例如你可能有：
# /content/drive/MyDrive/ADHD200-data/subjects_used_in_ablation.csv
# 里面一列 subject_id
#
# 先自动检查是否存在这个文件：
SUBJ_LIST_PATH = os.path.join(BASE_DIR, "subjects_used_in_ablation.csv")
if os.path.exists(SUBJ_LIST_PATH):
    used = pd.read_csv(SUBJ_LIST_PATH)
    # 自动找列名
    col = "subject_id" if "subject_id" in used.columns else used.columns[0]
    used_ids = set(used[col].astype(str).tolist())
    before = len(df2)
    df2 = df2[df2["subject_id"].isin(used_ids)].copy()
    print(f"\nFiltered by subjects_used_in_ablation.csv: {before} -> {len(df2)}")
else:
    print("\nNOTE: subjects_used_in_ablation.csv not found.")
    print("We will run baseline on ALL merged subjects.")
    print("If you want an apples-to-apples comparison with your FULL AUC=0.5619,")
    print("please export the subject_id list used in your ablation and save it as subjects_used_in_ablation.csv.")

# 6) 创建 folds（为了可重复，固定 random_state）
N_SPLITS = 5
SEED = 42
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)

fold = np.full(len(df2), -1, dtype=int)
for f, (_, te_idx) in enumerate(skf.split(df2["subject_id"], df2["y"]), start=1):
    fold[te_idx] = f
df2["fold"] = fold

print("\nFold sizes:")
print(df2["fold"].value_counts().sort_index())

# 7) Site-only baseline（OOF）
ALPHA = 1.0  # Laplace smoothing
oof_pred = np.full(len(df2), np.nan, dtype=float)
fold_auc = {}

for f in sorted(df2["fold"].unique()):
    tr = df2[df2["fold"] != f]
    te = df2[df2["fold"] == f]

    global_p = tr["y"].mean()
    g = tr.groupby("site")["y"].agg(["sum", "count"]).reset_index()
    g["p_site"] = (g["sum"] + ALPHA) / (g["count"] + 2*ALPHA)
    site2p = dict(zip(g["site"], g["p_site"]))

    te_pred = te["site"].map(site2p).fillna(global_p).astype(float).values
    oof_pred[te.index.values] = te_pred

    if te["y"].nunique() < 2:
        auc = np.nan
        print(f"[Fold {f}] only one class in test; AUC undefined.")
    else:
        auc = roc_auc_score(te["y"].values, te_pred)
    fold_auc[f] = auc
    print(f"[Fold {f}] n_test={len(te):4d} global_p={global_p:.3f} AUC={auc:.4f}")

# overall
if df2["y"].nunique() < 2:
    oof_auc = np.nan
else:
    oof_auc = roc_auc_score(df2["y"].values, oof_pred)

print("\n===== SITE-ONLY BASELINE SUMMARY =====")
print("Fold AUCs:", {k: (None if pd.isna(v) else round(float(v), 4)) for k,v in fold_auc.items()})
print(f"FINAL OOF AUC (site-only) = {oof_auc:.4f}")

# 8) 保存
out_csv = os.path.join(BASE_DIR, "site_only_merged_pheno_oof.csv")
df2.assign(pred_site_only=oof_pred).to_csv(out_csv, index=False)
print("Saved:", out_csv)

# 9) 站点 ADHD 比例表
site_prev = df2.groupby("site")["y"].mean().sort_values(ascending=False).reset_index()
site_prev.columns = ["site", "adhd_rate"]
display(site_prev.head(20))

"""# Site Bias 分析

刚刚得到的这个结果其实**非常关键，而且可以解释我们在 ablation study 里看到的很多“反常现象”。**

我们计算得到：

**Site-only baseline OOF AUC = 0.6864**

这意味着：

> 如果我们只知道 **MRI 来自哪个站点（site）**，  
> **完全不使用 MRI 图像信息**，  
> 仍然可以把 ADHD 和 Control 区分到 **AUC ≈ 0.69**。

在医学 AI 研究中，这通常被认为是 **非常强的 site bias（站点偏差）或 shortcut learning（捷径学习）的证据**。

---

# 1. 用最简单的话解释

一开始，我们以为模型在学习：

> ADHD 的脑结构差异。

但是现在这个实验说明：

> **只知道数据来自哪个医院，就已经可以较好地预测 ADHD。**

这说明数据集中存在一个很强的 **site bias**。

可能的原因包括：

- 不同医院的 ADHD 诊断比例不同  
- 不同站点的受试者人群不同  
- MRI 扫描仪和扫描参数不同  

因此模型可能学到的是：

> “这张 MRI 像哪个医院或扫描仪拍的”

而不是：

> “ADHD 的脑结构特征”。

---

# 数据中的证据

从我们的统计可以看到，不同站点的 ADHD 比例差异非常大：

- **site = 7** → ADHD rate = **0.0**（全部是 control）
- **site = 5** → ADHD rate ≈ **0.55**
- **site = 4** → ADHD rate ≈ **0.52**
- **site = 1** → ADHD rate ≈ **0.28**
- **site = 3** → ADHD rate ≈ **0.27**

因为这些比例差异很大，

模型只要学会：

> “识别这个 MRI 更像哪个站点”

就可以部分预测 ADHD。

这也是为什么在很多论文审稿时 reviewer 会问：

> **是否检测了 site bias？**

---

# 2. 解释 ablation study 中的两个现象

这个 site bias 其实也可以解释我们之前看到的两个现象。

---

## 为什么 NO-Norm 的 AUC 更高？

如果不做 intensity normalization，

MRI 中的扫描仪强度风格会被保留下来。

而这些风格通常是 **站点特有的**。

因此 CNN 更容易识别：

> 这个 MRI 来自哪个 scanner / 哪个 site。

"""

# 统一 merge key 的 dtype
dfb["subject_id"]  = dfb["subject_id"].astype(str)
dfb["site"]        = dfb["site"].astype(str)
dfb["y"]           = dfb["y"].astype(int)

meta["subject_id"] = meta["subject_id"].astype(str)
meta["site"]       = meta["site"].astype(str)
meta["y"]          = meta["y"].astype(int)

# 再 merge
dfm = dfb.merge(
    meta[["subject_id","site","y","sex","age"]],
    on=["subject_id","site","y"],
    how="inner"
)

print("Merged for baseline:", dfm.shape)
print(dfm[["subject_id","site","sex","age","y","fold"]].head())

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

# 读你刚保存的文件（里面已经有 subject_id, site, y, fold）
path = "/content/drive/MyDrive/ADHD200-data/site_only_merged_pheno_oof.csv"
dfb = pd.read_csv(path)

# Ensure merge keys in dfb are consistent types after loading from CSV
dfb["subject_id"] = dfb["subject_id"].astype(str)
dfb["site"] = dfb["site"].astype(str)
dfb["y"] = dfb["y"].astype(int)

# 把原始 phenotypic 再加载一次以获取 age/sex（如果你之前 df2 没保留）
# 这里简单做法：重新合并回去
# 你也可以直接用 merged df2（如果你还在同一个 cell 里）
# 我这里给一个稳健版本：重新合并需要的列
# 先重新读入各站点 phenotypic
import glob, os
BASE_DIR = "/content/drive/MyDrive/ADHD200-data"
train_pheno = [p for p in glob.glob(os.path.join(BASE_DIR, "*_phenotypic.csv")) if "TestRelease" not in os.path.basename(p)]
dfs = []
for p in train_pheno:
    d = pd.read_csv(p)
    dfs.append(d[["ScanDir ID", "Site", "Gender", "Age", "DX"]])
meta = pd.concat(dfs, ignore_index=True).copy()
meta["ScanDir ID"] = meta["ScanDir ID"].astype(str)
meta["Site"] = meta["Site"].astype(str)

meta["y"] = (pd.to_numeric(meta["DX"], errors="coerce").fillna(0) > 0).astype(int)
meta = meta.rename(columns={"ScanDir ID":"subject_id","Site":"site","Gender":"sex","Age":"age"})
meta = meta.dropna(subset=["age","sex"])

# 合并到 dfb
dfm = dfb.merge(meta[["subject_id","site","y","sex","age"]], on=["subject_id","site","y"], how="inner")
print("Merged for baseline:", dfm.shape)
print(dfm[["site","sex","age","y"]].head())

# 用相同 fold 做 OOF（如果 dfb 的 fold 是我们刚才生成的）
# 这里用 dfb 的 fold
assert "fold" in dfm.columns

X = dfm[["site","sex","age"]]
y = dfm["y"].values
folds = sorted(dfm["fold"].unique())

preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), ["site","sex"]),
        ("num", "passthrough", ["age"]),
    ]
)

model = Pipeline(steps=[
    ("prep", preprocess),
    ("clf", LogisticRegression(max_iter=2000))
])

oof = np.full(len(dfm), np.nan)
for f in folds:
    tr = dfm["fold"] != f
    te = dfm["fold"] == f
    model.fit(X.loc[tr], y[tr])
    oof[te] = model.predict_proba(X.loc[te])[:,1]
    auc = roc_auc_score(y[te], oof[te])
    print(f"[Fold {f}] AUC(site+age+sex) = {auc:.4f}")

print("FINAL OOF AUC(site+age+sex) =", roc_auc_score(y, oof))

"""# Confound Analysis：站点与人口学基线模型

在信任任何 MRI 深度学习结果之前，我们必须先回答一个非常重要的问题：

**模型究竟是在学习疾病相关的脑结构信号，还是仅仅在利用数据集中的“捷径（shortcut）”？**

为了验证这一点，我们训练了一些**极其简单的基线模型**，这些模型 **完全不使用 MRI 图像数据**。

---

# 1. 仅使用站点信息（Site-only baseline）

首先，我们训练了一个只使用 **采集站点信息（site）** 的分类模型。

也就是说，模型只知道：

**这个样本来自哪个医院 / 哪台扫描仪。**

实验结果：

**Site-only baseline AUC ≈ 0.686**

### 结果解释

这意味着：

**仅仅知道数据来自哪个站点，就可以以 AUC ≈ 0.69 的准确度预测 ADHD 或对照组。**

这表明数据集中存在明显的 **站点偏差（site bias）**。

造成这种现象的可能原因包括：

- 不同医院的 **诊断标准或患者来源不同**
- 不同 MRI 扫描仪产生 **系统性的图像差异**
- 不同站点的 **人口学结构（年龄、性别等）不同**

因此，一个使用 MRI 图像训练的模型，**很可能部分依赖的是站点相关的信号，而不是 ADHD 的真实生物学机制**。

---

# 2. 站点 + 年龄 + 性别 基线模型

接下来，我们训练了一个只使用人口学信息的模型，包括：

- Site（采集站点）
- Age（年龄）
- Sex（性别）

仍然 **完全不使用任何 MRI 图像数据**。

实验结果：

**AUC ≈ 0.78**

### 结果解释

这个结果非常重要。

仅仅依赖 **站点 + 年龄 + 性别** 这样的简单信息，就可以达到：

**AUC ≈ 0.78**

这意味着：

- 数据集的 **组成结构本身就可以强烈预测标签**
- ADHD 与对照的区分，在这个数据集中 **很大程度上由人口学和站点信息决定**
- MRI 图像中的疾病信号 **可能比这些因素更弱**

---

# 3. 与 MRI CNN 模型的对比

我们的 MRI 深度学习模型（CNN）得到的结果为：

**AUC ≈ 0.56**

这个结果 **低于所有基线模型**。

这说明：

1. ADHD 的结构性脑影像信号 **可能非常微弱**
2. 数据集中的 **站点和人口学混杂因素非常强**
3. CNN 模型 **可能难以从 MRI 中提取稳定的疾病信号**

---

# 4. 重要启示

在医学人工智能研究中：

**高准确率并不一定意味着发现了真正的生物学机制。**

模型可能利用的是各种 **数据集捷径（dataset shortcuts）**，例如：

- 站点偏差（site bias）
- 人口学不平衡（demographic imbalance）
- 扫描设备差异（scanner differences）

因此，一个严谨的医学 AI 研究通常需要包括：

- site-only baseline  
- demographic baseline  
- cross-site validation  
- confound control  
- ablation study  

这些分析的目的，是判断模型到底学到的是：

**真实的生物学信号（biology）**

还是

**数据集中的统计捷径（shortcuts）**。
"""