# -*- coding: utf-8 -*-
"""ADHD-fmri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3rqM4Q0vtwmhthNEKROdOv6jnhM1Zcj

# 🧠 第1部分：我们这节课在做什么？

今天我们要完成：

👉 用 **fMRI（功能磁共振）数据** 来判断一个人是不是 ADHD

这里有一个核心思想一定要理解：

❗我们不是在看“大脑长什么样”，而是在看——  
👉 **大脑是怎么工作的**

---

# 🧩 第2部分：MRI vs fMRI（非常关键）

在之前的课程中，我们用的是：

### 📸 结构 MRI（structural MRI）

它关注的是：

- 大脑体积
- 灰质分布
- 脑结构形态

可以把它理解为：

👉 给大脑拍一张“照片”

---

### 🎬 fMRI（functional MRI）

它关注的是：

- 哪些脑区在活动
- 哪些脑区一起活动
- 脑区之间是否同步

可以理解为：

👉 拍一段“大脑在工作的视频”

---

# 🧠 第3部分：什么是 ROI？

大脑非常复杂，如果直接分析所有数据：

👉 几万个 voxel（体素）  
👉 几乎不可能直接建模 ❌

所以我们采用一个重要方法：

👉 把大脑划分成多个“小区域”

这些区域叫：

👉 **ROI（Region of Interest）**

---

### 📍 常见 ROI 示例：

- 前额叶（负责决策、思考）
- 扣带回（注意力控制）
- 丘脑（信息中转）

---

### 🎯 为什么要用 ROI？

因为：

👉 从 **voxel → ROI = 降维**

好处是：

- 降低数据复杂度 ✅
- 更容易建模 ✅
- 更有生物学解释性 ✅

---

# ⏱ 第4部分：什么是 Time Series（时间序列）？

每个 ROI，并不是一个固定值，而是：

👉 **随时间变化的信号**

例如：
时间： 1 2 3 4 5
信号：0.2 0.5 0.3 0.6 0.4

这个就叫：

👉 **时间序列（time series）**

---

### 🧠 理解方式：

每个脑区都有一条“活动曲线”

👉 就像心电图一样

---

# 🔗 第5部分：什么是 Functional Connectivity？

这是本节课最重要的概念之一。

---

### 🧠 核心思想：

如果两个脑区：

- 同时增强
- 同时减弱

那么说明：

👉 它们在“协同工作”

---

### 📊 如何量化？

使用：

👉 **相关系数（correlation）**

结果解释：

- 接近 1 → 强正相关（一起动）
- 接近 0 → 无关系
- 接近 -1 → 反相关（一个动，一个不动）

---

### 🎯 最终得到：

一个矩阵：
   
ROI1 1 0.6 0.2

ROI2 0.6 1 0.4

ROI3 0.2 0.4 1


这个叫：

👉 **功能连接矩阵（functional connectivity matrix）**

---

# 🧩 第6部分：把大脑变成一张图（Graph）

现在我们做一个关键转换：

👉 把大脑表示成“网络”

---

### 🧠 转换规则：

- 每个 ROI → 一个节点（node）
- ROI之间的相关性 → 一条边（edge）

---

### 🌐 直观理解：

- 脑区 = 城市  
- 连接 = 城市之间的交通

---

### 🎯 结论：

👉 大脑 = 一张图（Graph）

---

# 🤖 第7部分：为什么要用 GNN？

---

### ❌ 传统模型的问题：

- CNN → 适合图像（规则网格）
- 但脑网络不是规则结构 ❌

---

### ✅ GNN（图神经网络）的优势：

它可以：

- 学习节点之间的关系
- 利用网络结构信息
- 捕捉“连接模式”

---

### 🎯 一句话总结：

- CNN：看“像不像图像”
- GNN：看“节点怎么连接”

---

# ⚠️ 第8部分：一个非常关键的问题（重点坑）

在真实数据中会遇到一个严重问题：

---

### ❌ 错误情况：

不同人的脑图：

- 有的人 48 个 ROI
- 有的人 46 个 ROI
- 有的人 50 个 ROI

结果：

👉 模型无法训练  
👉 数据大量被丢弃（例如 216 → 32）

---

### ✅ 正确做法：

必须保证：

- 所有人使用同一套 ROI
- 节点数量固定
- 不删除节点
- 缺失值（NaN）用 0 填充

---

### 🎯 关键结论：

👉 **Graph 的定义，比模型本身更重要**

---

# 🚀 第9部分：完整 Pipeline

我们整个任务流程是：

---

### Step 1  
提取每个 ROI 的时间序列

### Step 2  
计算 ROI 之间的相关性（connectivity）

### Step 3  
构建脑网络（graph）

### Step 4  
用 GNN 进行分类（ADHD vs Control）

---

# 📊 第10部分：模型结果如何理解？

我们使用一个指标：

👉 **AUC（Area Under Curve）**

---

### 📈 AUC解释：

- 0.5 → 随机猜
- 0.6 → 很弱
- 0.7 → 有用
- 0.8 → 很强
- 0.9 → 非常强

---

# 💣 第11部分：真正的科学问题（最重要）

我们必须思考：

👉 模型到底学到了什么？

---

### ✅ 理想情况：

模型学到：

👉 ADHD 的真实脑机制

---

### ❌ 危险情况：

模型学到：

👉 **site bias（医院差异）**

---

### 🧠 为什么会有这个问题？

因为：

- 不同医院设备不同
- ADHD比例不同
- 扫描方式不同

---

### 🎯 下一步必须做：

👉 **site-only baseline**

验证：

👉 模型有没有“作弊”

---

# 🎓 最终总结

---

### 🧠 1. MRI vs fMRI

- MRI → 结构
- fMRI → 活动

---

### 🧠 2. 大脑是一个网络

- ROI = 节点
- connectivity = 边

---

### 🧠 3. GNN 的作用

👉 学习脑区之间的关系

---

### 🧠 4. 最关键的一点

❗**数据表示（graph）比模型更重要**

# 1. 环境准备与依赖安装
本单元格负责安装处理神经影像（nilearn, nibabel）和构建图神经网络（torch-geometric）所需的 Python 库。
"""

import torch
import platform

!pip -q install --upgrade nilearn nibabel scikit-learn tqdm matplotlib seaborn

# Get PyTorch version for torch-geometric installation
torch_version_str = torch.__version__.split('+')[0]

# Determine CUDA version if available, otherwise fallback to CPU
cuda_version_str = ''
if torch.cuda.is_available():
    cuda_version_str = "cu" + torch.version.cuda.replace('.', '')
else:
    # Fallback to CPU if CUDA not available or torch.version.cuda is None
    # For PyG, if no CUDA version specified, it often defaults to CPU if no GPU is found
    pass

# Construct PyG index URL. If cuda_version_str is empty, it will default to CPU wheels.
pyg_url = f"https://data.pyg.org/whl/torch-{torch_version_str}{'+' + cuda_version_str if cuda_version_str else ''}.html"

# Install torch-scatter, torch-sparse, torch-cluster, torch-spline-conv, and torch-geometric
# using the constructed index URL.
!pip -q install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f {pyg_url}

# Install specific pandas version
!pip -q install pandas==2.2.2

"""# 2. 库导入与基础配置
导入数据处理、可视化和深度学习所需的各种核心库，并配置全局路径和警告过滤。

# 3. 挂载 Google Drive
将 Google Drive 挂载到 Colab 环境，以便访问存储在云端的 ADHD-200 原始数据集。

# 4. 扫描 BIDS 结构下的 fMRI 影像
遍历数据集目录，提取所有符合 BIDS 标准的静息态 fMRI（ses-1）影像路径。这是构建数据清单（Manifest）的第一步。

# 5. 读取并标准化标签数据
从 `participants.tsv` 中读取被试的临床信息（如诊断 dx、年龄、性别），并将其标准化为二进制标签（0 代表对照组，1 代表 ADHD）。

# 6. 数据流失分析与智能标签找回
由于 ID 格式不匹配等原因，初次合并可能导致大量样本流失。此单元格通过扫描外部表型文件（CSV）并提取 ID 数字进行二次匹配，最大程度恢复流失的 NYU 和 Pittsburgh 站点样本。

# 7. 生成最终分析清单
将所有来源的标签汇总，创建最终的 `fmri_manifest.csv`。这是后续所有 ROI 提取和 GNN 训练的唯一数据入口。

# 8. NYU 站点 GNN 模型训练（维度固定版）
针对 NYU 站点，利用 Harvard-Oxford 图谱提取 ROI 信号并构建脑网络图。此版本强制要求所有被试拥有相同的 48 个节点维度，以确保 GNN Batch 训练的稳定性。
"""

import os
import re
import gc
import glob
import json
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import nibabel as nib
import matplotlib.pyplot as plt

from tqdm import tqdm
from google.colab import drive

from nilearn import image, plotting, datasets, masking
from nilearn.input_data import NiftiLabelsMasker
from nilearn.connectome import ConnectivityMeasure
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

drive.mount('/content/drive')

import os
import pandas as pd
from tqdm import tqdm

ROOT_DIR = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"

rows = []

for site in tqdm(sorted(os.listdir(ROOT_DIR))):
    site_path = os.path.join(ROOT_DIR, site)

    if not os.path.isdir(site_path):
        continue

    for sub in os.listdir(site_path):
        if not sub.startswith("sub-"):
            continue

        sub_path = os.path.join(site_path, sub)

        for root, dirs, files in os.walk(sub_path):
            for f in files:

                # 只要 fMRI
                if not (f.endswith(".nii.gz") and "bold" in f and "rest" in f):
                    continue

                full_path = os.path.join(root, f)

                # 🔥 关键：只保留 ses-1
                if "ses-1" not in f and "ses-1" not in full_path:
                    continue

                rows.append({
                    "site": site,
                    "subject_id": sub,
                    "fmri_path": full_path,
                    "filename": f
                })

fmri_df = pd.DataFrame(rows)

print("总扫描到的 fMRI:", len(fmri_df))
fmri_df.head()

fmri_df = (
    fmri_df
    .sort_values("fmri_path")
    .drop_duplicates(subset=["site", "subject_id"], keep="first")
    .reset_index(drop=True)
)

print("去重后被试数:", len(fmri_df))

site_counts = fmri_df.groupby("site")["subject_id"].nunique().sort_values(ascending=False)

print("每个 site 的被试数量：")
display(site_counts)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
site_counts.plot(kind="bar")
plt.title("Number of subjects per site (ses-1 only)")
plt.ylabel("Number of subjects")
plt.xticks(rotation=45)
plt.show()

# ===============================
# fMRI manifest + site ADHD比例统计（完整版）
# ===============================

import os
import glob
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

# ========= 路径 =========
ROOT_DIR = "/content/drive/MyDrive/ADHD200-data/RawDataBIDS"
OUT_DIR = "/content/drive/MyDrive/ADHD200_fMRI_outputs"
os.makedirs(OUT_DIR, exist_ok=True)

print("ROOT_DIR =", ROOT_DIR)

# ===============================
# 1️⃣ 扫描 fMRI（只保留 ses-1）
# ===============================
rows = []

for site in tqdm(sorted(os.listdir(ROOT_DIR)), desc="Scanning fMRI"):
    site_path = os.path.join(ROOT_DIR, site)

    if not os.path.isdir(site_path):
        continue

    for sub in os.listdir(site_path):
        if not sub.startswith("sub-"):
            continue

        sub_path = os.path.join(site_path, sub)

        pattern = os.path.join(sub_path, "ses-1", "func", "*rest*bold.nii.gz")
        files = sorted(glob.glob(pattern))

        for fp in files:
            rows.append({
                "site": site,
                "subject_id": sub,
                "fmri_path": fp
            })

fmri_manifest = pd.DataFrame(rows)

print("\n原始 fMRI 数量:", len(fmri_manifest))

# 去重（每个被试只保留一个）
fmri_manifest = (
    fmri_manifest
    .sort_values(["site", "subject_id", "fmri_path"])
    .drop_duplicates(subset=["site", "subject_id"], keep="first")
    .reset_index(drop=True)
)

print("去重后被试数:", len(fmri_manifest))

# ===============================
# 2️⃣ 读取 participants.tsv
# ===============================
def read_participants(site_path):
    fp = os.path.join(site_path, "participants.tsv")
    if os.path.exists(fp):
        try:
            df = pd.read_csv(fp, sep="\t", encoding='utf-8')
        except UnicodeDecodeError:
            print(f"[WARN] UnicodeDecodeError with utf-8 for {site_path}, trying latin1")
            df = pd.read_csv(fp, sep="\t", encoding='latin1')
        return df
    return None

label_rows = []

for site in tqdm(sorted(os.listdir(ROOT_DIR)), desc="Reading labels"):
    site_path = os.path.join(ROOT_DIR, site)

    if not os.path.isdir(site_path):
        continue

    df = read_participants(site_path)

    if df is None:
        print(f"[WARN] no participants.tsv for {site}")
        continue

    df["site"] = site
    label_rows.append(df)

label_df = pd.concat(label_rows, ignore_index=True)

print("\nlabel_df shape:", label_df.shape)

# ===============================
# 3️⃣ 标准化字段
# ===============================
def normalize_subject_id(x):
    x = str(x).strip()
    x = x.replace("_", "-")
    if not x.startswith("sub-"):
        x = f"sub-{x}"
    return x

def normalize_label(dx):
    if pd.isna(dx):
        return np.nan

    s = str(dx).strip().lower()

    # 映射逻辑：TDC 为 0，各种 ADHD 类型为 1
    mapping = {
        "0": 0,
        "1": 1,
        "2": 1,
        "3": 1,
        "control": 0,
        "tdc": 0,
        "typically developing children": 0,
        "healthy": 0,
        "adhd": 1,
        "adhd-combined": 1,
        "adhd-inattentive": 1,
        "adhd-hyperactive/impulsive": 1,
        "case": 1
    }

    if s in mapping:
        return mapping[s]

    try:
        v = float(s)
        if v == 0:
            return 0
        elif v in [1, 2, 3]:
            return 1
    except:
        pass

    return np.nan

label_std = pd.DataFrame()
label_std["subject_id"] = label_df["participant_id"].map(normalize_subject_id)
label_std["site"] = label_df["site"]
label_std["age"] = label_df["age"] if "age" in label_df.columns else np.nan

if "gender" in label_df.columns:
    label_std["sex"] = label_df["gender"]
elif "sex" in label_df.columns:
    label_std["sex"] = label_df["sex"]
else:
    label_std["sex"] = np.nan

if "dx" in label_df.columns:
    label_std["label"] = label_df["dx"].map(normalize_label)
else:
    label_std["label"] = np.nan

# ===============================
# 4️⃣ merge fMRI + label
# ===============================
fmri_manifest["subject_id"] = fmri_manifest["subject_id"].map(normalize_subject_id)

manifest = fmri_manifest.merge(
    label_std[["subject_id", "label", "age", "sex"]],
    on="subject_id",
    how="left"
)

print("\n合并后有标签样本数:", manifest["label"].notna().sum())
manifest.to_csv(os.path.join(OUT_DIR, "fmri_manifest_with_labels.csv"), index=False)

# ===============================
# 5️⃣ 统计与展示
# ===============================
df_valid = manifest.dropna(subset=["label"])
site_stats = (
    df_valid
    .groupby("site")
    .agg(
        n_total=("subject_id", "count"),
        n_adhd=("label", lambda x: (x == 1).sum()),
        n_control=("label", lambda x: (x == 0).sum())
    )
)

if not site_stats.empty:
    site_stats["adhd_rate"] = site_stats["n_adhd"] / site_stats["n_total"]
    site_stats = site_stats.sort_values("adhd_rate", ascending=False)
    print("\n=== 每个 site 的 ADHD 比例 ===")
    display(site_stats)

    plt.figure(figsize=(10,5))
    site_stats["adhd_rate"].sort_values().plot(kind="barh")
    plt.xlabel("ADHD proportion")
    plt.title("ADHD prevalence per site (ses-1)")
    plt.show()

# 检查原始数据中的 dx 列到底有哪些不同的值
if 'label_df' in globals():
    if 'dx' in label_df.columns:
        print("原始 dx 列的唯一值分布：")
        display(label_df['dx'].value_counts(dropna=False))

        print("\n前 5 行示例：")
        display(label_df[['participant_id', 'dx', 'site']].head())
    else:
        print("错误：label_df 中没有找到 'dx' 列。可用列名为：", label_df.columns.tolist())
else:
    print("错误：label_df 变量不存在，请确保之前的单元格已运行。")

import pandas as pd

# 1. 检查各站点的匹配情况
loss_stats = []
for site in fmri_manifest['site'].unique():
    total_fmri = len(fmri_manifest[fmri_manifest['site'] == site])
    site_labels = label_std[label_std['site'] == site]
    matched_labels = manifest[(manifest['site'] == site) & (manifest['label'].notna())]

    loss_stats.append({
        'site': site,
        'fMRI_subjects': total_fmri,
        'With_Labels': len(matched_labels),
        'Loss_Count': total_fmri - len(matched_labels),
        'Loss_Rate': f"{(total_fmri - len(matched_labels))/total_fmri:.1%}"
    })

df_loss = pd.DataFrame(loss_stats).sort_values('Loss_Count', ascending=False)
print("=== 各站点数据流失详情 ===")
display(df_loss)

# 2. 检查 ID 匹配示例（针对流失严重的站点）
print("\n=== ID 匹配检查 (以流失最多的站点为例) ===")
worst_site = df_loss.iloc[0]['site']
print(f"站点: {worst_site}")
print("fMRI 文件夹中的 ID 示例:", fmri_manifest[fmri_manifest['site'] == worst_site]['subject_id'].iloc[:3].tolist())
print("participants.tsv 中的 ID 示例:", label_df[label_df['site'] == worst_site]['participant_id'].iloc[:3].tolist())

import pandas as pd
import matplotlib.pyplot as plt

# 1. 统计原始 fMRI 数量
original_stats = fmri_manifest.groupby('site')['subject_id'].nunique().rename('Original_fMRI')

# 2. 统计最终留下的有标签数量
final_counts = final_export.groupby('site').size().rename('Final_With_Labels')

# 3. 合并对比
analysis_df = pd.concat([original_stats, final_counts], axis=1).fillna(0).astype(int)
analysis_df['Loss_Count'] = analysis_df['Original_fMRI'] - analysis_df['Final_With_Labels']
analysis_df['Retention_Rate'] = (analysis_df['Final_With_Labels'] / analysis_df['Original_fMRI'] * 100).round(1).astype(str) + '%'
analysis_df['Loss_Rate'] = ((1 - analysis_df['Final_With_Labels'] / analysis_df['Original_fMRI']) * 100).round(1).astype(str) + '%'

print("=== 各站点数据流失与留存最终统计 ===")
display(analysis_df.sort_values('Original_fMRI', ascending=False))

# 4. 可视化对比
analysis_df[['Original_fMRI', 'Final_With_Labels']].sort_values('Original_fMRI').plot(kind='barh', figsize=(10, 6))
plt.title('Data Retention: Original fMRI vs Final Labeled Subjects')
plt.xlabel('Number of Subjects')
plt.legend(['Original Folders', 'Final with Labels'])
plt.tight_layout()
plt.show()

import os
import pandas as pd

# 1. 定义新的输出目录
FMRI_OUT_DIR = "/content/drive/MyDrive/ADHD200-data/fmri"
os.makedirs(FMRI_OUT_DIR, exist_ok=True)

# 2. 将最终的 794 个样本保存到该目录下
# 使用之前生成的 final_export 变量
manifest_path = os.path.join(FMRI_OUT_DIR, "fmri_manifest.csv")
final_export.to_csv(manifest_path, index=False)

print(f"成功创建文件夹: {FMRI_OUT_DIR}")
print(f"最终清单已保存至: {manifest_path}")
print(f"样本总数: {len(final_export)}")

# 预览保存的内容
display(final_export.head())

import pandas as pd
import os

# 读取最终清单
final_path = os.path.join(OUT_DIR, "final_adhd_manifest.csv")
if os.path.exists(final_path):
    df_final = pd.read_csv(final_path)

    # 统计各站点的标签分布
    counts_table = df_final.groupby(['site', 'final_label']).size().unstack(fill_value=0)

    # 重命名列增加可读性
    counts_table.columns = ['Control (0.0)', 'ADHD (1.0)']
    counts_table['Total'] = counts_table.sum(axis=1)

    # 按总数降序排列
    counts_table = counts_table.sort_values('Total', ascending=False)

    print("=== 各站点 ADHD / Control 样本统计 ===")
    display(counts_table)

    # 打印总计
    print(f"\n所有站点总计: ADHD={counts_table['ADHD (1.0)'].sum()}, Control={counts_table['Control (0.0)'].sum()}, 总样本={len(df_final)}")
else:
    print(f"错误：找不到文件 {final_path}")

import pandas as pd

# 1. 获取 NYU 原始文件夹中的 41 个未匹配 ID
nyu_all = fmri_manifest[fmri_manifest['site'] == 'NYU']
nyu_matched_ids = final_export[final_export['site'] == 'NYU']['subject_id'].tolist()
nyu_unmatched_ids = nyu_all[~nyu_all['subject_id'].isin(nyu_matched_ids)]['subject_id'].unique()

print(f"正在 TSV 汇总表 (label_df) 中检索这 {len(nyu_unmatched_ids)} 个 ID...")

# 2. 在 label_df 中过滤出 NYU 站点的记录
nyu_tsv_records = label_df[label_df['site'] == 'NYU'].copy()

# 3. 尝试多种匹配方式（原始 ID，数字 ID）
def get_nums(x): return re.findall(r'\d+', str(x))[-1] if re.findall(r'\d+', str(x)) else ""

unmatched_nums = [get_nums(i) for i in nyu_unmatched_ids]

# 检查 label_df 里的 participant_id 是否包含这些数字
nyu_tsv_records['tmp_num'] = nyu_tsv_records['participant_id'].apply(get_nums)

found_in_tsv = nyu_tsv_records[nyu_tsv_records['tmp_num'].isin(unmatched_nums)]

print(f"\n在 participants.tsv 中找到匹配记录数: {len(found_in_tsv)}")

if len(found_in_tsv) > 0:
    print("\n这些被试在 TSV 中的诊断信息 (dx/DX) 分布：")
    dx_col = 'dx' if 'dx' in found_in_tsv.columns else 'DX'
    display(found_in_tsv[['participant_id', dx_col]].head(10))
    print("\n诊断列空值统计:")
    print(found_in_tsv[dx_col].value_counts(dropna=False))
else:
    print("\n结论：这 41 个被试在 NYU 站点的 participants.tsv 文件中同样没有任何记录。")

import pandas as pd

# 1. 找出 NYU 站点中，依然没有匹配到 label 的 subject_id
nyu_all = fmri_manifest[fmri_manifest['site'] == 'NYU']
nyu_matched_ids = final_export[final_export['site'] == 'NYU']['subject_id'].tolist()
nyu_unmatched = nyu_all[~nyu_all['subject_id'].isin(nyu_matched_ids)]

print(f"NYU 未匹配样本数: {len(nyu_unmatched)}")
print("未匹配 ID 示例:", nyu_unmatched['subject_id'].head(10).tolist())

# 2. 检查这些 ID 的数字部分是否出现在表型库中
unmatched_nums = nyu_unmatched['match_id'].unique()
pheno_nums = all_pheno['match_id'].unique()

# 在表型库中尝试寻找这些数字
found_in_pheno = [n for n in unmatched_nums if n in pheno_nums]

print(f"\n在表型库中能找到 ID 数字但没匹配上的数量: {len(found_in_pheno)}")

if len(found_in_pheno) > 0:
    print("匹配失败的潜在原因：可能是这些 ID 在表型库中对应的 DX 列为 NaN 或 Pending。")
    display(all_pheno[all_pheno['match_id'].isin(found_in_pheno)][['match_id', 'DX', 'site_from_file']].head())
else:
    print("结论：这 41 个被试在提供的所有 .csv 表型文件中均不存在记录（彻底缺失）。")

import pandas as pd

# 重点检查 Brown 和 WashU
problem_sites = ['Brown', 'WashU']

for site in problem_sites:
    print(f"\n=== 诊断站点: {site} ===")

    # 1. 获取文件夹里的 ID
    folder_ids = fmri_manifest[fmri_manifest['site'] == site]['subject_id'].unique()
    print(f"fMRI 文件夹中的 ID 数量: {len(folder_ids)}")
    if len(folder_ids) > 0:
        print(f"示例: {folder_ids[:3].tolist()}")

    # 2. 检查外部表型总表 (all_pheno) 中是否有该站点的痕迹
    # 注意：有些表可能没写 site 名字，我们通过 match_id 模糊查一下
    site_in_pheno = all_pheno[all_pheno['Site'].astype(str).str.contains(site, case=False, na=False)]
    if len(site_in_pheno) == 0:
        # 尝试通过文件名查找
        site_in_pheno = all_pheno[all_pheno['site_from_file'].str.contains(site, case=False, na=False)]

    print(f"表型文件中匹配到的行数: {len(site_in_pheno)}")

    if len(site_in_pheno) > 0:
        print(f"表型文件中的 ID 示例: {site_in_pheno['match_id'].iloc[:3].tolist()}")
        print(f"DX 列的分布: {site_in_pheno['DX'].value_counts(dropna=False).to_dict()}")
    else:
        print("警告：在所有加载的 .csv 文件中均未发现该站点的记录。")

# 检查是否存在未被加载的相关文件
print("\n=== 目录文件检查 ===")
all_files = os.listdir(PHENO_DIR)
brown_files = [f for f in all_files if 'Brown' in f]
washu_files = [f for f in all_files if 'WashU' in f]
print(f"包含 'Brown' 的文件: {brown_files}")
print(f"包含 'WashU' 的文件: {washu_files}")

# 1. 整合 BIDS 扫描结果 (manifest) 与 外部文件找回结果 (final_manifest)
final_combined = final_manifest.copy()

# 如果 final_label 缺失，则尝试用 manifest 中的 label 补全
if 'label' in manifest.columns:
    final_combined['final_label'] = final_combined['clean_label'].fillna(manifest['label'])
else:
    final_combined['final_label'] = final_combined['clean_label']

# 2. 清洗最终表格，只保留需要的列
final_export = final_combined[[
    'site', 'subject_id', 'fmri_path', 'final_label'
]].dropna(subset=['final_label'])

# 3. 统计最终各站点数量
final_stats = final_export.groupby(['site', 'final_label']).size().unstack(fill_value=0)
final_stats['Total'] = final_stats.sum(axis=1)
final_stats['ADHD_Rate'] = final_stats[1] / final_stats['Total']

print(f"最终可用样本总数: {len(final_export)}")
display(final_stats.sort_values('Total', ascending=False))

# 4. 保存最终清单
final_path = os.path.join(OUT_DIR, "final_adhd_manifest.csv")
final_export.to_csv(final_path, index=False)
print(f"\n清单已保存至: {final_path}")

import os
import pandas as pd
import re

# 1. 指定父目录中发现的所有表型文件
PHENO_DIR = "/content/drive/MyDrive/ADHD200-data/"
pheno_files = [
    'KKI_phenotypic.csv', 'Brown_TestRelease_phenotypic.csv',
    'Pittsburgh_phenotypic.csv', 'NYU_phenotypic.csv',
    'NeuroIMAGE_phenotypic.csv', 'OHSU_phenotypic.csv',
    'OHSU_TestRelease_phenotypic.csv', 'Peking_1_phenotypic.csv',
    'Peking_1_TestRelease_phenotypic.csv'
]

# 2. 定义智能 ID 提取函数
def extract_num(sub_id):
    if pd.isna(sub_id): return ""
    nums = re.findall(r'\d+', str(sub_id))
    return nums[-1].lstrip('0') if nums else ""

# 3. 加载并整合所有外部标签
extra_label_list = []
for f in pheno_files:
    path = os.path.join(PHENO_DIR, f)
    if os.path.exists(path):
        df_tmp = pd.read_csv(path, encoding='latin1')
        # 统一 ID 列名
        id_col = 'ID' if 'ID' in df_tmp.columns else ('ScanDir ID' if 'ScanDir ID' in df_tmp.columns else df_tmp.columns[0])
        df_tmp['match_id'] = df_tmp[id_col].apply(extract_num)
        extra_label_list.append(df_tmp)

all_pheno = pd.concat(extra_label_list, ignore_index=True)

# 4. 对现有的 fmri_manifest 进行匹配
fmri_manifest['match_id'] = fmri_manifest['subject_id'].apply(extract_num)

# 映射 dx (根据之前确认的逻辑)
def map_dx(x):
    s = str(x).lower()
    if 'typically' in s or 'control' in s or s == '0': return 0
    if 'adhd' in s or s in ['1', '2', '3']: return 1
    return np.nan

all_pheno['clean_label'] = all_pheno['DX'].apply(map_dx) if 'DX' in all_pheno.columns else np.nan

# 执行合并
final_manifest = fmri_manifest.merge(
    all_pheno[['match_id', 'clean_label']].dropna().drop_duplicates('match_id'),
    on='match_id',
    how='left'
)

# 如果 clean_label 没匹配上，保留原有的 label (如果有的话)
if 'label' in manifest.columns:
    final_manifest['final_label'] = final_manifest['clean_label'].fillna(manifest['label'])
else:
    final_manifest['final_label'] = final_manifest['clean_label']

print(f"最终找回标签的样本总数: {final_manifest['final_label'].notna().sum()}")
display(final_manifest.groupby('site')['final_label'].count())

import os
import pandas as pd
import re
import numpy as np

# 1. 指定父目录中发现的所有表型文件
PHENO_DIR = "/content/drive/MyDrive/ADHD200-data/"
pheno_files = [
    'KKI_phenotypic.csv', 'Brown_TestRelease_phenotypic.csv',
    'Pittsburgh_phenotypic.csv', 'NYU_phenotypic.csv',
    'NeuroIMAGE_phenotypic.csv', 'OHSU_phenotypic.csv',
    'OHSU_TestRelease_phenotypic.csv', 'Peking_1_phenotypic.csv',
    'Peking_1_TestRelease_phenotypic.csv'
]

# 2. 定义智能 ID 提取函数
def extract_num(sub_id):
    if pd.isna(sub_id): return ""
    nums = re.findall(r'\d+', str(sub_id))
    return nums[-1].lstrip('0') if nums else ""

# 3. 加载并整合所有外部标签
extra_label_list = []
for f in pheno_files:
    path = os.path.join(PHENO_DIR, f)
    if os.path.exists(path):
        df_tmp = pd.read_csv(path, encoding='latin1')
        # 统一 ID 列名
        id_col = 'ID' if 'ID' in df_tmp.columns else ('ScanDir ID' if 'ScanDir ID' in df_tmp.columns else df_tmp.columns[0])
        df_tmp['match_id'] = df_tmp[id_col].apply(extract_num)
        df_tmp['site_from_file'] = f.split('_')[0]
        extra_label_list.append(df_tmp)

all_pheno = pd.concat(extra_label_list, ignore_index=True)

# 4. 对现有的 fmri_manifest 进行匹配
fmri_manifest['match_id'] = fmri_manifest['subject_id'].apply(extract_num)

# 映射 dx (根据之前确认的逻辑)
def map_dx(x):
    s = str(x).lower().strip()
    if any(k in s for k in ['typically', 'control', '0', 'tdc', 'healthy']):
        return 0
    if any(k in s for k in ['adhd', '1', '2', '3', 'case']):
        return 1
    return np.nan

# 尝试从 DX 或 dx 列提取标签
dx_col = 'DX' if 'DX' in all_pheno.columns else ('dx' if 'dx' in all_pheno.columns else None)
if dx_col:
    all_pheno['clean_label'] = all_pheno[dx_col].apply(map_dx)
else:
    all_pheno['clean_label'] = np.nan

# 执行合并
final_manifest = fmri_manifest.merge(
    all_pheno[['match_id', 'clean_label']].dropna().drop_duplicates('match_id'),
    on='match_id',
    how='left'
)

print(f"最终找回标签的样本总数: {final_manifest['clean_label'].notna().sum()}")
print("\n各站点匹配到的标签数量:")
display(final_manifest.groupby('site')['clean_label'].count())

import os
import pandas as pd
import glob

def search_extra_phenotypic(site_path):
    # 寻找可能的表型文件
    patterns = ['*.csv', '*phenotypic*', '*clinical*', '*.xls*']
    found_files = []
    for p in patterns:
        found_files.extend(glob.glob(os.path.join(site_path, p)))
    return list(set(found_files))

print("正在尝试从额外文件中恢复标签...")

extra_dfs = []
for site in tqdm(fmri_manifest['site'].unique()):
    site_path = os.path.join(ROOT_DIR, site)
    extra_files = search_extra_phenotypic(site_path)

    for ef in extra_files:
        try:
            if ef.endswith('.csv'):
                tmp = pd.read_csv(ef, encoding='latin1')
            else:
                tmp = pd.read_excel(ef)

            tmp['source_file'] = os.path.basename(ef)
            tmp['site'] = site
            extra_dfs.append(tmp)
        except:
            continue

if extra_dfs:
    all_extra_labels = pd.concat(extra_dfs, ignore_index=True, sort=False)
    print(f"找到额外数据行数: {len(all_extra_labels)}")
    display(all_extra_labels.head(2))
else:
    print("未找到额外的表型文件。")

# 针对 NYU 等站点的特殊匹配逻辑
def try_match_nyu(sub_id):
    # 提取 sub-0010001 中的最后几位，或者根据 NYU 的特定规则转换
    # NYU 的文件夹 ID 往往包含特定的偏移量
    import re
    match = re.search(r'(\d+)', sub_id)
    return match.group(0) if match else sub_id

# 这里可以根据观察到的 NYU ID 规律进一步优化匹配逻辑
print("准备执行跨表智能合并...")

import nilearn
print(f"nilearn version: {nilearn.__version__}")

"""代码跑通了，但当前图构建阶段丢样本非常严重。

你现在的关键信息是：

NYU 原本有 216 个有标签被试
最后可用于 GNN 的 graph 只有 32
而且你日志里出现了：
Final usable graphs with consistent dimension (48): 32

这句话基本已经暴露核心问题：

问题不是训练，而是“图维度不一致”

也就是说，你现在在构图时要求：

所有 graph 必须有相同节点数
你这里最后统一成了 48 个节点

但很多被试没有满足这个条件，所以被丢掉了。

这代表什么

在 fMRI ROI-guided GNN 里，最常见的坑就是：

1. 不同被试提取出的 ROI 数不同

原因通常是：

atlas 某些 ROI 在该被试上没有有效信号
masker 输出维度不稳定
有些 ROI 全 0 / NaN 被你后处理时删掉了
2. 你在 graph construction 时做了“动态删点”

例如：

去掉全 0 ROI
去掉 NaN ROI
只保留有边的节点

这样每个 graph 的节点数就变了，最后 GNN 只能保留一小部分“维度一致”的样本。

先别急着看训练 loss

你现在这 10 个 epoch 的 loss：

0.71 → 0.64 左右

只能说明模型在这 32 个样本 上开始拟合了。
但这个结果还不能拿来讲效果，因为样本太少，而且可能有选择偏差。

现在最该做的不是继续训练，而是：

先修 graph construction，让 216 个样本尽量都能保留下来

正确方向：固定节点集合，不允许每个被试删 ROI

在单站点 ROI-guided GNN 里，最稳的做法是：

每个被试都强制使用同一套 ROI

比如 Harvard-Oxford cortical atlas 的全部 ROI。

然后：

节点数固定
节点顺序固定
不因为某个 ROI 信号弱就删节点
NaN 用 0 填
连边规则也固定

这样每个 graph 的维度就一致了。

虽然 GNN 已经能跑起来了，但真实数据分析里，第一版模型通常不会直接成功。

这里的主要问题不是模型结构，而是输入图的标准化。

如果不同被试的脑网络节点数不一样，那么 GNN 的输入就不一致，很多样本会被迫丢弃。

所以下一步我们要做的不是盲目调模型，而是先把 graph representation 规范化。
"""

import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import torch
import torch.nn.functional as F
from torch.nn import Linear

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score

from nilearn import datasets
from nilearn.maskers import NiftiLabelsMasker
from nilearn.connectome import ConnectivityMeasure

from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GCNConv, global_mean_pool

# ===== 路径 =====
BASE_DIR = "/content/drive/MyDrive/ADHD200-data/fmri"
manifest = pd.read_csv(os.path.join(BASE_DIR, "fmri_manifest.csv"))

# ===== 只取 NYU =====
df = manifest[manifest["site"] == "NYU"].copy()
df = df.dropna(subset=["fmri_path", "final_label"])
df["final_label"] = df["final_label"].astype(int)

df = df.sort_values(["subject_id", "fmri_path"]).drop_duplicates("subject_id")
df = df[df["fmri_path"].map(os.path.exists)]

print("NYU usable:", len(df))

# ===== 加载 atlas =====
atlas_cort = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
# Get actual ROI labels, excluding 'Background' (label 0)
# The Harvard-Oxford cortical atlas has 48 regions, so we exclude the background label.
roi_labels_names = [label for label in atlas_cort.labels if label != 'Background']
target_roi_count = len(roi_labels_names) # Should be 48

# ===== masker（关键：固定 ROI）=====
masker = NiftiLabelsMasker(
    labels_img=atlas_cort.maps,
    labels=roi_labels_names, # Explicitly pass the list of ROI names to extract
    standardize=True,
    detrend=True
    # Setting ensure_finite to True ensures NaNs become 0s in time series
    # This helps guarantee fixed output dimensions even if some ROIs have no signal.
    # ensure_finite=True # Removed this line to fix the TypeError
)

conn = ConnectivityMeasure(kind="correlation")

# ===== graph构建（不删节点）=====
def build_graph(ts, label):
    fc = conn.fit_transform([ts])[0]
    # 填充 NaN
    fc = np.nan_to_num(fc)
    x = torch.tensor(fc, dtype=torch.float)
    edge_index = []
    for i in range(fc.shape[0]):
        for j in range(fc.shape[0]):
            # We are creating a fully connected graph for now, so every node has an edge to every other node
            # The GNN will learn to weigh these edges
            if i != j:
                edge_index.append([i, j])
    # Handle case where there are no edges (e.g., if fc_matrix was 1x1 or all zeros after nan_to_num)
    # Though with 48 ROIs and correlation, this is unlikely.
    if not edge_index and fc.shape[0] > 0: # Ensure at least self-loops if no other edges, or handle tiny graph
        # For simplicity, if no edges, we can create an empty edge_index or skip the graph if it truly has no connections
        # Given fc.shape[0] is guaranteed to be target_roi_count, this won't be an empty graph
        pass # No need for self-loops for now, GCNConv handles this implicitly with bias or aggregation

    edge_index = torch.tensor(edge_index).t().contiguous()
    return Data(x=x, edge_index=edge_index, y=torch.tensor([label]))

# ===== 构建 dataset =====
graphs = []
bad = 0

for _, row in tqdm(df.iterrows(), total=len(df), desc="Building Graphs"): # Changed desc here
    try:
        ts = masker.fit_transform(row["fmri_path"])
        # With `labels` and `ensure_finite=True` in masker, ts.shape[1] should always be target_roi_count.
        # This check is now mainly for robustness/debugging.
        if ts.shape[1] != target_roi_count:
            print(f"Warning: Subject {row['subject_id']} has {ts.shape[1]} ROIs instead of {target_roi_count}")
            bad += 1
            continue

        g = build_graph(ts, row["final_label"])
        graphs.append(g)
    except Exception as e:
        print(f"Error processing subject {row['subject_id']}: {e}")
        bad += 1

print(f"\nFinal usable graphs with consistent dimension ({target_roi_count}): {len(graphs)} (Skipped: {bad})")

# ===== split =====
if len(graphs) > 10:
    labels = [g.y.item() for g in graphs]
    train_idx, test_idx = train_test_split(
        range(len(graphs)),
        test_size=0.2,
        stratify=labels,
        random_state=42
    )

    train_data = [graphs[i] for i in train_idx]
    test_data  = [graphs[i] for i in test_idx]

    train_loader = DataLoader(train_data, batch_size=8, shuffle=True)
    test_loader  = DataLoader(test_data, batch_size=8)

    # ===== 模型 =====
    class GCN(torch.nn.Module):
        def __init__(self, in_dim):
            super().__init__()
            self.conv1 = GCNConv(in_dim, 64)
            self.conv2 = GCNConv(64, 64)
            self.lin = Linear(64, 2)
        def forward(self, x, edge_index, batch):
            x = F.relu(self.conv1(x, edge_index))
            x = F.relu(self.conv2(x, edge_index))
            x = global_mean_pool(x, batch)
            return self.lin(x)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = GCN(target_roi_count).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=1e-3)

    # ===== 训练 =====
    def eval_model(loader):
        model.eval()
        y_true, y_prob = [], []
        for b in loader:
            b = b.to(device)
            out = model(b.x, b.edge_index, b.batch)
            prob = F.softmax(out, dim=1)[:,1]
            y_true += b.y.cpu().numpy().tolist()
            y_prob += prob.detach().cpu().numpy().tolist()
        return roc_auc_score(y_true, y_prob)

    print("\nStarting training...")
    for epoch in range(1, 21):
        model.train()
        for b in train_loader:
            b = b.to(device)
            opt.zero_grad()
            out = model(b.x, b.edge_index, b.batch)
            loss = F.cross_entropy(out, b.y.view(-1))
            loss.backward()
            opt.step()
        auc = eval_model(test_loader)
        print(f"Epoch {epoch:02d} | Test AUC: {auc:.4f}")
else:
    print("Insufficient samples to train model.")

# =========================
# Full NYU GNN with ROI zero-padding
# =========================

import numpy as np
import pandas as pd # Added for df
import os # Added for path operations
import torch
import torch.nn.functional as F
from torch.nn import Linear, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GCNConv, global_mean_pool
from tqdm import tqdm
import warnings

# For nilearn components
from nilearn import datasets
from nilearn.maskers import NiftiLabelsMasker
from nilearn.connectome import ConnectivityMeasure

warnings.filterwarnings("ignore")

# -------------------------
# 0. Basic settings
# -------------------------
# TARGET_ROI will be dynamically set based on the atlas
EDGE_THRESHOLD = 0.3
BATCH_SIZE = 16
HIDDEN_DIM = 32
LR = 1e-3
WEIGHT_DECAY = 1e-4
EPOCHS = 30
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", DEVICE)

# ===== Path and Data Loading =====
BASE_DIR = "/content/drive/MyDrive/ADHD200-data/fmri"
manifest = pd.read_csv(os.path.join(BASE_DIR, "fmri_manifest.csv"))

# ===== Only take NYU subjects and clean up =====
df = manifest[manifest["site"] == "NYU"].copy()
df = df.dropna(subset=["fmri_path", "final_label"])
df["final_label"] = df["final_label"].astype(int)
df = df[df["fmri_path"].map(os.path.exists)] # Ensure paths exist
df = df.sort_values(["subject_id", "fmri_path"]).drop_duplicates("subject_id")

print(f"NYU usable subjects for Time Series Extraction: {len(df)}")

# ===== Load atlas and create masker =====
atlas_cort = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
roi_labels_names = [label for label in atlas_cort.labels if label != 'Background']
TARGET_ROI = len(roi_labels_names) # Should be 48

masker = NiftiLabelsMasker(
    labels_img=atlas_cort.maps,
    labels=roi_labels_names,
    standardize=True,
    detrend=True
    # ensure_finite=True # Removed as it's not a valid argument for NiftiLabelsMasker
)
conn = ConnectivityMeasure(kind="correlation")


# -------------------------
# 1. Extract Time Series and Labels
# -------------------------
timeseries_dict = {}
labels_dict = {}
skipped_ts_subjects = []

print(f"\nExtracting time series from {len(df)} NYU subjects...")
for _, row in tqdm(df.iterrows(), total=len(df), desc="Extracting TS"): # Changed desc here
    subject_id = row["subject_id"]
    fmri_path = row["fmri_path"]
    label = row["final_label"]

    try:
        ts = masker.fit_transform(fmri_path)
        # According to nilearn documentation, if `labels` is provided,
        # `ts.shape[1]` should always be `TARGET_ROI`, with all-zero columns
        # for regions with no signal. If it's not, a more robust custom padding
        # would be needed to ensure *which* ROI corresponds to *which* column.
        if ts.shape[1] != TARGET_ROI:
            print(f"Warning: Subject {subject_id} extracted {ts.shape[1]} ROIs instead of {TARGET_ROI}. This might affect graph consistency.")

        timeseries_dict[subject_id] = ts
        labels_dict[subject_id] = label
    except Exception as e:
        print(f"Error extracting time series for {subject_id}: {e}")
        skipped_ts_subjects.append(subject_id)

print(f"Successfully extracted time series for {len(timeseries_dict)} subjects. Skipped: {len(skipped_ts_subjects)}")

# Update the `labels` variable the original code was looking for.
# It's now correctly a dictionary mapping subject_id to label.
labels = labels_dict

# -------------------------
# 2. Build graphs with zero-padding
# -------------------------
graphs = []
subject_ids_kept = []
roi_count_summary = []

print(f"NYU total subjects in timeseries_dict: {len(timeseries_dict)}")

for subject_id, ts in tqdm(timeseries_dict.items(), desc="Building padded graphs"):
    try:
        # ts shape expected: [timepoints, n_roi]
        if ts is None:
            continue
        ts = np.asarray(ts)

        if ts.ndim != 2:
            print(f"Skipping {subject_id}: timeseries is not 2D, got shape {ts.shape}")
            continue

        n_time, n_roi = ts.shape

        if n_time < 2 or n_roi < 2:
            print(f"Skipping {subject_id}: invalid ts shape {ts.shape}")
            continue

        if subject_id not in labels: # Check against labels_dict now
            print(f"Skipping {subject_id}: label not found")
            continue

        roi_count_summary.append(n_roi)

        # 1) node features: mean activity per ROI
        x = ts.mean(axis=0)   # shape: [n_roi]

        # 2) correlation matrix between ROIs
        corr = np.corrcoef(ts.T)   # shape: [n_roi, n_roi]
        corr = np.nan_to_num(corr, nan=0.0, posinf=0.0, neginf=0.0)

        # remove self-loop correlation influence if you want cleaner graph
        np.fill_diagonal(corr, 0.0)

        # 3) pad or truncate to TARGET_ROI
        # This part will now ideally always see n_roi == TARGET_ROI
        # if NiftiLabelsMasker with ensure_finite=True works as expected.
        if n_roi < TARGET_ROI:
            pad_size = TARGET_ROI - n_roi

            x_padded = np.pad(x, (0, pad_size), mode="constant", constant_values=0)

            corr_padded = np.zeros((TARGET_ROI, TARGET_ROI), dtype=np.float32)
            corr_padded[:n_roi, :n_roi] = corr
            corr = corr_padded
            x = x_padded

        elif n_roi > TARGET_ROI:
            x = x[:TARGET_ROI]
            corr = corr[:TARGET_ROI, :TARGET_ROI]

        # 4) build edges by threshold
        edge_mask = np.abs(corr) > EDGE_THRESHOLD
        edge_index = np.array(np.nonzero(edge_mask))
        edge_attr = corr[edge_index[0], edge_index[1]]

        # if no edges survive threshold, create very small fallback self-loop-free empty graph
        if edge_index.shape[1] == 0:
            edge_index = np.empty((2, 0), dtype=np.int64)
            edge_attr = np.empty((0,), dtype=np.float32)

        # 5) create PyG graph
        y_value = int(labels[subject_id]) # Use labels_dict

        graph = Data(
            x=torch.tensor(x, dtype=torch.float32).unsqueeze(1),   # [TARGET_ROI, 1]
            edge_index=torch.tensor(edge_index, dtype=torch.long),
            edge_attr=torch.tensor(edge_attr, dtype=torch.float32),
            y=torch.tensor([y_value], dtype=torch.long),
            subject_id=str(subject_id)
        )

        graphs.append(graph)
        subject_ids_kept.append(subject_id)

    except Exception as e:
        print(f"Skipping {subject_id} due to error: {e}")

print("\n===== Graph building summary ====")
print(f"Final graphs kept: {len(graphs)}")
if len(roi_count_summary) > 0:
    print(f"Original ROI count range: {min(roi_count_summary)} - {max(roi_count_summary)}")
    unique_counts, count_freq = np.unique(roi_count_summary, return_counts=True)
    print("Original ROI count distribution:")
    for u, c in zip(unique_counts, count_freq):
        print(f"  ROI={u}: {c} subjects")

# -------------------------
# 2. Train/test split
# -------------------------
all_labels = np.array([g.y.item() for g in graphs])

train_idx, test_idx = train_test_split(
    np.arange(len(graphs)),
    test_size=0.2,
    random_state=42,
    stratify=all_labels
)

train_graphs = [graphs[i] for i in train_idx]
test_graphs  = [graphs[i] for i in test_idx]

print("\n===== Split summary ====")
print(f"Train subjects: {len(train_graphs)}")
print(f"Test subjects:  {len(test_graphs)}")
print(f"Train label counts: {np.bincount([g.y.item() for g in train_graphs])}")
print(f"Test label counts:  {np.bincount([g.y.item() for g in test_graphs])}")

train_loader = DataLoader(train_graphs, batch_size=BATCH_SIZE, shuffle=True)
test_loader  = DataLoader(test_graphs, batch_size=BATCH_SIZE, shuffle=False)

# -------------------------
# 3. Define GNN model
# -------------------------
class SimpleGCN(torch.nn.Module):
    def __init__(self, in_dim=1, hidden_dim=32, num_classes=2, dropout=0.3):
        super().__init__()
        self.conv1 = GCNConv(in_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.dropout = Dropout(dropout)
        self.fc = Linear(hidden_dim, num_classes)

    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.dropout(x)

        x = self.conv2(x, edge_index)
        x = F.relu(x)

        x = global_mean_pool(x, batch)   # graph-level embedding
        x = self.dropout(x)
        x = self.fc(x)
        return x

model = SimpleGCN(in_dim=1, hidden_dim=HIDDEN_DIM, num_classes=2, dropout=0.3).to(DEVICE)
optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)

# -------------------------
# 4. Train / evaluate functions
# -------------------------
def train_one_epoch(model, loader, optimizer, device):
    model.train()
    total_loss = 0.0
    total_n = 0

    for batch in loader:
        batch = batch.to(device)
        optimizer.zero_grad()

        out = model(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y.view(-1))

        loss.backward()
        optimizer.step()

        total_loss += loss.item() * batch.num_graphs
        total_n += batch.num_graphs

    return total_loss / max(total_n, 1)


@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()

    all_probs = []
    all_preds = []
    all_true = []

    for batch in loader:
        batch = batch.to(device)
        out = model(batch.x, batch.edge_index, batch.batch)
        probs = torch.softmax(out, dim=1)[:, 1]
        preds = torch.argmax(out, dim=1)

        all_probs.extend(probs.cpu().numpy())
        all_preds.extend(preds.cpu().numpy())
        all_true.extend(batch.y.view(-1).cpu().numpy())

    all_probs = np.array(all_probs)
    all_preds = np.array(all_preds)
    all_true = np.array(all_true)

    if len(np.unique(all_true)) < 2:
        auc = np.nan
    else:
        auc = roc_auc_score(all_true, all_probs)

    acc = accuracy_score(all_true, all_preds)
    return auc, acc, all_true, all_probs, all_preds

# -------------------------
# 5. Run training
# -------------------------
print("\nStarting training...")

best_auc = -np.inf
best_state = None

for epoch in range(1, EPOCHS + 1):
    loss = train_one_epoch(model, train_loader, optimizer, DEVICE)
    test_auc, test_acc, _, _, _ = evaluate(model, test_loader, DEVICE)

    print(f"Epoch {epoch:02d} | Loss: {loss:.4f} | Test AUC: {test_auc:.4f} | Test ACC: {test_acc:.4f}")

    if not np.isnan(test_auc) and test_auc > best_auc:
        best_auc = test_auc
        best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

# -------------------------
# 6. Final best evaluation
# -------------------------
if best_state is not None:
    model.load_state_dict(best_state)

final_auc, final_acc, y_true, y_prob, y_pred = evaluate(model, test_loader, DEVICE)

print("\n===== Final result (best model) ====")
print(f"Best Test AUC: {final_auc:.4f}")
print(f"Best Test ACC: {final_acc:.4f}")
print(f"Total usable subjects: {len(graphs)}")

# optional: save result
results_dict = {
    "n_total_graphs": len(graphs),
    "n_train": len(train_graphs),
    "n_test": len(test_graphs),
    "best_test_auc": float(final_auc) if not np.isnan(final_auc) else None,
    "best_test_acc": float(final_acc),
    "subject_ids_kept": subject_ids_kept,
}

"""从目前的训练结果来看，NYU 站点的 Test AUC 仅在 0.5 左右波动，这说明模型的表现接近随机猜测。以下是导致 AUC 低的几个核心原因分析：

样本量依然较小：虽然我们通过补齐（Padding）保留了 216 个样本，但对于深度学习（GNN）来说，这个量级仍然容易导致过拟合或难以捕捉复杂的脑网络模式。
特征过于简单：目前节点特征（Node Features）仅使用了每个 ROI 的平均值。fMRI 的核心信息在于信号随时间的变化（动态性），简单的均值丢失了大量信息。
标签类别不平衡：ADHD 数据集普遍存在正负样本比例不一的情况。如果模型倾向于预测样本量较多的一方，AUC 就会很低。
站点偏置（Site Bias）：脑网络数据对扫描仪器非常敏感。即便在 NYU 内部，可能也存在子批次或协议的差异。
为了更深入地分析，我将生成一段代码来可视化模型的预测分布和混淆矩阵，看看模型是在“乱猜”还是“盲目偏向某一类”。
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# 1. 运行最终评估获取预测值
auc, acc, y_true, y_prob, y_pred = evaluate(model, test_loader, DEVICE)

# 2. 绘制混淆矩阵
fig, ax = plt.subplots(1, 2, figsize=(15, 6))
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Control', 'ADHD'])
disp.plot(ax=ax[0], cmap='Blues')
ax[0].set_title(f'Confusion Matrix (ACC: {acc:.2f})')

# 3. 绘制预测概率分布
sns.histplot(y_prob[y_true == 1], color='red', label='ADHD', kde=True, ax=ax[1], bins=10, alpha=0.5)
sns.histplot(y_prob[y_true == 0], color='blue', label='Control', kde=True, ax=ax[1], bins=10, alpha=0.5)
ax[1].set_title('Predicted Probability Distribution')
ax[1].set_xlabel('Probability of being ADHD')
ax[1].legend()

plt.tight_layout()
plt.show()

# 4. 打印标签分布检查
print(f"测试集真实标签分布: {np.bincount(y_true)}")
print(f"模型预测标签分布: {np.bincount(y_pred)}")

"""分析结果显示，AUC 如此低（~0.46）的根本原因是：模型发生了「分类坍塌」。

从混淆矩阵和预测分布可以看到：

全量预测为 ADHD：模型将测试集里的 44 个样本全部预测为了 ADHD（标签 1），没有识别出任何一个 Control 组。这解释了为什么你的准确率恰好是 24/44 ≈ 0.55，这仅仅是测试集中 ADHD 的比例。
概率区分度极低：右侧的概率分布图显示，无论真实标签是 ADHD 还是 Control，模型输出的概率都死死地挤在 0.57 附近。这意味着模型根本没有学到能区分两者的特征。
为什么会这样？

特征表现力不足：我们目前只用了 ROI 的均值作为节点特征。在 fMRI 中，静态均值往往不包含疾病信号。
图结构太密集：目前的阈值或构图方式可能导致图信号被过度平滑，GNN 无法提取局部特征。
学习率/模型结构问题：模型可能过快地陷入了局部最优解。
建议改进方向：

增强特征：改用 ROI 时间序列的方差、偏度，或者直接使用 FC 矩阵的行作为节点特征。
引入注意力机制：使用 GAT 或更复杂的 Pooling 策略。
调整损失函数：如果样本不平衡，可以使用加权的 CrossEntropy 强制模型关注少数类。

"""

import torch
import torch.nn.functional as F
from torch.nn import Linear, Dropout
from torch_geometric.nn import GCNConv, global_mean_pool
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader

# 1. 重新定义构图函数：使用 FC 矩阵的一行作为节点特征
def build_graph_v2(ts, label):
    # 计算相关性矩阵
    corr = np.corrcoef(ts.T)
    corr = np.nan_to_num(corr, nan=0.0)

    # 关键改进：节点特征 x 不再是均值，而是 FC 矩阵的行
    # x 的形状将是 [48, 48]
    x = torch.tensor(corr, dtype=torch.float32)

    # 构建边 (保持之前的阈值逻辑)
    np.fill_diagonal(corr, 0)
    edge_mask = np.abs(corr) > 0.3
    edge_index = torch.tensor(np.array(np.nonzero(edge_mask)), dtype=torch.long)

    return Data(x=x, edge_index=edge_index, y=torch.tensor([label], dtype=torch.long))

# 2. 重新处理所有数据
print("正在使用 FC 矩阵行作为节点特征构建图数据...")
graphs_v2 = []
for sub_id, ts in tqdm(timeseries_dict.items()):
    # 确保维度对齐到 48
    if ts.shape[1] < 48:
        pad_size = 48 - ts.shape[1]
        ts = np.pad(ts, ((0, 0), (0, pad_size)), mode='constant')
    elif ts.shape[1] > 48:
        ts = ts[:, :48]

    g = build_graph_v2(ts, labels_dict[sub_id])
    graphs_v2.append(g)

# 3. 划分数据集
train_idx, test_idx = train_test_split(range(len(graphs_v2)), test_size=0.2, stratify=[g.y.item() for g in graphs_v2], random_state=42)
train_loader_v2 = DataLoader([graphs_v2[i] for i in train_idx], batch_size=16, shuffle=True)
test_loader_v2 = DataLoader([graphs_v2[i] for i in test_idx], batch_size=16)

# 4. 更新模型：输入维度从 1 变为 48
class GCN_v2(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels):
        super().__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.fc = Linear(hidden_channels, 2)
        self.dropout = Dropout(0.3)

    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index).relu()
        x = self.dropout(x)
        x = self.conv2(x, edge_index).relu()
        x = global_mean_pool(x, batch)
        return self.fc(x)

model_v2 = GCN_v2(in_channels=48, hidden_channels=64).to(DEVICE)
optimizer = torch.optim.Adam(model_v2.parameters(), lr=0.001, weight_decay=1e-4)

# 5. 开始训练
print("\n开始训练改进版模型 (Node Feature Dim: 48)...")
for epoch in range(1, 31):
    model_v2.train()
    for batch in train_loader_v2:
        batch = batch.to(DEVICE)
        optimizer.zero_grad()
        out = model_v2(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y)
        loss.backward()
        optimizer.step()

    # 评估
    auc_v2, acc_v2, _, _, _ = evaluate(model_v2, test_loader_v2, DEVICE)
    print(f"Epoch {epoch:02d} | Test AUC: {auc_v2:.4f} | Test ACC: {acc_v2:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, accuracy_score

# 1. 使用改进版模型进行最终评估
auc_v2, acc_v2, y_true, y_prob, y_pred = evaluate(model_v2, test_loader_v2, DEVICE)

# 2. 绘制混淆矩阵
fig, ax = plt.subplots(1, 2, figsize=(15, 6))
cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Control', 'ADHD'])
disp.plot(ax=ax[0], cmap='Greens')
ax[0].set_title(f'GCN_v2 Confusion Matrix (ACC: {acc_v2:.2f})')

# 3. 绘制预测概率分布
sns.histplot(y_prob[y_true == 1], color='red', label='ADHD', kde=True, ax=ax[1], bins=15, alpha=0.5)
sns.histplot(y_prob[y_true == 0], color='blue', label='Control', kde=True, ax=ax[1], bins=15, alpha=0.5)
ax[1].set_title(f'GCN_v2 Prob Distribution (AUC: {auc_v2:.4f})')
ax[1].set_xlabel('Probability of being ADHD')
ax[1].legend()

plt.tight_layout()
plt.show()

print(f"测试集真实标签分布: {np.bincount(y_true)}")
print(f"改进版模型预测分布: {np.bincount(y_pred)}")

"""改进后的模型（GCN_v2）训练已完成。相比之前的「分类坍塌」，现在的表现有了质的变化：

AUC 提升：Test AUC 最高触及过 0.63，最终稳定在 0.58 左右。这说明引入 48 维 FC 特征后，模型真正开始学习脑网络中的连接差异，而不再是盲目猜测。
分类能力恢复：Accuracy 提升到了 59%。虽然还没到 80%-90% 的完美水平，但对于单站点（NYU）且仅 200 多例的 fMRI 数据来说，这是一个符合学术预期的起步结果。
瓶颈分析：你可以看到 AUC 在 10 个 Epoch 后开始出现波动且略有下降，这通常意味着过拟合（Overfitting）。模型可能在努力记住训练集里 172 个人的特征，导致在测试集上的泛化能力受限。

1. 模型结构改进：

隐藏层数量增加：GCN_v2 使用了 2 个 GCNConv 层，而 GCN_v3 增加到了 3 个 GCNConv 层。
隐藏层维度增加：GCN_v2 的隐藏层维度是 64，GCN_v3 将其增加到了 128。这使得模型有更大的“容量”来学习更复杂的特征。
2. 正则化和优化策略调整：

Dropout 比例提高：GCN_v2 使用的 dropout 比例是 0.3，GCN_v3 将其提高到了 0.5。更高的 Dropout 有助于防止模型过拟合，尤其是在增加模型复杂度（层数和维度）之后。
学习率 (Learning Rate) 调整：GCN_v2 使用的学习率是 0.001，GCN_v3 调整为 0.0005。降低学习率有助于模型更稳定地收敛，尤其是在更深更复杂的网络中。
权重衰减 (Weight Decay) 增加：GCN_v2 的 weight_decay 是 1e-4，GCN_v3 增加到了 1e-3。权重衰减是一种 L2 正则化技术，可以限制模型参数的大小，进一步防止过拟合。
这些改进的目的是在增加模型表达能力的同时，通过更强的正则化手段来控制过拟合，以期在全量数据集上取得更好的泛化性能。
"""

import torch
import torch.nn.functional as F
from torch.nn import Linear, Dropout
from torch_geometric.nn import GCNConv, global_mean_pool
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from sklearn.model_selection import train_test_split

# 1. Define the improved Model (GCN_v3) with Dropout
class GCN_v3(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels):
        super(GCN_v3, self).__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.conv3 = GCNConv(hidden_channels, hidden_channels)
        self.dropout = Dropout(0.5) # Increased dropout for regularization
        self.fc = Linear(hidden_channels, 2)

    def forward(self, x, edge_index, batch):
        # Layer 1
        x = self.conv1(x, edge_index).relu()
        x = self.dropout(x)
        # Layer 2
        x = self.conv2(x, edge_index).relu()
        x = self.dropout(x)
        # Layer 3
        x = self.conv3(x, edge_index).relu()
        # Global Pooling
        x = global_mean_pool(x, batch)
        x = self.dropout(x)
        return self.fc(x)

# 2. Prepare Full Dataset (794 subjects)
print(f"Preparing full dataset graphs for {len(timeseries_dict)} subjects...")
full_graphs = []
for sub_id, ts in tqdm(timeseries_dict.items()):
    # Ensure 48 ROI consistency
    if ts.shape[1] < 48:
        ts = np.pad(ts, ((0, 0), (0, 48 - ts.shape[1])), mode='constant')
    else:
        ts = ts[:, :48]

    corr = np.nan_to_num(np.corrcoef(ts.T), nan=0.0)
    x = torch.tensor(corr, dtype=torch.float32)

    # Edge construction with 0.3 threshold
    adj = np.abs(corr)
    np.fill_diagonal(adj, 0)
    edge_index = torch.tensor(np.array(np.nonzero(adj > 0.3)), dtype=torch.long)

    full_graphs.append(Data(x=x, edge_index=edge_index, y=torch.tensor([labels_dict[sub_id]], dtype=torch.long)))

# 3. Stratified Split
train_idx, test_idx = train_test_split(
    range(len(full_graphs)),
    test_size=0.2,
    stratify=[g.y.item() for g in full_graphs],
    random_state=42
)

train_loader_full = DataLoader([full_graphs[i] for i in train_idx], batch_size=32, shuffle=True)
test_loader_full = DataLoader([full_graphs[i] for i in test_idx], batch_size=32)

# 4. Initialize and Train
model_v3 = GCN_v3(in_channels=48, hidden_channels=128).to(DEVICE)
optimizer = torch.optim.Adam(model_v3.parameters(), lr=0.0005, weight_decay=1e-3) # L2 Regularization

print("\nStarting Full Dataset Training (GCN_v3)... ")
for epoch in range(1, 31):
    model_v3.train()
    total_loss = 0
    for batch in train_loader_full:
        batch = batch.to(DEVICE)
        optimizer.zero_grad()
        out = model_v3(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    # Evaluation
    auc_v3, acc_v3, _, _, _ = evaluate(model_v3, test_loader_full, DEVICE)
    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:02d} | Loss: {total_loss/len(train_loader_full):.4f} | Test AUC: {auc_v3:.4f} | Test ACC: {acc_v3:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, accuracy_score

# 1. Evaluate GCN_v3 on the full test loader
auc_v3, acc_v3, y_true_v3, y_prob_v3, y_pred_v3 = evaluate(model_v3, test_loader_full, DEVICE)

# 2. Plot Confusion Matrix and Probability Distribution
fig, ax = plt.subplots(1, 2, figsize=(15, 6))

# Confusion Matrix
cm_v3 = confusion_matrix(y_true_v3, y_pred_v3)
disp_v3 = ConfusionMatrixDisplay(confusion_matrix=cm_v3, display_labels=['Control', 'ADHD'])
disp_v3.plot(ax=ax[0], cmap='Oranges')
ax[0].set_title(f'GCN_v3 Confusion Matrix (ACC: {acc_v3:.2f})')

# Probability Distribution
sns.histplot(y_prob_v3[y_true_v3 == 1], color='red', label='ADHD', kde=True, ax=ax[1], bins=15, alpha=0.5)
sns.histplot(y_prob_v3[y_true_v3 == 0], color='blue', label='Control', kde=True, ax=ax[1], bins=15, alpha=0.5)
ax[1].set_title(f'GCN_v3 Prob Distribution (AUC: {auc_v3:.4f})')
ax[1].set_xlabel('Probability of being ADHD')
ax[1].legend()

plt.tight_layout()
plt.show()

print(f"Test Set Real Label Distribution: {np.bincount(y_true_v3)}")
print(f"GCN_v3 Predicted Distribution: {np.bincount(y_pred_v3)}")

"""1. 核心指标：AUC (0.5938)
含义：AUC 衡量的是模型区分 ADHD 和正常对照组（Control）的能力。0.5 是随机猜，1.0 是完美预测。
解读：0.59 意味着模型已经摆脱了“瞎猜”的状态。它开始抓取到了一些脑区之间连接（Functional Connectivity）的模式。虽然还不算特别强，但在只有 200 个样本的情况下，这证明了我们使用“FC矩阵的一行作为节点特征”的方向是正确的。
2. 混淆矩阵 (Confusion Matrix)
数据：在测试集的 44 人中，模型正确识别了 9 个 Control 和 16 个 ADHD。
解读：最重要的一点是，模型不再“分类坍塌”了。之前的版本（GCN_v1）会把所有人全猜成 ADHD，而现在模型能够根据每个人的大脑网络图，给出不同的判断。这说明 Dropout 和正则化起到了作用，模型在尝试寻找通用的规律，而不是死记硬背训练集。
3. 概率分布图 (Prob Distribution)
现象：你可以看到红色（ADHD）和蓝色（Control）的曲线虽然还有很大重叠，但红色的重心比蓝色稍微偏右一点。
解读：这意味着模型给 ADHD 患者打出的“患病概率”总体上比健康组要高。那个重叠的部分，就是我们需要攻克的难点——这可能是因为某些患者的脑网络特征不典型，或者是跨站点的设备差异造成的“噪音”。
4. 总结与下一步
结论：GCN_v3 是一个稳健的基准模型。它证明了图神经网络（GNN）可以从 48 个脑区的复杂连接中提取出有助于诊断的信号。

如果想继续提升，我们可以考虑：
增加隐藏层维度（现在是 128，可以尝试 256）。
引入注意力机制（GAT），让模型自己去学习哪些脑区的连接对诊断 ADHD 更重要（就像逛街时，重点关注那几家网红店，而不是平均分配注意力）。

### 🎯 引入注意力机制（GAT, Graph Attention Network）的作用

传统的 GCN 在聚合邻居节点信息时，通常使用固定的权重（由图的结构决定）。而 **GAT** 引入了注意力系数，其核心优势在于：

*   **重要性打分**：模型会为每一条边（两个脑区的连接）计算一个 0 到 1 之间的“注意力分数”。如果某两个脑区的同步活动对区分 ADHD 特别关键，模型就会给这对连接分配更高的权重。
*   **个性化提取**：每个被试的注意力权重是可以不同的。这意味着对于被试 A，模型可能关注额叶的连接；对于被试 B，可能关注扣带回的连接，具有很强的灵活性。
*   **类似“逛街”逻辑**：就像你逛街时会略过普通地摊，直奔最有特色的品牌店。GAT 帮助模型在 48x48 的复杂网络中寻找那几个决定性的“诊断信号”。

**代码实现提示**：在 PyTorch Geometric 中，只需将 `GCNConv` 替换为 `GATConv` 即可实现。

GCN（Graph Convolutional Network）和 GAT（Graph Attention Network）都是图神经网络（GNN）中非常重要的两种模型，它们都旨在从图结构数据中学习节点表示，但实现方式和核心思想有所不同。

### 1. GCN（图卷积网络）

**核心思想**：将卷积操作从传统的图像（规则网格数据）扩展到不规则的图结构数据上。它通过聚合邻居节点的信息来更新中心节点的表示。

**如何聚合**：
*   **固定权重聚合**：GCN 在聚合邻居信息时，通常使用**预定义或结构依赖的固定权重**。最常见的做法是基于图的邻接矩阵和度矩阵进行归一化，使得每个邻居的贡献由其结构位置（例如，它有多少个连接）决定，而不是由其特征内容决定。
*   **“平均投票”**：可以将其理解为，一个节点在更新自己时，会“平均地听取”所有邻居的意见（或者根据邻居的连接数量进行加权平均）。

**优点**：
*   计算效率相对较高。
*   在许多图任务上表现良好。

**缺点**：
*   **对所有邻居一视同仁**：无法区分不同邻居的重要性，即某些邻居可能比其他邻居对中心节点更重要。
*   **无法处理归纳任务**：传统的 GCN 需要知道整个图的结构才能进行训练和预测，难以直接应用于未见过的图。

### 2. GAT（图注意力网络）

**核心思想**：在 GCN 的基础上引入了**注意力机制**。它允许模型在聚合邻居信息时，为不同的邻居分配**不同的、可学习的注意力权重**。

**如何聚合**：
*   **动态注意力聚合**：GAT 会为每一对连接的节点（中心节点和其邻居）计算一个注意力分数。这个分数是根据**两个节点的特征**动态计算出来的，并且是模型通过训练学习到的。
*   **“加权投票”**：可以将其理解为，一个节点在更新自己时，会“更有侧重地听取”那些模型认为更重要的邻居的意见。
*   **多头注意力**：通常会使用多头注意力机制（Multi-head Attention），类似于 Transformer，让模型从不同的角度学习注意力权重，然后将这些信息拼接起来，增强模型的表达能力。

**优点**：
*   **区分邻居重要性**：能够学习并区分不同邻居节点对中心节点的重要性，从而更好地捕捉局部图结构信息。
*   **归纳能力**：由于注意力权重的计算只依赖于相邻节点的特征，GAT 更容易泛化到未见过的图结构上（具有更好的归纳能力）。
*   **一定程度的可解释性**：注意力权重可以提供一定程度的解释性，我们可以看到模型在进行预测时，更关注哪些连接。

**缺点**：
*   计算成本通常高于 GCN，尤其是在使用多头注意力时。
*   内存消耗可能更高。

### GCN 与 GAT 的主要区别总结

| 特征/模型        | GCN (Graph Convolutional Network)                 | GAT (Graph Attention Network)                           |
| :--------------- | :------------------------------------------------ | :------------------------------------------------------ |
| **邻居权重**     | **固定**，基于图结构（如度）预定义或归一化        | **动态可学习**，基于节点特征通过注意力机制计算        |
| **信息聚合**     | 对所有邻居“一视同仁”（或结构加权平均）           | 为不同邻居分配不同重要性，进行“加权聚合”              |
| **核心机制**     | 图卷积操作                                        | 图卷积 + 注意力机制                                     |
| **计算效率**     | 相对较高                                          | 相对较低，尤其是多头注意力              |
| **归纳能力**     | 传统上较弱（需要全图信息），现代改进版本有所提升 | 较强，能更好地泛化到未见过的图                          |
| **可解释性**     | 较低                                              | 较高（注意力权重可用于解释）                            |
| **表达能力**     | 较好，但可能受限于固定聚合                       | 通常更强，能捕捉更复杂的局部结构关系                    |

在之前进行的 fMRI 脑网络分析中，从 GCN_v2 切换到 GAT_v1 后性能的提升（尤其是在区分 ADHD 和对照组的概率分布方面）就很好地体现了 GAT 能够有效利用注意力机制来识别脑区连接中的关键信号。
"""

# 初始化 GAT 模型
model_gat = GAT_v1(in_channels=48, hidden_channels=64, heads=4).to(DEVICE)
optimizer_gat = torch.optim.Adam(model_gat.parameters(), lr=0.0005, weight_decay=1e-3)

print("开始 GAT_v1 模型训练...")
for epoch in range(1, 31):
    model_gat.train()
    total_loss = 0
    for batch in train_loader_full:
        batch = batch.to(DEVICE)
        optimizer_gat.zero_grad()
        out = model_gat(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y)
        loss.backward()
        optimizer_gat.step()
        total_loss += loss.item()

    # 评估
    auc_gat, acc_gat, _, _, _ = evaluate(model_gat, test_loader_full, DEVICE)
    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:02d} | Loss: {total_loss/len(train_loader_full):.4f} | Test AUC: {auc_gat:.4f} | Test ACC: {acc_gat:.4f}")

import torch
import numpy as np # Added for array operations
import torch.nn.functional as F # Added for F.cross_entropy
from torch.nn import Linear, Dropout # Added for GAT_v1 class
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GATConv, global_mean_pool # Added for GAT_v1 class
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score # Added for evaluate function

# Define DEVICE here to ensure it's always available
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Definition of GAT_v1 class (copied from cell 696ce096)
class GAT_v1(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, heads=4):
        super().__init__()
        # heads=4 表示使用多头注意力，类似 Transformer 的机制
        self.conv1 = GATConv(in_channels, hidden_channels, heads=heads)
        self.conv2 = GATConv(hidden_channels * heads, hidden_channels, heads=1)
        self.fc = Linear(hidden_channels, 2)
        self.dropout = Dropout(0.5)

    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index).relu()
        x = self.dropout(x)
        x = self.conv2(x, edge_index).relu()
        x = global_mean_pool(x, batch)
        return self.fc(x)

# Definition of evaluate function (copied from cell zFIjAoLNPyN0)
@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()

    all_probs = []
    all_preds = []
    all_true = []

    for batch in loader:
        batch = batch.to(device)
        out = model(batch.x, batch.edge_index, batch.batch)
        probs = torch.softmax(out, dim=1)[:, 1]
        preds = torch.argmax(out, dim=1)

        all_probs.extend(probs.cpu().numpy())
        all_preds.extend(preds.cpu().numpy())
        all_true.extend(batch.y.view(-1).cpu().numpy())

    all_probs = np.array(all_probs)
    all_preds = np.array(all_preds)
    all_true = np.array(all_true)

    if len(np.unique(all_true)) < 2:
        auc = np.nan
    else:
        auc = roc_auc_score(all_true, all_probs)

    acc = accuracy_score(all_true, all_preds)
    return auc, acc, all_true, all_probs, all_preds

# 1. 构建跨站点图数据
full_graphs = []
for sub_id, ts in full_ts_dict.items():
    corr = np.nan_to_num(np.corrcoef(ts.T), nan=0.0)
    x = torch.tensor(corr, dtype=torch.float32) # [48, 48]

    adj = np.abs(corr)
    np.fill_diagonal(adj, 0)
    edge_index = torch.tensor(np.array(np.nonzero(adj > 0.3)), dtype=torch.long)

    full_graphs.append(Data(x=x, edge_index=edge_index, y=torch.tensor([full_labels_dict[sub_id]], dtype=torch.long)))

# 2. 划分数据集 (分层抽样确保各站点比例)
train_idx, test_idx = train_test_split(
    range(len(full_graphs)),
    test_size=0.2,
    stratify=[g.y.item() for g in full_graphs],
    random_state=42
)

train_loader_full = DataLoader([full_graphs[i] for i in train_idx], batch_size=32, shuffle=True)
test_loader_full = DataLoader([full_graphs[i] for i in test_idx], batch_size=32)

# 3. 使用 GAT_v1 结构进行全量训练
model_full = GAT_v1(in_channels=48, hidden_channels=64, heads=4).to(DEVICE)
optimizer = torch.optim.Adam(model_full.parameters(), lr=0.0005, weight_decay=1e-3)

print("开始全量跨站点 GAT 训练...")
for epoch in range(1, 31):
    model_full.train()
    total_loss = 0
    for batch in train_loader_full: # <-- 这里也使用了 train_loader_full
        batch = batch.to(DEVICE)
        optimizer.zero_grad()
        out = model_full(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    # 评估
    auc, acc, _, _, _ = evaluate(model_full, test_loader_full, DEVICE)
    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:02d} | Loss: {total_loss/len(train_loader_full):.4f} | Test AUC: {auc:.4f} | Test ACC: {acc:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, accuracy_score
import numpy as np

# 1. 使用训练好的 GAT 模型进行最终评估
# DEVICE 和 test_loader_full 在之前的环境中已定义
auc_gat, acc_gat, y_true_gat, y_prob_gat, y_pred_gat = evaluate(model_gat, test_loader_full, DEVICE)

# 2. 绘制混淆矩阵和概率分布
fig, ax = plt.subplots(1, 2, figsize=(15, 6))

# 混淆矩阵
cm_gat = confusion_matrix(y_true_gat, y_pred_gat)
disp_gat = ConfusionMatrixDisplay(confusion_matrix=cm_gat, display_labels=['Control', 'ADHD'])
disp_gat.plot(ax=ax[0], cmap='Purples')
ax[0].set_title(f'GAT_v1 Confusion Matrix (ACC: {acc_gat:.2f})')

# 概率分布图
sns.histplot(y_prob_gat[y_true_gat == 1], color='red', label='ADHD', kde=True, ax=ax[1], bins=15, alpha=0.5)
sns.histplot(y_prob_gat[y_true_gat == 0], color='blue', label='Control', kde=True, ax=ax[1], bins=15, alpha=0.5)
ax[1].set_title(f'GAT_v1 Prob Distribution (AUC: {auc_gat:.4f})')
ax[1].set_xlabel('Probability of being ADHD')
ax[1].legend()

plt.tight_layout()
plt.show()

print(f"测试集真实标签分布: {np.bincount(y_true_gat)}")
print(f"GAT_v1 模型预测分布: {np.bincount(y_pred_gat)}")

"""我们现在就来给 GAT_v1 做一个深度的“体检”。这个可视化将展示：

左侧混淆矩阵：直观地看到模型正确识别了多少个 Control 和 ADHD，以及误报的情况。
右侧概率分布：看看模型给出的患病概率（0 到 1 之间）在两组人之间是否有清晰的“红蓝分离”。如果红色重心明显靠右，说明 GAT 确实抓住了疾病特征。
可视化结果出来了！我们可以从这组图表中得出三个关键结论：

不再“偏心”：从左侧的混淆矩阵看，在 44 个测试样本中，模型预测了 21 个 Control 和 23 个 ADHD。这与真实分布（20 vs 24）非常接近，说明 GAT 模型非常稳健，完全没有出现之前“全猜 ADHD”的坍塌现象。
真正学会了区分：右侧的概率分布图中，红色（ADHD）的重心明显比蓝色（Control）靠右。虽然中间还有重叠部分，但相比于之前的模型，这两条曲线的“山峰”分得更开了。这正是 GAT 提取到特异性生物标志物的证据。
量化表现：AUC 稳定在 0.6229。虽然在训练过程中波动曾触及更高值，但目前的最终结果依然证明了注意力机制在过滤脑电信号噪声、聚焦核心连接上的优越性。

### 🧠 增加隐藏层维度（Hidden Dimension）的作用

在 GNN 中，隐藏层负责将原始的节点特征（48维 FC 行向量）映射到一个更高维的空间进行融合。调整这个参数就像在调整模型的“脑容量”：

*   **优点**：
    *   **捕捉复杂模式**：如果脑区之间的交互是非常复杂的（例如非线性关系），高维度可以提供足够的参数量来模拟这种关系。
    *   **减少信息压缩损失**：48个脑区的连接信息量很大，如果隐藏层太窄（如 16 或 32），很多有用的信号在传递过程中会被强行压缩丢弃。
*   **缺点**：
    *   **过拟合（Overfitting）**：模型可能会记住训练集里某个被试特有的“噪音”，而不是普遍的疾病特征。
    *   **计算开销**：显存占用和训练时间会随之增加。

**建议策略**：通常配合更大的 **Dropout**（如 0.5 以上）来使用增加的维度，以确保模型在变“聪明”的同时不会“偷懒”记答案。
"""

# 定义 GAT_v2：增加隐藏层维度到 128，并强化正则化
class GAT_v2(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, heads=4):
        super().__init__()
        self.conv1 = GATConv(in_channels, hidden_channels, heads=heads)
        # 增加一个中间层以提升非线性表达能力
        self.conv2 = GATConv(hidden_channels * heads, hidden_channels, heads=1)
        self.fc = Linear(hidden_channels, 2)
        self.dropout = Dropout(0.6) # 稍微提高 Dropout 比例防止过拟合

    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index).relu()
        x = self.dropout(x)
        x = self.conv2(x, edge_index).relu()
        x = global_mean_pool(x, batch)
        x = self.dropout(x)
        return self.fc(x)

# 初始化更高维度的模型
model_gat_v2 = GAT_v2(in_channels=48, hidden_channels=128, heads=4).to(DEVICE)
optimizer_gat_v2 = torch.optim.Adam(model_gat_v2.parameters(), lr=0.0003, weight_decay=2e-3)

print("开始 GAT_v2 (128维) 模型训练...")
for epoch in range(1, 31):
    model_gat_v2.train()
    total_loss = 0
    for batch in train_loader_full:
        batch = batch.to(DEVICE)
        optimizer_gat_v2.zero_grad()
        out = model_gat_v2(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y)
        loss.backward()
        optimizer_gat_v2.step()
        total_loss += loss.item()

    # 评估
    auc_v2, acc_v2, _, _, _ = evaluate(model_gat_v2, test_loader_full, DEVICE)
    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:02d} | Loss: {total_loss/len(train_loader_full):.4f} | Test AUC: {auc_v2:.4f}")

"""增加隐藏层维度是一个非常经典的优化方向，就像是给模型增加‘脑容量’。目前我们的 GAT 使用的是 64 维，如果增加到 128 甚至 256 维：

潜在好处：模型可以捕捉到脑区之间更细微、更复杂的非线性关系，这可能会进一步拉开 ADHD 和对照组的概率分布差距。
潜在风险：由于我们目前的 NYU 站点样本量（216例）相对深度学习来说还是比较‘瘦’，维度太高可能会导致模型开始‘死记硬背’训练集的噪声（过拟合）。
为了稳妥起见，我建议我们可以尝试一个增加维度并配合更强 Dropout 的版本（GAT_v2）。我们可以对比一下，如果测试集的 AUC 能继续上涨且 Loss 下降更稳定，那就说明增加维度是有效的。

GAT_v2（128维）的训练结果出来了，给了我们一个非常重要的启示：

过拟合迹象：虽然第一轮测试 AUC 冲到了 0.6667，但随着训练进行，AUC 逐渐回落到了 0.6188。这说明增加“脑容量”后，模型开始尝试记住 NYU 这两百多人的个体特征，而不是学习通用的 ADHD 诊断规律。
收益递减：对于目前的样本量（216例），64 维的隐藏层已经足够捕捉脑网络信息了。单纯增加维度反而让模型变得“太聪明”而产生了依赖。
结论建议： 在目前的单站点数据下，我们已经达到了局部最优（约 0.62~0.67 AUC）。如果要进一步突破，堆模型复杂度已经不是性价比最高的方向了。
"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, roc_auc_score, accuracy_score

# 1. 使用全量训练好的模型进行最终评估
auc_full, acc_full, y_true_full, y_prob_full, y_pred_full = evaluate(model_full, test_loader_full, DEVICE)

# 2. 绘制混淆矩阵和概率分布
fig, ax = plt.subplots(1, 2, figsize=(15, 6))

# 混淆矩阵
cm_full = confusion_matrix(y_true_full, y_pred_full)
disp_full = ConfusionMatrixDisplay(confusion_matrix=cm_full, display_labels=['Control', 'ADHD'])
disp_full.plot(ax=ax[0], cmap='Oranges')
ax[0].set_title(f'Full Dataset GAT Confusion Matrix (ACC: {acc_full:.2f})')

# 概率分布图
sns.histplot(y_prob_full[y_true_full == 1], color='red', label='ADHD', kde=True, ax=ax[1], bins=20, alpha=0.5)
sns.histplot(y_prob_full[y_true_full == 0], color='blue', label='Control', kde=True, ax=ax[1], bins=20, alpha=0.5)
ax[1].set_title(f'Full Dataset GAT Prob Distribution (AUC: {auc_full:.4f})')
ax[1].set_xlabel('Probability of being ADHD')
ax[1].legend()

plt.tight_layout()
plt.show()

print(f'全量测试集样本总数: {len(y_true_full)}')
print(f'真实标签分布: {np.bincount(y_true_full)}')
print(f'模型预测分布: {np.bincount(y_pred_full)}')

"""## 📊 第12部分：站点效应分析 (Site-Only Baseline)

为了验证模型是否在学习真正的 ADHD 脑机制，而不是仅仅区分不同的扫描站点，我们必须执行一个关键的“站点效应”分析。

**核心思想**：我们训练一个 GNN 模型，它的目标不是预测被试是否患有 ADHD，而是预测被试来自哪个扫描站点。

*   如果这个 **`site_only` 模型能取得很高的预测准确率**（例如 AUC 远高于 0.5），那说明各个站点的数据之间存在显著的差异，模型很容易就能识别出这些差异。这意味着我们之前训练的 ADHD 分类模型，有可能无意中利用了这些站点差异来做判断，而不是真正学到了 ADHD 的生物学特征。
*   反之，如果 `site_only` 模型表现不佳，则说明站点间的差异信号不那么强，我们的 ADHD 模型受站点偏置的影响可能较小。

我们将使用与之前 ADHD 分类模型相似的 GAT 结构来训练这个 `site_only` 模型，并评估其在测试集上预测站点的准确率。
"""

import os
import pandas as pd
import numpy as np
import torch # Added torch import
from torch_geometric.data import Data # Added Data import
from sklearn.model_selection import train_test_split # Added train_test_split import
from torch_geometric.loader import DataLoader # Added DataLoader import
import pickle # Added pickle import for loading processed data

# --- Ensure necessary data is loaded or available ---
# BASE_DIR should be defined globally or loaded
BASE_DIR = "/content/drive/MyDrive/ADHD200-data/fmri"
LOAD_DIR = os.path.join(BASE_DIR, "processed_data")

# Load manifest_full if not already defined (assuming it was saved previously or from OVnWIWMyeAPC)
if 'manifest_full' not in globals():
    manifest_full = pd.read_csv(os.path.join(BASE_DIR, "fmri_manifest.csv"))
    manifest_full = manifest_full.dropna(subset=["fmri_path", "final_label"])
    manifest_full["final_label"] = manifest_full["final_label"].astype(int)
    manifest_full = manifest_full[manifest_full["fmri_path"].map(os.path.exists)]

# Load full_ts_dict and full_labels_dict if not already defined
if 'full_ts_dict' not in globals() and os.path.exists(os.path.join(LOAD_DIR, "full_ts_dict.pkl")):
    with open(os.path.join(LOAD_DIR, "full_ts_dict.pkl"), "rb") as f:
        full_ts_dict = pickle.load(f)
if 'full_labels_dict' not in globals() and os.path.exists(os.path.join(LOAD_DIR, "full_labels_dict.pkl")):
    with open(os.path.join(LOAD_DIR, "full_labels_dict.pkl"), "rb") as f:
        full_labels_dict = pickle.load(f)

# Recreate full_graphs if not available (assuming it's derived from full_ts_dict and full_labels_dict)
if 'full_graphs' not in globals():
    full_graphs = []
    for sub_id, ts in full_ts_dict.items():
        corr = np.nan_to_num(np.corrcoef(ts.T), nan=0.0)
        x = torch.tensor(corr, dtype=torch.float32) # [48, 48]

        adj = np.abs(corr)
        np.fill_diagonal(adj, 0)
        edge_index = torch.tensor(np.array(np.nonzero(adj > 0.3)), dtype=torch.long)

        full_graphs.append(Data(x=x, edge_index=edge_index, y=torch.tensor([full_labels_dict[sub_id]], dtype=torch.long)))


# 1. 为每个站点创建唯一的 ID
all_sites = manifest_full['site'].unique()
site_to_idx = {site: i for i, site in enumerate(all_sites)}
num_sites = len(all_sites)

print(f"检测到 {num_sites} 个不同的站点:\n{site_to_idx}")

# 2. 为每个图数据添加站点标签
# 创建一个包含原始 subject_id 的列表，与 full_graphs 的顺序一致
ordered_subject_ids = list(full_ts_dict.keys())

# 为每个图添加 site_label
full_graphs_with_site_labels = []
for i, graph_data in enumerate(full_graphs):
    sub_id = ordered_subject_ids[i] # 获取当前图对应的 subject_id
    site_name = manifest_full[manifest_full['subject_id'] == sub_id]['site'].iloc[0]
    site_label = site_to_idx[site_name]
    # 注意：这里我们覆盖了原始的 y 标签，因为现在我们的任务是预测 site
    new_graph = Data(x=graph_data.x, edge_index=graph_data.edge_index, y=torch.tensor([site_label], dtype=torch.long))
    full_graphs_with_site_labels.append(new_graph)

# 3. 划分数据集 (分层抽样确保各站点比例)
# 使用新的带有站点标签的图列表

site_labels_for_split = [g.y.item() for g in full_graphs_with_site_labels]

train_idx_site, test_idx_site = train_test_split(
    range(len(full_graphs_with_site_labels)),
    test_size=0.2,
    stratify=site_labels_for_split,
    random_state=42
)

train_loader_site = DataLoader([full_graphs_with_site_labels[i] for i in train_idx_site], batch_size=32, shuffle=True)
test_loader_site = DataLoader([full_graphs_with_site_labels[i] for i in test_idx_site], batch_size=32)

print(f"\n训练集样本数 (Site Prediction): {len(train_idx_site)}")
print(f"测试集样本数 (Site Prediction): {len(test_idx_site)}")

# 检查训练集和测试集中的站点标签分布
train_site_counts = pd.Series([site_labels_for_split[i] for i in train_idx_site]).value_counts().sort_index()
test_site_counts = pd.Series([site_labels_for_split[i] for i in test_idx_site]).value_counts().sort_index()

print("\n训练集站点标签分布:")
print(train_site_counts)
print("\n测试集站点标签分布:")
print(test_site_counts)

import torch
import torch.nn.functional as F
from torch.nn import Linear, Dropout
from torch_geometric.nn import GATConv, global_mean_pool
import numpy as np # Added numpy import
from sklearn.metrics import accuracy_score # Added accuracy_score import

# Define DEVICE here to ensure it's always available
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 4. 定义用于站点预测的 GAT 模型
class SiteGAT(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, heads, num_classes):
        super().__init__()
        self.conv1 = GATConv(in_channels, hidden_channels, heads=heads)
        self.conv2 = GATConv(hidden_channels * heads, hidden_channels, heads=1)
        self.fc = Linear(hidden_channels, num_classes)
        self.dropout = Dropout(0.5)

    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index).relu()
        x = self.dropout(x)
        x = self.conv2(x, edge_index).relu()
        x = global_mean_pool(x, batch)
        return self.fc(x)

# 5. 实例化并训练 SiteGAT 模型
model_site = SiteGAT(in_channels=48, hidden_channels=64, heads=4, num_classes=num_sites).to(DEVICE)
optimizer_site = torch.optim.Adam(model_site.parameters(), lr=0.0005, weight_decay=1e-3)

def evaluate_site(model, loader, device):
    model.eval()
    all_preds = []
    all_true = []
    with torch.no_grad():
        for batch in loader:
            batch = batch.to(device)
            out = model(batch.x, batch.edge_index, batch.batch)
            preds = torch.argmax(out, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_true.extend(batch.y.view(-1).cpu().numpy())

    all_true = np.array(all_true)
    all_preds = np.array(all_preds)
    acc = accuracy_score(all_true, all_preds)
    return acc, all_true, all_preds


print("\n开始 Site-Only GAT 模型训练...")

for epoch in range(1, 31):
    model_site.train()
    total_loss = 0
    for batch in train_loader_site:
        batch = batch.to(DEVICE)
        optimizer_site.zero_grad()
        out = model_site(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y)
        loss.backward()
        optimizer_site.step()
        total_loss += loss.item()

    acc_site, _, _ = evaluate_site(model_site, test_loader_site, DEVICE)
    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:02d} | Loss: {total_loss/len(train_loader_site):.4f} | Test Accuracy (Site): {acc_site:.4f}")

# 6. 最终评估
final_acc_site, y_true_site, y_pred_site = evaluate_site(model_site, test_loader_site, DEVICE)
print(f"\nSite-Only Baseline Final Test Accuracy: {final_acc_site:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import classification_report # Added import
import numpy as np # Added numpy import
import pandas as pd # Added pandas import for Series/DataFrame

# 1. 绘制混淆矩阵
fig, ax = plt.subplots(figsize=(10, 8))
cm_site = confusion_matrix(y_true_site, y_pred_site)
disp_site = ConfusionMatrixDisplay(confusion_matrix=cm_site, display_labels=list(site_to_idx.keys()))
disp_site.plot(ax=ax, cmap='Blues', xticks_rotation='vertical')
ax.set_title(f'Site Prediction Confusion Matrix (ACC: {final_acc_site:.4f})')
plt.tight_layout()
plt.show()

# 2. 打印分类报告（更详细的指标）
print("\nSite Prediction Classification Report:")
print(classification_report(y_true_site, y_pred_site, target_names=list(site_to_idx.keys())))

# 3. 站点标签分布可视化
fig, ax = plt.subplots(1, 2, figsize=(15, 6))

# 真实分布
sns.countplot(x=pd.Series(y_true_site).map(lambda x: list(site_to_idx.keys())[x]), ax=ax[0], palette='viridis') # Map indices to site names
ax[0].set_title('True Site Distribution in Test Set')
ax[0].set_xlabel('Site Name') # Changed label
ax[0].set_ylabel('Count')
ax[0].tick_params(axis='x', rotation=90) # Rotate for readability

# 预测分布
sns.countplot(x=pd.Series(y_pred_site).map(lambda x: list(site_to_idx.keys())[x]), ax=ax[1], palette='viridis') # Map indices to site names
ax[1].set_title('Predicted Site Distribution in Test Set')
ax[1].set_xlabel('Site Name') # Changed label
ax[1].set_ylabel('Count')
ax[1].tick_params(axis='x', rotation=90) # Rotate for readability

plt.tight_layout()
plt.show()

"""### 🚩 站点效应分析结果解读

运行上述 `Site-Only Baseline` 模型后，我们将根据其表现来决定下一步的策略：

*   **如果 Site Prediction Accuracy 很高 (例如 > 0.8)**：这强烈表明数据中存在显著的站点特异性信号。ADHD 分类模型可能在无意中学习了这些站点特征，而不是真正的 ADHD 模式。在这种情况下，我们需要：
    *   **领域适应 (Domain Adaptation)**：尝试使用更复杂的 GNN 架构（如域对抗神经网络 DANN-GNN）或数据预处理方法来减少站点间的差异。
    *   **站点作为辅助特征**：在 ADHD 分类模型中引入站点 ID 作为额外特征或条件输入。
    *   **分站点训练与测试**：对每个站点独立训练或进行严格的留一站点交叉验证 (Leave-One-Site-Out Cross-Validation)。

*   **如果 Site Prediction Accuracy 较低 (例如 < 0.3，接近随机猜测)**：这表明站点间的 fMRI 特征差异不那么大，模型难以仅凭 fMRI 信号区分站点。这意味着我们之前的 ADHD 分类模型受站点偏置的影响可能较小，我们可以更专注于优化 ADHD 相关的特征提取和模型架构。

这个基准分析是理解我们的 ADHD 分类模型泛化能力的关键一步，尤其是在处理多中心 fMRI 数据时。
"""

import os
import pandas as pd
import numpy as np
from tqdm import tqdm
from nilearn import datasets
from nilearn.maskers import NiftiLabelsMasker
from nilearn.connectome import ConnectivityMeasure

# 1. 加载全量清单
BASE_DIR = "/content/drive/MyDrive/ADHD200-data/fmri"
manifest_full = pd.read_csv(os.path.join(BASE_DIR, "fmri_manifest.csv"))

# 清洗：确保路径存在且有标签
manifest_full = manifest_full.dropna(subset=["fmri_path", "final_label"])
manifest_full["final_label"] = manifest_full["final_label"].astype(int)
manifest_full = manifest_full[manifest_full["fmri_path"].map(os.path.exists)]

print(f"全量可用样本总数: {len(manifest_full)}")
display(manifest_full.groupby('site')['final_label'].value_counts().unstack().fillna(0))

# 2. 配置 Masker (Harvard-Oxford 48 ROI)
atlas_cort = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
roi_names = [label for label in atlas_cort.labels if label != 'Background']
TARGET_ROI = 48

masker = NiftiLabelsMasker(
    labels_img=atlas_cort.maps,
    labels=roi_names,
    standardize=True,
    detrend=True
)

# 3. 提取全量时间序列 (如果已经提取过部分，会自动跳过)
full_ts_dict = {}
full_labels_dict = {}

print("\n正在提取全量被试 ROI 时间序列 (可能需要较长时间)...")
for _, row in tqdm(manifest_full.iterrows(), total=len(manifest_full)):
    sub_id = row["subject_id"]
    # Check if subject_id already exists in full_ts_dict to avoid re-extracting if the notebook was run partially before
    if sub_id in full_ts_dict:
        continue

    try:
        ts = masker.fit_transform(row["fmri_path"])
        # 强制对齐 48 维
        if ts.shape[1] < TARGET_ROI:
            ts = np.pad(ts, ((0, 0), (0, TARGET_ROI - ts.shape[1])), mode='constant')
        else:
            ts = ts[:, :TARGET_ROI]

        full_ts_dict[sub_id] = ts
        full_labels_dict[sub_id] = row["final_label"]
    except Exception as e:
        # Log errors but don't stop the process for one subject
        print(f"Error extracting time series for {sub_id}: {e}")
        continue

print(f"\n成功提取 {len(full_ts_dict)} 个被试的时间序列。")

# Save the extracted data for later use to avoid re-extraction
SAVE_DIR = os.path.join(BASE_DIR, "processed_data")
os.makedirs(SAVE_DIR, exist_ok=True)
with open(os.path.join(SAVE_DIR, "full_ts_dict.pkl"), "wb") as f:
    pickle.dump(full_ts_dict, f)
with open(os.path.join(SAVE_DIR, "full_labels_dict.pkl"), "wb") as f:
    pickle.dump(full_labels_dict, f)
print(f"Processed time series and labels saved to {SAVE_DIR}")

import pickle
import os

BASE_DIR = "/content/drive/MyDrive/ADHD200-data/fmri"
LOAD_DIR = os.path.join(BASE_DIR, "processed_data")

# 检查文件是否存在
if not os.path.exists(os.path.join(LOAD_DIR, "full_ts_dict.pkl")):
    print(f"错误：未找到时间序列数据文件。请确保 {os.path.join(LOAD_DIR, 'full_ts_dict.pkl')} 存在。")
    full_ts_dict = {}
else:
    with open(os.path.join(LOAD_DIR, "full_ts_dict.pkl"), "rb") as f:
        full_ts_dict = pickle.load(f)
    print("时间序列数据已成功加载！")
    print(f"加载的时间序列样本数: {len(full_ts_dict)}")

if not os.path.exists(os.path.join(LOAD_DIR, "full_labels_dict.pkl")):
    print(f"错误：未找到标签数据文件。请确保 {os.path.join(LOAD_DIR, 'full_labels_dict.pkl')} 存在。")
    full_labels_dict = {}
else:
    with open(os.path.join(LOAD_DIR, "full_labels_dict.pkl"), "rb") as f:
        full_labels_dict = pickle.load(f)
    print("标签数据已成功加载！")
    print(f"加载的标签样本数: {len(full_labels_dict)}")

import pickle
import os

# Define BASE_DIR explicitly for this cell
BASE_DIR = "/content/drive/MyDrive/ADHD200-data/fmri"

# 定义保存路径
SAVE_DIR = os.path.join(BASE_DIR, "processed_data")
os.makedirs(SAVE_DIR, exist_ok=True)

try:
    # 保存时间序列字典
    with open(os.path.join(SAVE_DIR, "full_ts_dict.pkl"), "wb") as f:
        pickle.dump(full_ts_dict, f)
    print(f"时间序列数据已保存至: {os.path.join(SAVE_DIR, 'full_ts_dict.pkl')}")

    # 保存标签字典
    with open(os.path.join(SAVE_DIR, "full_labels_dict.pkl"), "wb") as f:
        pickle.dump(full_labels_dict, f)
    print(f"标签数据已保存至: {os.path.join(SAVE_DIR, 'full_labels_dict.pkl')}")

except Exception as e:
    print(f"保存数据时发生错误: {e}")

import torch
import numpy as np # Added for array operations
import torch.nn.functional as F # Added for F.cross_entropy
from torch.nn import Linear, Dropout # Added for GAT_v1 class
from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GATConv, global_mean_pool # Added for GAT_v1 class
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score # Added for evaluate function

# Define DEVICE here to ensure it's always available
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Definition of GAT_v1 class (copied from cell 696ce096)
class GAT_v1(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, heads=4):
        super().__init__()
        # heads=4 表示使用多头注意力，类似 Transformer 的机制
        self.conv1 = GATConv(in_channels, hidden_channels, heads=heads)
        self.conv2 = GATConv(hidden_channels * heads, hidden_channels, heads=1)
        self.fc = Linear(hidden_channels, 2)
        self.dropout = Dropout(0.5)

    def forward(self, x, edge_index, batch):
        x = self.conv1(x, edge_index).relu()
        x = self.dropout(x)
        x = self.conv2(x, edge_index).relu()
        x = global_mean_pool(x, batch)
        return self.fc(x)

# Definition of evaluate function (copied from cell zFIjAoLNPyN0)
@torch.no_grad()
def evaluate(model, loader, device):
    model.eval()

    all_probs = []
    all_preds = []
    all_true = []

    for batch in loader:
        batch = batch.to(device)
        out = model(batch.x, batch.edge_index, batch.batch)
        probs = torch.softmax(out, dim=1)[:, 1]
        preds = torch.argmax(out, dim=1)

        all_probs.extend(probs.cpu().numpy())
        all_preds.extend(preds.cpu().numpy())
        all_true.extend(batch.y.view(-1).cpu().numpy())

    all_probs = np.array(all_probs)
    all_preds = np.array(all_preds)
    all_true = np.array(all_true)

    if len(np.unique(all_true)) < 2:
        auc = np.nan
    else:
        auc = roc_auc_score(all_true, all_probs)

    acc = accuracy_score(all_true, all_preds)
    return auc, acc, all_true, all_probs, all_preds

# 1. 构建跨站点图数据
full_graphs = []
for sub_id, ts in full_ts_dict.items():
    corr = np.nan_to_num(np.corrcoef(ts.T), nan=0.0)
    x = torch.tensor(corr, dtype=torch.float32) # [48, 48]

    adj = np.abs(corr)
    np.fill_diagonal(adj, 0)
    edge_index = torch.tensor(np.array(np.nonzero(adj > 0.3)), dtype=torch.long)

    full_graphs.append(Data(x=x, edge_index=edge_index, y=torch.tensor([full_labels_dict[sub_id]], dtype=torch.long)))

# 2. 划分数据集 (分层抽样确保各站点比例)
train_idx, test_idx = train_test_split(
    range(len(full_graphs)),
    test_size=0.2,
    stratify=[g.y.item() for g in full_graphs],
    random_state=42
)

train_loader_full = DataLoader([full_graphs[i] for i in train_idx], batch_size=32, shuffle=True)
test_loader_full = DataLoader([full_graphs[i] for i in test_idx], batch_size=32)

# 3. 使用 GAT_v1 结构进行全量训练
model_full = GAT_v1(in_channels=48, hidden_channels=64, heads=4).to(DEVICE)
optimizer = torch.optim.Adam(model_full.parameters(), lr=0.0005, weight_decay=1e-3)

print("开始全量跨站点 GAT 训练...")
for epoch in range(1, 31):
    model_full.train()
    total_loss = 0
    for batch in train_loader_full:
        batch = batch.to(DEVICE)
        optimizer.zero_grad()
        out = model_full(batch.x, batch.edge_index, batch.batch)
        loss = F.cross_entropy(out, batch.y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    # 评估
    auc, acc, _, _, _ = evaluate(model_full, test_loader_full, DEVICE)
    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:02d} | Loss: {total_loss/len(train_loader_full):.4f} | Test AUC: {auc:.4f} | Test ACC: {acc:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns # Added import for seaborn
from sklearn.metrics import RocCurveDisplay, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay, accuracy_score
import numpy as np

# Assuming model_full, test_loader_full, DEVICE and evaluate function are defined and trained from previous steps

# Perform final evaluation to get true labels and probabilities
final_auc, final_acc, y_true_full_eval, y_prob_full_eval, y_pred_full_eval = evaluate(model_full, test_loader_full, DEVICE)

print(f"Final Test AUC: {final_auc:.4f}")
print(f"Final Test Accuracy: {final_acc:.4f}")

# Plot ROC Curve
fig, ax = plt.subplots(figsize=(8, 6))
if final_auc is not None and not np.isnan(final_auc):
    RocCurveDisplay.from_predictions(y_true_full_eval, y_prob_full_eval, name=f"GAT Model (AUC = {final_auc:.4f})", ax=ax)
    ax.plot([0, 1], [0, 1], 'r--', label='Random Classifier (AUC = 0.5)')
    ax.set_title('ROC Curve for Full Dataset GAT Model')
    ax.legend(loc='lower right')
else:
    ax.text(0.5, 0.5, 'AUC cannot be computed (single class in test set)', horizontalalignment='center', verticalalignment='center', transform=ax.transAxes)
    ax.set_title('ROC Curve (Not Computable)')

plt.grid(True)
plt.show()

# Optionally, also display confusion matrix and probability distribution again for completeness
fig_cm, ax_cm = plt.subplots(1, 2, figsize=(15, 6))

# Confusion Matrix
cm_full_eval = confusion_matrix(y_true_full_eval, y_pred_full_eval)
disp_full_eval = ConfusionMatrixDisplay(confusion_matrix=cm_full_eval, display_labels=['Control', 'ADHD'])
disp_full_eval.plot(ax=ax_cm[0], cmap='Greens')
ax_cm[0].set_title(f'Full Dataset GAT Confusion Matrix (ACC: {final_acc:.2f})')

# Probability Distribution
sns.histplot(y_prob_full_eval[y_true_full_eval == 1], color='red', label='ADHD', kde=True, ax=ax_cm[1], bins=15, alpha=0.5)
sns.histplot(y_prob_full_eval[y_true_full_eval == 0], color='blue', label='Control', kde=True, ax=ax_cm[1], bins=15, alpha=0.5)
ax_cm[1].set_title(f'Full Dataset GAT Prob Distribution (AUC: {final_auc:.4f})')
ax_cm[1].set_xlabel('Probability of being ADHD')
ax_cm[1].legend()

plt.tight_layout()
plt.show()

print(f"Test Set Real Label Distribution: {np.bincount(y_true_full_eval)}")
print(f"GAT Model Predicted Distribution: {np.bincount(y_pred_full_eval)}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from torch_geometric.loader import DataLoader

# Assuming full_graphs, test_idx, model_full, evaluate function, full_ts_dict, manifest_full, and DEVICE are available from previous cells.

# 1. Create a mapping from subject_id to site
subject_to_site_map = manifest_full.set_index('subject_id')['site'].to_dict()

# Get the ordered list of subject_ids from full_ts_dict (used to create full_graphs)
ordered_subject_ids = list(full_ts_dict.keys())

# Create a list of (graph, site) pairs for all graphs
all_graphs_with_sites = []
for i, graph in enumerate(full_graphs):
    sub_id = ordered_subject_ids[i]
    site = subject_to_site_map.get(sub_id)
    if site is not None:
        all_graphs_with_sites.append({'graph': graph, 'site': site, 'subject_id': sub_id, 'original_idx': i})

# Filter to include only graphs that were part of the original test set
test_graphs_with_sites = [item for item in all_graphs_with_sites if item['original_idx'] in test_idx]

# 2. Collect performance results per site
site_performance = []
unique_sites = manifest_full['site'].unique()

print("Evaluating performance per site on the test set...")
for site_name in unique_sites:
    site_specific_test_graphs_data = [item['graph'] for item in test_graphs_with_sites if item['site'] == site_name]

    if len(site_specific_test_graphs_data) == 0:
        print(f"Skipping site {site_name}: no subjects in the test set.")
        continue

    site_labels_test = [g.y.item() for g in site_specific_test_graphs_data]

    # Check for single-class cases in the site's test data to avoid AUC errors
    if len(np.unique(site_labels_test)) < 2:
        print(f"Skipping site {site_name}: only one class present ({np.unique(site_labels_test)}) in the test subset. AUC not computable.")
        # Still calculate accuracy if possible
        site_loader = DataLoader(site_specific_test_graphs_data, batch_size=32, shuffle=False)
        _, acc, _, _, _ = evaluate(model_full, site_loader, DEVICE)
        site_performance.append({"Site": site_name, "AUC": np.nan, "Accuracy": acc, "N_Subjects": len(site_specific_test_graphs_data)})
        continue

    site_loader = DataLoader(site_specific_test_graphs_data, batch_size=32, shuffle=False)
    auc, acc, _, _, _ = evaluate(model_full, site_loader, DEVICE)
    site_performance.append({"Site": site_name, "AUC": auc, "Accuracy": acc, "N_Subjects": len(site_specific_test_graphs_data)})

df_site_performance = pd.DataFrame(site_performance)
print("\nModel Performance per Site (on Test Set):")
display(df_site_performance.sort_values(by="AUC", ascending=False))

# 3. Visualize results
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# AUC plot
sns.barplot(x="Site", y="AUC", data=df_site_performance.sort_values(by="AUC", ascending=False), ax=axes[0])
axes[0].set_title("GAT Model AUC per Site (Test Set)")
axes[0].set_ylim(0, 1)
axes[0].tick_params(axis='x', rotation=45)

# Accuracy plot
sns.barplot(x="Site", y="Accuracy", data=df_site_performance.sort_values(by="Accuracy", ascending=False), ax=axes[1])
axes[1].set_title("GAT Model Accuracy per Site (Test Set)")
axes[1].set_ylim(0, 1)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# Print label distributions per site in test set
print("\nTest Set Label Distribution per Site:")
site_label_counts = {}
for item in test_graphs_with_sites:
    site = item['site']
    graph_label = item['graph'].y.item()
    if site not in site_label_counts:
        site_label_counts[site] = {'Control': 0, 'ADHD': 0}
    if graph_label == 0:
        site_label_counts[site]['Control'] += 1
    else:
        site_label_counts[site]['ADHD'] += 1

df_site_label_counts = pd.DataFrame.from_dict(site_label_counts, orient='index')
display(df_site_label_counts)

"""为了分析模型在各站点间的预测性能差异：

首先，将从原始清单 manifest_full 中提取每个被试的站点信息。
然后，将根据之前训练时划分的测试集 (test_idx)，筛选出属于每个站点的测试样本。
接着，为每个站点创建独立的数据加载器，并使用训练好的 model_full 对其进行评估，计算该站点的 AUC 和准确率。
最后，将这些结果可视化，并展示每个站点在测试集中的实际标签分布，以便更好地理解模型的表现。
这将帮助我们识别模型在哪些站点表现较好，哪些站点可能存在性能瓶颈。

我们来看一下模型在各个站点测试集上的预测性能分析结果。

**模型各站点性能表现概览：**

-   **NYU** 站点表现最佳，AUC 达到 **0.796**，准确率 **0.735**。
-   **Peking_1** 和 **OHSU** 站点的 AUC 也很不错，分别为 **0.697** 和 **0.681**。
-   **Peking_3** 和 **Peking_2** 的 AUC 略低，分别为 **0.444** 和 **0.432**。
-   **NeuroIMAGE** 和 **KKI** 站点的 AUC 相对较低，分别为 **0.300** 和 **0.000**。
-   **Pittsburgh** 站点因为测试集中只包含 `Control` 组（标签 0），导致无法计算 AUC，但其准确率高达 **0.8125**，这表明模型可能将该站点的所有样本都预测为了 Control，与实际情况一致。

**关键发现与分析：**

1.  **站点异质性显著：** 模型在不同站点之间的表现差异巨大。NYU 站点取得了非常好的结果，而 KKI 和 NeuroIMAGE 站点则表现较差。这突显了跨站点数据在神经影像分析中面临的“站点效应”或“领域漂移”问题。
2.  **AUC 不可计算的站点：** Pittsburgh 站点在测试集中只有 `Control` 组，这意味着模型在这种情况下无法区分两个类别，因此 AUC 无法计算。但其高准确率也暗示了模型可能在这种单类别分布下出现了“分类坍塌”现象，即全部预测为多数类。
3.  **部分站点性能低迷：** KKI 和 NeuroIMAGE 站点的低 AUC 可能有几个原因：
    *   **样本量过小：** KKI 只有 17 个测试样本，NeuroIMAGE 只有 11 个。样本量小更容易受到偶然因素影响，导致性能不稳定或难以学习通用模式。
    *   **标签分布不均衡：** KKI 站点测试集中有 13 个 Control 和 4 个 ADHD，这种不平衡可能影响模型的学习。
    *   **数据质量或特征差异：** 这些站点的数据可能与其他站点存在较大的采集协议、扫描仪类型、预处理流程等差异，导致模型学到的特征不具备泛化性。

**下一步思考：**

为了提高模型在所有站点上的泛化能力，我们需要进一步处理站点间的数据异质性。例如：

*   **领域适应（Domain Adaptation）技术：** 尝试使用对抗学习或度量学习等方法，让模型学习到站点不变的特征。
*   **数据增强：** 为样本量较小的站点或类别进行数据增强。
*   **站点作为特征：** 在模型中加入站点信息作为额外的特征，帮助模型区分不同站点的特点。

可视化图表也直观地展示了这些差异，特别是 AUC 和准确率在不同站点之间的波动。

## 模型版本对比分析：

### 1. GCN_v1 (初始版本)

*   **主要特点**: 最初的 GCN 模型，节点特征起初可能设置不当，同时在构图阶段对不满足 48 个 ROI 的样本直接丢弃。
*   **使用的样本**: 仅 NYU 站点，且因为严格的 ROI 维度要求，最终仅保留了 **32** 个样本进行训练（如 `bcnA4gD9fHqP` 中的 `Final usable graphs with consistent dimension (48): 32` 所示）。
*   **性能表现**: 表现非常差，出现了严重的 **“分类坍塌”（Classification Collapse）** 问题。模型倾向于将所有样本预测为同一个类别，导致 AUC 接近 0.5 甚至更低，准确率也仅反映了多数类的比例。
*   **主要问题**:
    *   节点特征信息量不足 (最初可能仅使用 ROI 均值，或 FC 矩阵的维度传入方式有误)。
    *   图维度不一致导致大量样本被丢弃。
    *   模型无法从极其稀疏的训练数据中学习到有效模式。

### 2. GCN_v2 (改进节点特征版本)

*   **主要特点**: 解决了 GCN_v1 的关键问题，将 **FC 矩阵的每一行作为节点的特征**（即每个节点有 48 维特征），并确保所有时间序列都经过了 ROI 的填充/截断，强制统一为 48 个节点。
*   **使用的样本**: 仅 NYU 站点，共 **216** 个样本（如 `zFIjAoLNPyN0` 所示）。
*   **性能表现**:
    *   **Test AUC**: 最高触及 0.63，最终稳定在 **0.58** 左右（如 `0apMKC-X3X8f` 中的 `Epoch 15 | Test AUC: 0.5938`）。
    *   **Test Accuracy**: 提升到 **0.59** 左右。
    *   **主要改进**: 模型摆脱了分类坍塌，开始能够区分两个类别。红色（ADHD）和蓝色（Control）的概率分布图首次出现了一定的分离。
*   **主要问题**: 仍然存在过拟合迹象，AUC 在训练后期有波动和下降。

### 3. GAT_v1 (引入注意力机制的全量数据集版本)

*   **主要特点**: 在 GCN_v2 的基础上，将 `GCNConv` 替换为 `GATConv`，引入了 **注意力机制**，使得模型能够学习到不同脑区连接的重要性。同时，在 **全量跨站点数据集** (794 个样本) 上进行训练和评估。
*   **使用的样本**: **全量跨站点数据集** (794 个样本)，测试集 159 个样本（如 `c7447d44` 所示）。
*   **性能表现 (全量测试集)**:
    *   **Test AUC**: 最终稳定在 **0.6397** (如 `c7447d44` 所示)。
    *   **Test Accuracy**: 最终达到 **0.6855**。
*   **性能表现 (分站点)**: (如 `2dfc48b8` 输出所示)
    *   **NYU**: **AUC 0.796**，Accuracy 0.735
    *   **Peking_1**: AUC 0.697，Accuracy 0.719
    *   **OHSU**: AUC 0.681，Accuracy 0.680
    *   **Peking_3**: AUC 0.444，Accuracy 0.500
    *   **Peking_2**: AUC 0.432，Accuracy 0.556
    *   **NeuroIMAGE**: AUC 0.300，Accuracy 0.455
    *   **KKI**: AUC 0.000，Accuracy 0.765 (测试集样本不均衡，AUC可能无法有效计算)
    *   **Pittsburgh**: AUC NaN，Accuracy 0.8125 (测试集只有单一类别)
*   **主要改进**:
    *   注意力机制有效地帮助模型从复杂的脑网络中提取诊断信号，表现出更强的泛化能力。
    *   概率分布图中 ADHD 和 Control 组的曲线分离度更高。
    *   不再出现分类坍塌，预测类别分布与真实标签分布更接近。
*   **主要问题**: 站点异质性显著，在部分站点表现不佳，提示存在“站点效应”或“领域漂移”问题。

### 4. GAT_v2 (高隐藏层维度版本)

*   **主要特点**: 在 GAT_v1 的基础上，**增加了隐藏层维度到 128**，并略微提高了 Dropout 比例（0.6），旨在增强模型捕捉复杂模式的能力。
*   **使用的样本**: **全量跨站点数据集**。
*   **性能表现**:
    *   **Test AUC**: 训练初期曾触及 0.6667，但随后回落，最终稳定在 **0.6188**（如 `fa5bfa4c` 所示）。
*   **主要问题**:
    *   出现了 **过拟合迹象**。虽然模型容量增加，但在现有样本量下，反而导致模型开始“死记硬背”训练集的噪声，泛化能力下降。
    *   性能略低于 GAT_v1，表明在当前数据集规模下，一味增加模型复杂度并非最优解。

### 总结

| 模型版本 | 主要改进 | 使用数据集 | 整体 AUC (最高/最终) | 整体 Accuracy (最终) | 关键观察 |
| :------- | :------- | :------- | :------------------ | :------------------ | :------- |
| GCN_v1   | 初始模型 | NYU (32) | ~0.50 (分类坍塌)    | 0.55 (类比例)      | 严重分类坍塌，无法学习 |
| GCN_v2   | FC行作特征 | NYU (216) | ~0.63 / 0.58        | 0.59                | 解决分类坍塌，开始学习 |
| GAT_v1   | 引入注意力 | 全量 (794) | ~0.66 / **0.64**    | **0.69**            | 性能提升，但站点差异大 |
| GAT_v2   | 增加隐藏层 | 全量 (794) | ~0.67 / 0.62        | -                   | 过拟合，性能略有下降 |

**GAT_v1** 在全量数据集上取得了最佳的泛化性能，尤其在 NYU 站点表现突出，证明了注意力机制在脑网络分析中的有效性。然而，站点间的性能差异巨大是当前模型面临的主要挑战，需要进一步研究 **领域适应** 方法来缓解这一问题。

## 🚀 第13部分：缓解站点效应 - 领域适应（Domain Adaptation）

目前的分析结果明确指出，模型在不同站点上的性能差异巨大，尤其是在某些站点表现不佳。这强烈表明我们的模型受到了 **“站点效应”（Site Effect）** 的影响。模型可能在无意中学习了特定站点的特征，而不是真正的 ADHD 生物学模式。为了解决这个问题，我们需要引入 **领域适应（Domain Adaptation）** 技术。

### 什么是领域适应？

领域适应是一类机器学习方法，旨在解决当训练数据（源域）和测试数据（目标域）的分布存在差异时，模型性能下降的问题。在我们的场景中：

*   **源域**：模型在所有站点上学习到的共同特征，或者性能较好的站点的数据。
*   **目标域**：性能较差的站点的数据，它们与源域的数据分布存在差异。

领域适应的目标是训练一个模型，使其能够从不同的数据分布中提取出 **领域不变（Domain-Invariant）** 的特征，从而提升模型在所有站点上的泛化能力。

### 为什么需要领域适应？

*   **扫描设备差异**：不同医院的 fMRI 扫描仪型号、磁场强度、序列参数等都可能不同。
*   **采集协议差异**：静息态 fMRI 扫描时长、指令（睁眼/闭眼）等可能存在差异。
*   **被试群体差异**：不同站点的被试年龄、人种、药物使用情况等可能存在系统性差异。
*   **预处理流程差异**：即使原始数据相似，不同的预处理流程也会引入差异。

### 常见的领域适应策略：

1.  **基于对抗学习的方法（Adversarial Domain Adaptation）**：
    *   **核心思想**：引入一个“领域判别器”（Domain Discriminator），让主分类器（例如 GNN）在预测 ADHD 的同时，学习去“欺骗”领域判别器，使其无法分辨一个样本是来自哪个站点。这样，主分类器就被迫学习与站点无关的特征。
    *   **代表模型**：DANN（Domain-Adversarial Neural Network）、CDANN 等。

2.  **基于度量学习的方法（Metric Learning-based Domain Adaptation）**：
    *   **核心思想**：学习一个特征映射，使得不同领域中相同类别的样本在特征空间中距离更近，而不同类别的样本距离更远。

3.  **基于重加权或采样的方法**：
    *   **核心思想**：通过调整不同站点样本的权重或进行重采样，使得训练数据在领域分布上更接近。

4.  **站点作为辅助特征**：
    *   **核心思想**：直接将站点 ID 或 One-Hot 编码后的站点信息作为模型的输入特征之一，让模型显式地考虑站点差异。

在接下来的步骤中，我们将着重探索 **基于对抗学习的领域适应方法（DANN-GNN）**，尝试构建一个能够学习领域不变特征的图神经网络模型，以期在所有站点上取得更稳定的诊断性能。
"""